### ISSUE TITLE
TileLayer loading event

### ISSUE THREAD

**Issue by gsahbi** [visgl/loaders.gl#1010]
I have a tile layer from a remote server and requests take a bit of time to process.
is there a way to intercept the loading / finished loading events in order to show a spinner ?

**Comment by ibgreen** [comment]
For 3D tiles and I3S, we do have `onTileLoad` but we don't have an `onTileLoadStart` see https://loaders.gl/modules/tiles/docs/api-reference/tileset-3d#constructor-1

You could however use the tilesets embedded `stats` object which tracks, among other things, how many tiles are being loaded, see e.g. https://github.com/visgl/loaders.gl/blob/master/examples/website/i3s/app.js#L112
