### ISSUE TITLE
Running conversion with bundle (converter.min.js) is failing in finding 'draco_decoder.wasm'

### ISSUE THREAD

**Issue by Tamrat-B** [visgl/loaders.gl#1051]
node converter.min.js --input-type 3dtiles --tileset https://assets.cesium.com/29328/tileset.json --name CairoLayer --max-depth 4 --egm /home/<user>/pgm/egm2008-5/geoids/egm2008-5.pgm --slpk

is failing with:

Error: ENOENT: no such file or directory, open '/draco_decoder.wasm'
failed to asynchronously prepare wasm: RuntimeError: abort(Error: ENOENT: no such file or directory, open '/draco_decoder.wasm'). Build with -s ASSERTIONS=1 for more info.
RuntimeError: abort(Error: ENOENT: no such file or directory, open '/draco_decoder.wasm'). Build with -s ASSERTIONS=1 for more info.
A 3D tile failed to load: undefined abort(Error: ENOENT: no such file or directory, open '/draco_decoder.wasm'). Build with -s ASSERTIONS=1 for more info.

**Comment by ibgreen** [comment]
Discussed with @belom88, this is related to the upgrade to Draco 1.4 which required changes to how we load Draco in browser and Node. We are looking into it.
