### ISSUE TITLE
Polyfills not working in IE11

### ISSUE THREAD

**Issue by tonetechnician** [visgl/loaders.gl#1065]
Hey there,

I'm trying to use the provided polyfills for a playcanvas integration. For the PR to be accepted I've been asked to also allow for IE11 support. You can find the PR in progress [here](https://github.com/playcanvas/engine/pull/2617). 

Unfortunately I keep running into syntax errors. It looks as if ES6 syntax such as async functions are included in the @loaders.gl/polyfills.

Similarly, I keep getting thrown an error that Const is used in @loaders.gl/core. Is there something I'm missing with the usage of the polyfills provided by loaders.gl? Would I need to use babel to make these work, or is there another solution?

Thanks!

**Comment by ibgreen** [comment]
Are you installing from npm? The npm modules have multiple dist folders. The non-`es6` distributions should be fully transpiled to ES5 (no async and const).

What bundler are you using? webpack? You may be able to look at the `mainFields` setting to make sure it is not including the `es6` distribution.

**Comment by tonetechnician** [comment]
Thanks for the fast reply @ibgreen 

I'm simply loading loaders.gl from a cdn at the top of my html script. This is the format the playcanvas prefers for their demoes. You can see how I'm doing so here --> https://github.com/tonetechnician/engine/blob/loaders.gl-example/examples/loaders/loader-loaders.gl.html


I've now incorporated the babel-standalone at the top of my html, along with the fetch polyfill as follows and I'm no longer having issues with es6 features:

```html
    <script src="https://unpkg.com/whatwg-fetch@3.0.0/dist/fetch.umd.js"></script>
    <script src="https://unpkg.com/core-js@2.6.0/client/core.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/regenerator-runtime@0.13.7/runtime.min.js"></script>
    <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
    <script type="text/babel" src="https://unpkg.com/@loaders.gl/core@2.3.7/dist/dist.min.js"></script>
    <script type="text/babel" src="https://unpkg.com/@loaders.gl/draco@2.3.7/dist/dist.min.js"></script>
    <script type="text/babel" src="https://unpkg.com/@loaders.gl/ply@2.3.7/dist/dist.min.js"></script>

    <script type="text/babel">
       <!-- ... rest of script in loader-loaders.gl.html -->
    </script>
```

That being said, I'm now getting issues with the loaders worker thread. 

```js
"draco-worker@2.3.7 (#1 of 5): WorkerThread.process() failed Script Error :0:0"
```

This seems to only happen with the Draco loader, although I'm unable to test with the PLY loader yet as IE11 keeps dropping the network request.

**Comment by ibgreen** [comment]
Understood. The scripts are built separately from the npm modules. Perhaps they are not built with full transpilation. It is worth an investigation.

**Comment by tonetechnician** [comment]
Thanks @ibgreen 

Just a quick question, is there a place I can find es5 cdn distributions of loaders.gl? Or are they supposed to be incorporated in the dist.min.js in unpkg? My hope is this would avoid me needing to incorporate my own babel transpilation when importing the loaders.gl modules.

**Comment by ibgreen** [comment]
> I guess if they were built with full transpilation I could then have them load in IE11 without any of my own transpilation. 

Yes. The idea is that `dist.min.js` should be fully transpiled to ES5, and `dist.dev.js` should be minimally transpiled. 

> That being said, I'm now getting issues with the loaders worker thread.

There may be some issues with Worker Threads in IE11 (I didn't even realize that they were supported). We are not able to test that. 

If you have a reasonable fix your are welcome to open a PR. 

If not, you can try to provide a `{worker: false}` option to your `load` calls.

**Comment by tonetechnician** [comment]
Thanks @ibgreen 

It would seem IE11 does have support for [workers](https://developer.mozilla.org/en-US/docs/Web/API/Worker) threads, but no [shared workers](https://developer.mozilla.org/en-US/docs/Web/API/SharedWorker). Upon using the load function with `{worker: false}`, it has loaded the model successfully, although it the model looks weird due to what seems to be a playcanvas error.

![image](https://user-images.githubusercontent.com/13471797/102931932-042a2f00-44a8-11eb-9b6d-bec1fa770c90.png)

So looks then that it might just be es5 transpilation not happening within the dist.min.js. 

Thanks for the fast replies! This has helped alot!

**Comment by ibgreen** [comment]
Just a thought - the workers are also transpiled into separate scripts, and loaded from unpkg.com during runtime - it could be that something in those scripts is also untranspiled.

**Comment by dryabinin-actionengine** [comment]
@tonetechnician Hello. V2.3.9 is published with ES5 transpilation fix. You are welcome to use it.

**Comment by tonetechnician** [comment]
Thanks @dryabinin-actionengine. I'll do this and feedback, I appreciate the notification!

**Comment by tonetechnician** [comment]
Hey @dryabinin-actionengine 

Thanks for the fix! I've been able to include the es5 module with no issue now.
