### ISSUE TITLE
glTF Model loading fails in `loadImages` - `gltf.buffer` undefined

### ISSUE THREAD

**Issue by ibgreen** [visgl/loaders.gl#1073]
Downloading and dropping the following gltf file on the loaders.gl glTF example crashes https://resource-1300645485.cos.ap-chengdu.myqcloud.com/model/Haier/H5Draco.gltf

See https://github.com/visgl/deck.gl/discussions/5289

**Comment by belom88** [comment]
The root cause is buffer storage.
The file has 1 buffer which is stored in the `json` part in URL as very very long base64 string:
```
json: {
...
buffers: [
  0: {
    byteLength: 5246732,
    name: "H5Draco",
    uri: "data:application/octet-stream;base64,RFJBQ08CAgEBA............."
  }
],
....
}
```

`loaders.gl` expects the buffer is stored as binary chunk.

**Comment by belom88** [comment]
@ibgreen should we implement `base64` `uri` support for `GLTF` buffers?

**Comment by ibgreen** [comment]
We used to have this support. The idea is that we just use `fetch` to asynchronously decode base64 buffers.
https://github.com/visgl/loaders.gl/blob/master/modules/gltf/src/lib/parse-gltf.js#L109

I don't find any comments near the fetch, that would be nice to add. But I do find:
https://github.com/visgl/loaders.gl/blob/master/modules/gltf/src/lib/parse-gltf.js#L32

I think this bug may be a regression introduced in 
https://github.com/visgl/loaders.gl/blame/master/modules/gltf/src/lib/parse-gltf.js#L33

- If this is really a regression, we are clearly missing a test case for base64 encoded buffers. 
- And adding a JSDoc comment header to the `loadBuffers` function mentioning base64 seems like a good idea.

**Comment by ibgreen** [comment]
@vdunaev https://github.com/visgl/deck.gl/discussions/5289#discussioncomment-278190 users are waiting for this patch
