### ISSUE TITLE
glTF: Performance when loading large models

### ISSUE THREAD

**Issue by ibgreen** [visgl/loaders.gl#1082]
Investigate performance when loading large GLB files. See discussion in https://github.com/visgl/deck.gl/discussions/5305

Public URL to the file - https://resource-1300645485.cos.ap-chengdu.myqcloud.com/model/test/factory.glb

This online viewer - https://gltf-viewer.donmccurdy.com/ which renders the file well (based on the three.js.)

**Comment by belom88** [comment]
Downloading the file from the server is slow. It takes a few minutes to download it. https://gltf-viewer.donmccurdy.com/ works with local files so it doesn't waste time on downloading.
I checked loading of this file with "loaders.gl" from local file system. It works approximately with the same speed.

**Comment by ibgreen** [comment]
@sunyonglincanada See above

**Comment by sunyonglincanada** [comment]
> @sunyonglincanada See above

Thanks @ibgreen and @belom88 for the updates. I've tried to load this file from local file system and it was much better now for the loading speed. However, once the model is loaded,  it seems like the frame rate is pretty low to around 5-6 FPS which feels like the model is freezing and you cannot drag/spin it.  I am wondering if is there a way to optimize this issue as well?

**Comment by belom88** [comment]
> However, once the model is loaded, it seems like the frame rate is pretty low to around 5-6 FPS which feels like the model is freezing and you cannot drag/spin it.

@ibgreen  I suppose it is not the @loaders.gl issue, possibly deck or luma...

**Comment by ibgreen** [comment]
Yes. Closing this here for now.
