### ISSUE TITLE
Loaders.GL Github Pages Site is down.

### ISSUE THREAD

**Issue by jay-manday** [visgl/loaders.gl#1090]
Hey there! 

Just a friendly note that the Loaders.gl github pages site is down. It's been a v handy ref for all the great work you guys have put into this lib.

Thanks!

**Comment by ibgreen** [comment]
Yes looks like our github pages setup has been hacked. Be careful!

**Comment by ibgreen** [comment]
We are back in business. 

It is apparently tricky, once a domain has been pointed to github pages, there are cases where another page can step in and take control. Our new setup is supposed to avoid this.

**Comment by jay-manday** [comment]
Awesome! thanks for getting on this so quickly
