### ISSUE TITLE
Excel / Spreadsheet loader

### ISSUE THREAD

**Issue by ibgreen** [visgl/loaders.gl#1098]
https://github.com/SheetJS/sheetjs appears to be a powerful spreadsheet loading library. It would be good to have a loaders.gl integration.

First weed to decide the name of the module

- `@loaders.gl/excel`
- `@loaders.gl/spreadsheets`

Also need to decided what to load. Spreadsheets can contain multiple tabs etc. Do we just pick a default one?

@RandomFractals

**Comment by kylebarron** [comment]
Another common issue with spreadsheets is that data is sometimes stored in a "visual" way instead of a "clean data" way, which makes it impossible to accurately import into a tabular storage format. How would the loader treat these cases? Throw an error?

**Comment by RandomFractals** [comment]
I would prefer `@loaders/excel` and we'll have to decided on what Excel file formats we want to support in that loader. There are quite a few of them beyond just basic `.xlsb` and `.xlsx`.

Defaulting to the first spreadsheet sounds reasonable. I'll have to go back and look at tabular loaders api and see if there are some parse options we can set/pass for loading other spreadsheets from a workbook.

For a quick usage example, please see this data provider TS implementation from my data preview vscode extension that hadles a few of those file formats: https://github.com/RandomFractals/vscode-data-preview/blob/master/src/data.providers/excel.data.provider.ts

**Comment by RandomFractals** [comment]
@kylebarron not sure what you mean by "visual" way. Spreadsheets are tables with column names, no different from CVS. Sure, most Excel data is dirty and might require some cleansing, but I don't think it's the loaders job to do that, as long as we can load and map that tabular data.

**Comment by kylebarron** [comment]
> not sure what you mean by "visual" way.

The Excel format is a _huge superset_ of CSV, and Excel files are much more often edited by hand than a CSV file.

- Header columns put in "merged cells"
- Multiple header rows
- Empty "margin rows" and "margin columns" to the left and above where the data starts. E.g. the top left corner of valid data is not A1.
- Multiple logical tables in a single Excel sheet, separated by empty columns or rows.
- Generated columns: if a column is auto-generated using an equation and source cells, does the Excel format store the function itself or the result of the function? I'd assume the former... so would a loader need to resolve the function?

**Comment by ibgreen** [comment]
> I would prefer @loaders.gl/excel and we'll have to decided on what Excel file formats we want to support in that loader. There are quite a few of them beyond just basic .xlsb and .xlsx.

Sounds good - sheetsjs seems to be a bit of a kitchen sink that also support non-excel formats, but agree that excel is the highlight.

> Defaulting to the first spreadsheet sounds reasonable. I'll have to go back and look at tabular loaders api and see if there are some parse options we can set/pass for loading other spreadsheets by name from a workbook.

As long as we are only loading one table we are good. We could certainly provide an `options.excel.sheet: 'sheetName'` prop for specifying the name of the table to load. 

We are discussing adding a layers concept as some geospatial formats also support layers. But let's start with a single tab.

> The Excel format is a huge superset of CSV, and Excel files are much more often edited by hand than a CSV file.

I am assuming that all that is extra information on top of an underlying table and it would not be preserved by our loader. Fancy stuff will be stripped.

**Comment by RandomFractals** [comment]
actually, that library does some of the Excel data cleansing and filters out all the visual noise found in the spreadsheets.

You bring up good points, but how is that different from invalid or sparsely formatted CSV?

I use that lib in my extension and have not seen any complaints for the issues you raise, even tho most devs use it for loading Excel files.

So, I'd say we support Excel spreadsheets relying on that library to cleanup/collate some data, which it does already.

Super fancy spreadsheets with pivot tables might not work, but how often do we use those as inputs for data analytics?

**Comment by kylebarron** [comment]
> You bring up good points, but how is that different from invalid or ill and sparsely formatted CSV?

Mostly that in my experience weirdly-formatted Excel is much more common than CSV, since Excel is more often formatted by hand, whereas CSV is more often created from a program.

Mostly my worry is that every other loader in the existing loaders.gl catalog (with the notable exception of CSV) has a rigid specification behind it that enables straightforward data loading, so that any valid input will be successfully read into a common output format. Many excel files I've seen would be impossible to load into a table without manual cleaning (while still meeting the Excel spec).

**Comment by kylebarron** [comment]
I think it'll be good to have a loaders.gl module for Excel, and if it handles the majority of the cases that'll be great. I think we'll just need to make clear to users that there are some edge cases that might not be handled by the loader.

**Comment by RandomFractals** [comment]
yes. we'll have to list edge cases for what's supported for the Excel formats and test it out. 

I get where you are coming from Excel spreadsheets is not geojson, doesn't not have rigit table structure as some other data formats supported by this loaders lib might have, yet it's frequently used as the raw data dumps in many data analytics products. 

Why I think it would be good to have that option for other apps using loaders.gl to have it as an option for loading raw data.

**Comment by ibgreen** [comment]
Closed by https://github.com/visgl/loaders.gl/pull/1106
