### ISSUE TITLE
2.3.8: glTF regression: Default glTF up Axis changed

### ISSUE THREAD

**Issue by ibgreen** [visgl/loaders.gl#1100]
- 3d-tiles + gltf is broken with loaders.gl@2.3.8
- website is built with 2.3.0 and is working as expected
- to test, run playground > Tile3DLayer (new york) on master

![image (9)](https://user-images.githubusercontent.com/7025232/104650082-89010680-566a-11eb-8425-6aa0bc989483.png)

@Pessimistress

**Comment by dryabinin-actionengine** [comment]
@ibgreen It is not reproduced on `master` branch.
My steps to reproduce:

1. Go to the` examples/website/3d-tiles`
2. Commands: ` yarn / yarn start-local`
3. Select `New York` from dropdown
4. Check this bug

What I am seeing:
![image](https://user-images.githubusercontent.com/70207219/104712736-f7f66200-5733-11eb-9b9b-109c366f29ea.png)

Maybe I am not understand you steps. Could you provide more details please?

**Comment by ibgreen** [comment]
This bug is happening in deck.gl repository - it has a similar 3D tiles example. Please test there.

**Comment by Pessimistress** [comment]
This seems to be caused by unmatching loader module versions (a mix of 2.3.0 and 2.3.8). I removed my local lock file and reinstalled and the issue went away.
