### ISSUE TITLE
Pass through options to DracoLoader

### ISSUE THREAD

**Issue by ibgreen** [visgl/loaders.gl#1116]
See https://github.com/visgl/loaders.gl/pull/1113#issuecomment-762348315

Options are not being passed through to DracoLoader here.

https://github.com/visgl/loaders.gl/blob/master/modules/3d-tiles/src/lib/parsers/parse-3d-tile-point-cloud.js#L207

@avernus

**Comment by Avnerus** [comment]
Thank you! When and if you do pass the options here, please first `delete options['3d-tiles'];` as in https://github.com/visgl/loaders.gl/pull/1113.
