### ISSUE TITLE
Full tileset is passed through Tileset3DLoader options

### ISSUE THREAD

**Issue by ibgreen** [visgl/loaders.gl#1118]
This is putting megabytes of data in what is supposed to be a small options object.

**Comment by ibgreen** [comment]
@Avnerus

**Comment by belom88** [comment]
@ibgreen  do you mean https://github.com/visgl/loaders.gl/blob/f0a61eef2cbc4b910d2969c4b439be179a41d239/modules/3d-tiles/src/tiles-3d-loader.js#L28 ?
This is just reference to the parent `tileset`. We don't have memory leaks here.

**Comment by ibgreen** [comment]
An object with options is supposed to be small. A `tileset` can be several megabytes of tile headers with bounding boxes etc.

The problem is that to parse on workers we need to serialized and deserialize any non-binary data. For small objects that is OK but for an entire tileset.json that is really slow.
