### ISSUE TITLE
Pre-built bundles broken in 2.3.9

### ISSUE THREAD

**Issue by Pessimistress** [visgl/loaders.gl#1132]
The global `loaders` object is no longer populated.
https://codepen.io/Pessimistress/pen/LYRKMqK?editors=1000

Console log:
`dist.min.js:1 Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'`

May be caused by https://github.com/visgl/loaders.gl/pull/1074

**Comment by ibgreen** [comment]
Looks like our IE11 fix broke the scripts. 

As a side note, we need some better test cases for scripts.
