### ISSUE TITLE
DRCLoader documentation says it supports parseSync, but receive error "Draco loader: 'parseSync' not supported by this loader, use 'parse' instead."

### ISSUE THREAD

**Issue by tonetechnician** [visgl/loaders.gl#1143]
Hi there loaders.gl team! 

This is somewhat a continuation of #1065 where I'm trying to make loaders.gl work on ie11 with Playcanvas. Tagging @ibgreen  and @dryabinin-actionengine.

I've been trying to avoid any es6 syntax whatsover (no promises) for Draco loading. To do this, I want to provide an ArrayBuffer to parseSync using the Draco Loader. 

The documentation says that the DracoLoader supports the [parseSync API](https://loaders.gl/modules/draco/docs/api-reference/draco-loader), however, when trying to use parseSync I get:

```
Error: Draco loader: 'parseSync' not supported by this loader, use 'parse' instead.
```

Is this meant to be the case? Seems the documentation is out of sync with the code. I'm using loaders.gl core + Draco version 2.3.9 from the unpkg CDN.

**Comment by ibgreen** [comment]
Hi, yes this has changed, the DracoLoader parsing is synchronous, but because of its size we now load the underlying webassembly draco library asynchronously from CDN before parsing.

@dryabinin-actionengine can you update the docs?

> I've been trying to avoid any es6 syntax whatsover 

You could just use a then statement on the returned promise with out using any ES6 syntax.
```
load(...).then(function (mesh) {
});
```

**Comment by tonetechnician** [comment]
Thanks @ibgreen. I could be wrong but from what I understand isn't the Promise returned from loaders.gl an es6 feature itself? The Promise returned from loaders.gl seems to be undefined in IE11:

```
load(...).then(function (mesh) {
});
```

When running in IE11, it returns `'Promise' is undefined`

**Comment by ibgreen** [comment]
Yes - it is expected that you will need to import some polyfills to run loaders.gl under IE11: https://loaders.gl/docs#supported-platforms
