### ISSUE TITLE
Sample / resources for vanilla WebGL + Loaders

### ISSUE THREAD

**Issue by timautin** [visgl/loaders.gl#1172]
Hello,

I'm writing a vanilla WebGL 3D scene and I'd like to use Loaders.gl to load GLB / GLTF/ 3DTile models on it.

I'm looking for a sample or some documentation showing how to load the result of a loader to my scene (like the basis sample https://github.com/visgl/loaders.gl/blob/master/examples/basis/app.js)? I see how to use the result of the OBJ loader since it has the classic normals / positions / textures data, but the GLB loader's result is completely different.

Thanks for this amazing project =)

**Comment by ibgreen** [comment]
@timautin Thanks for considering loaders.gl

GLTF is a complicated format that loads a hierarchical scenegraph with advanced PBR materials. Unless you have a special case where you control the GLTF file (so that it e.g. just has one top-level node) you are going to have to do a lot of work to process it in raw WebGL. 

If you are writing an app I would not recommend using raw WebGL directly. If you are writing your own WebGL framework, then using the loaders.gl GLTFLoader should save you a lot of work, and it would be great to see our loaders being reused that way.

With those comments out of the way, I would recommend you look into the luma.gl code that implements support for loaders.gl on how this can be done. It does not make much sense for us to reimplement all of that in a raw WebGL example.

Hope that works as a first answer and helps set expectations.

**Comment by timautin** [comment]
Thanks @ibgreen for you very fast answer!

I indeed control the GLTF file: it will always be a 3D textured mesh, generated from an OBJ file (I could use the OBJ format but it's much slower. The files typically weight several GB). The OBJ -> GLTF -> WebGL visualization pipeline is controlled as well.  No animation, no complex graph. Supporting every feature of GLTF would be great but is clearly not required. I initially thought that the result of a loader could be directly uploaded to WebGL (like the OBJ loader permits), but it looks like I'll have more work.

The app is a Cesium-like 3D globe (written as a library to be used in several projects), not a Three/Luma-like framework. I decided to go for raw WebGL because I'll very likely have to write it in C++ OpenGL as well (without GLTF support at least at the beginning), so the less libraries, the easier to rewrite. Three or Luma may be low-level enough though.

I quickly looked at Luma's source GLTF module (https://github.com/visgl/luma.gl/tree/master/modules/experimental/src/gltf) and GLTF sample (https://github.com/visgl/luma.gl/tree/master/examples/showcase/gltf), there's indeed quite some code but that seems doable. I'll try the Luma GLTF sample and see if I can build on it.

Thanks again!

**Comment by ibgreen** [comment]
Sounds good. Would love to see the results. Just for your awareness, deck.gl (which is built on luma.gl and loaders.gl) does support globe view: https://deck.gl/examples/globe-view

Deck.gl does have C++ port (deck.gl-native) but it only supports a few layers and not GlobeView at this stage.

**Comment by timautin** [comment]
`Would love to see the results `
Well the project is at an early stage, but here are a few screenshots:
<img width="918" alt="Capture d’écran 2021-02-12 à 13 42 12" src="https://user-images.githubusercontent.com/3846288/107769642-95938000-6d38-11eb-9e4f-5960abf72450.png">
<img width="999" alt="Capture d’écran 2021-02-12 à 13 42 57" src="https://user-images.githubusercontent.com/3846288/107769647-988e7080-6d38-11eb-9f2a-7d582fab082f.png">

There's still a lot of work in the camera handling, but it's going well 🙂 . I have no idea if it will be publicly available one day, as it will mainly be used in a software used to follow a submarine dive during scientific oceanographic cruises.

Here's the kind of 3D models we want to display on it (the article is in french but you can scroll a bit to see a video): https://wwz.ifremer.fr/mediterranee_eng/l-actu-Ifremer-Mediterranee/Une-Tour-Eiffel-a-1700-metres-de-profondeur-en-3D . That structure is ~15 meters high.

`Just for your awareness, deck.gl (which is built on luma.gl and loaders.gl) does support globe view `
I saw, but we have very specific requirements:
- levels of details
- negative altitudes (underwater) support
- multiple terrain sources, with the possibility to enable / disable some of them on the fly, and manage their z-order and the "fusion" between them to avoid having a big step when going from eg GEBCO (15 arc-sec worldwide DEM) to a very detailed 1m dataset (I think I'll have some hard time here 😅)
- easy port to C++

That list made us dismiss Cesium and I think Deck doesn't check all the boxes as well, does it?

**Comment by ibgreen** [comment]
> I saw, but we have very specific requirements:

OK, I'll bite :)

> * levels of details

This can probably be supported, not quite clear what you need, deck has extensive support for various tiled layers.

> * negative altitudes (underwater) support

If you work without a 2D basemap, using e.g. the deck.gl `TerrainLayer`, negative altitudes should work (possibly modulo some trivial bugs). You would likely need to extend the far plane of your 'View' camera to avoid clipping at z=0 but that is a one line thing.

> * multiple terrain sources, with the possibility to enable / disable some of them on the fly, and manage their z-order and the "fusion" between them to avoid having a big step when going from eg GEBCO (15 arc-sec worldwide DEM) to a very detailed 1m dataset (I think I'll have some hard time here 😅)

loaders.gl already supports a couple of different elevation formats which are used by the deck.gl `TerrainLayer`. There is active development in this area, your extensions sound like something deck.gl would be interested in, and you'd be improving this together with several strong geospatial engineers in the deck.gl community.

> * GLTF / 3D tiles support

Yes and Yes.

> * dense realtime-created point cloud support

- loaders.gl and deck.gl support both 3D Tiles and I3S.
- support for wide range of point cloud formats, including LAS, Draco etc. Decoding is done on worker pools, I think the `DracoWorkerLoader` using the latest Draco libraries can currently achieve a decoding throughput around 4M points/second.

> (fed by a stereoscopic camera)

- there is experimental support for stereoscopic camera in luma.gl. Since you are likely only using terrain layer, but not using a flat basemap (such as mapbox) this becomes easier to get working deck.gl.

> * easy port to C++

Well, at least we have strong foundations in `deck.gl-native`, the core architecture is in place and much of the hard work has been done. It is a matter of porting more layers, loaders etc. 

I do hesitate to mention this in an open source repo, but apart from the (free) support you'd get from the deck.gl community, it is possible to get help with improving deck.gl, C++ porting etc, there are relatively cost-effective engineering resources available to help with such porting work.

> * no subscription plan

deck.gl is 
- MIT-licensed free open source
- under open governance as part of the Linux Foundation / UCF. 
- You are welcome to join the open planning meetings, and major contributors can even become part of the TSC - technical steering committee

> That list made us dismiss Cesium. Deck also checks many boxes but not all, does it?

I am of course biased, but I think this would be a great project for deck.gl, I think deck has a lot to offer you, given that how much of what you are planning to do is already fully or partially implemented. 

That said, we are big fans of Cesium too :)

**Comment by timautin** [comment]
```
OK, I'll bite :) 
```
Ouch, didn't see it coming 😅 ! Thank you for all this information, which raise a few more questions 😃

```
- levels of details

This can probably be supported, not quite clear what you need, deck has extensive support for various tiled layers.
```

```
- multiple terrain sources, with the possibility to enable / disable some of them on the fly, and manage their z-order and the "fusion" between them to avoid having a big step when going from eg GEBCO (15 arc-sec worldwide DEM) to a very detailed 1m dataset (I think I'll have some hard time here 😅)

loaders.gl already supports a couple of different elevation formats which are used by the deck.gl TerrainLayer. There is active development in this area, your extensions sound like something deck.gl would be interested in, and you'd be improving this together with several strong geospatial engineers in the deck.gl community.
```

By levels of details I meant 2D tiles + zoom levels: when showing the whole earth I load zoom level 0, when zooming at some point I load zoom 1, then 2, etc.
Our source datasets are DEM geotifs (so only one Z per XY, no "real" 3D). I processed them using python / GDAL to get RGB PNGs tiles like [Mapbox did](https://blog.mapbox.com/global-elevation-data-6689f1d0ba65).
Currently my datasets are merged server-side and so I have only one tiles endpoint. But in the end the server would provide one endpoint (URL) per RGB-encoded DEM, and the client will do the merging on the fly. That will allow to adjust merging parameters and toggle elevation sources on the fly.

```
- negative altitudes (underwater) support

If you work without a 2D basemap, using e.g. the deck.gl TerrainLayer, negative altitudes should work (possibly modulo some trivial bugs). You would likely need to extend the far plane of your 'View' camera to avoid clipping at z=0 but that is a one line thing.
```

If by "2D basemap" you mean a flat map like Mapbox, then indeed that's not what I do. But since that's exactly what I'm doing these days, I don't think that the near / far clipping management is a 1 line thing though: it's indeed trivial if you don't support tilting / rotating the camera, but guess what ^^ ... Currently I didn't find near / far values that enables to see from the whole earth to a ~15m structure without having buffer problems, so I'll need to update the values according to the distance between the camera and the mesh.

```
- dense realtime-created point cloud support

loaders.gl and deck.gl support both 3D Tiles and I3S.
support for wide range of point cloud formats, including LAS, Draco etc. Decoding is done on worker pools, I think the DracoWorkerLoader using the latest Draco libraries can currently achieve a decoding throughput around 4M points/second.
```

4M points/second is great! Our camera is ~ 5 mpx I think, so we'd only need a small compression if any. But at this rate it quickly fills the GPU memory, doesn't it? The complexity here I think is not the displaying, but to (fastly) detect similar points between consecutive frames, to add only new points (and so to do nearly nothing when the camera doesn't move). Another not so easy task, but luckily the job of a colleague 😃

```
- (fed by a stereoscopic camera)

there is experimental support for stereoscopic camera in luma.gl. Since you are likely only using terrain layer, but not using a flat basemap (such as mapbox) this becomes easier to get working deck.gl.
```

I didn't see that, very interesting! Does it support similar points detection in consecutive frames as described above?

```
- easy port to C++

Well, at least we have strong foundations in deck.gl-native, the core architecture is in place and much of the hard work has been done. It is a matter of porting more layers, loaders etc.

I do hesitate to mention this in an open source repo, but apart from the (free) support you'd get from the deck.gl community, it is possible to get help with improving deck.gl, C++ porting etc, there are relatively cost-effective engineering resources available to help with such porting work.
```

```
I am of course biased, but I think this would be a great project for deck.gl, I think deck has a lot to offer you, given that how much of what you are planning to do is already fully or partially implemented.
```

Well I think that going with Deck and participating in the project to add the few unsupported features vs going vanilla is a matter of being slow to start (the time to learn Deck's code + add the missing features) but then get a lot of "free" features vs starting quickly and get a hard time every now and then (supporting 3D tiles for instance). I spent ~3 weeks for now, 1-2 more and I should be able to zoom / unzoom up to the desired resolution I think / hope.

Since I want to quickly get a working prototype going with raw WebGL makes sense I think, but I'll definitely give Deck/Luma a try. I may be wrong but I think that getting involved in Deck (js & native) would take much more than a few weeks, and I don't think I can spend that much: it's not my main project, not even the second one.

Anyway thanks again for the discussion, that's very interesting 🙂 ! Yesterday I used webpack to package Loaders core + GLTF as an external library ready to use in a raw JS project by just including the file, that could be nice to add it to the getting started repo if you are interested.

**Comment by ibgreen** [comment]
Understood. Obviously you can still use our point cloud loaders etc even if you are not using deck.

Let me respond to your final comments.

> so I'll need to update the values according to the distance between the camera and the mesh.

deck provide the ability to adjust the far plane on your Views every frame so you could iterate on this in the app. Once your far planing tuning algorithm was working well, it could have been considered for merge back into the library if generic enough.

> The complexity here I think is not the displaying, but to (fastly) detect similar points between consecutive frames, to add only new points

We don't have any support for the incremental detection part, but support for consuming incremental buffer chunks with additional points (and maybe dropping old chunks) could be added with modest effort.

> Yesterday I used webpack to package Loaders core + GLTF as an external library ready to use in a raw JS project by just including the file

Maybe try:
```js
<script src="https://unpkg.com/@loaders.gl/core@2.3.11/dist/dist.js"></script>
<script src="https://unpkg.com/@loaders.gl/gltf@2.3.11/dist/dist.js"></script>
```

**Comment by timautin** [comment]
```
Obviously you can still use our point cloud loaders etc even if you are not using deck.
```
Yes that's what I'll try to do 🙂

```
deck provide the ability to adjust the far plane on your Views every frame so you could iterate on this in the app. Once your far planing tuning algorithm was working well, it could have been considered for merge back into the library if generic enough.
```
Noted.

```
We don't have any support for the incremental detection part, but support for consuming incremental buffer chunks with additional points (and maybe dropping old chunks) could be added with modest effort.
```
That's interesting as well!

```
Maybe try:
<script src="https://unpkg.com/@loaders.gl/core@2.3.11/dist/dist.js"></script>
<script src="https://unpkg.com/@loaders.gl/gltf@2.3.11/dist/dist.js"></script>
```

I tried something similar and got an error. These print another error but work, thanks! It may be nice to include either solution as a quick start sample 😉 . I simply did this:

package.json
```
{
  "license": "MIT",
  "description": "Minimal example of using loaders.gl with webpack.",
  "scripts": {
    "start": "webpack-dev-server --progress --hot --open -d"
  },
  "dependencies": {
    "@loaders.gl/core": "2.2.0",
    "@loaders.gl/obj": "2.2.0",
    "@loaders.gl/gltf": "2.2.0"
  },
  "devDependencies": {
    "html-webpack-plugin": "^3.2.0",
    "webpack": "^4.42.0",
    "webpack-cli": "^3.3.11",
    "webpack-dev-server": "^3.1.1"
  }
}
```

webpack.config.js
```
const {resolve} = require('path');

module.exports = {
  entry: './app.js',
  output: {
    path: __dirname + '/lib',
    filename: 'loaders.gl.js',
    libraryTarget: 'var',
    library: 'Loaders'
  }
};
```

app.js
```
export { parse } from '@loaders.gl/core';
export { load } from '@loaders.gl/core';
export { OBJLoader } from '@loaders.gl/obj';
export { GLTFLoader, GLBLoader } from '@loaders.gl/gltf';
```

And then:
```
npm install --save
npx webpack --config webpack.config.js
```

The lib is then created in a lib folder and can be used using a "Loaders" prefix (eg Loaders.load(...)).

**Comment by timautin** [comment]
I case someone gets lost here, here are some bits of code that can partially load a Gltf (only its meshes, which is enough for our needs) to raw WebGL buffers:

Parse the GLB with Loaders:

```
const glb = await Loaders.load(GLB_URL, Loaders.GLBLoader, { gltf: { postProcess: false } });

for (let mesh of glb.json.meshes) {
    for (let primitive of mesh.primitives) {
        primitives.push(await this.loadPrimitive(glb, primitive));
    }
}
```

Primitive loading function:

```
async loadPrimitive(glb, primitive) {

    const indices = GlbBuilder.getAccessorData(glb, primitive.indices);
    const vertices = GlbBuilder.getAccessorData(glb, primitive.attributes.POSITION, true);
    const normals = GlbBuilder.getAccessorData(glb, primitive.attributes.NORMAL);
    const textureCoordinates = GlbBuilder.getAccessorData(glb, primitive.attributes.TEXCOORD_0);

    const materialDef = glb.json.materials[primitive.material];
    const textureIndex = materialDef.pbrMetallicRoughness.baseColorTexture.index;
    const texture = await this.getTexture(glb, textureIndex);

    const verticesBuffer = this.gl.createBuffer();
    this.gl.bindBuffer(this.gl.ARRAY_BUFFER, verticesBuffer);
    this.gl.bufferData(this.gl.ARRAY_BUFFER, vertices, this.gl.STATIC_DRAW);

    const normalsBuffer = this.gl.createBuffer();
    this.gl.bindBuffer(this.gl.ARRAY_BUFFER, normalsBuffer);
    this.gl.bufferData(this.gl.ARRAY_BUFFER, normals, this.gl.STATIC_DRAW);

    const indicesBuffer = this.gl.createBuffer();
    this.gl.bindBuffer(this.gl.ELEMENT_ARRAY_BUFFER, indicesBuffer);
    this.gl.bufferData(this.gl.ELEMENT_ARRAY_BUFFER, indices, this.gl.STATIC_DRAW);

    const textureCoordinatesBuffer = this.gl.createBuffer();
    this.gl.bindBuffer(this.gl.ARRAY_BUFFER, textureCoordinatesBuffer);
    this.gl.bufferData(this.gl.ARRAY_BUFFER, textureCoordinates, this.gl.STATIC_DRAW);

    const buffers = {

        indices: {
            data: indicesBuffer,
            length: indices.length
        },

        vertices: {
            data: verticesBuffer,
            length: vertices.length,
            stride: glb.json.bufferViews[glb.json.accessors[primitive.attributes.POSITION].bufferView].byteStride
        },

        normals: {
            data: normalsBuffer,
            length: normals.length,
            stride: glb.json.bufferViews[glb.json.accessors[primitive.attributes.NORMAL].bufferView].byteStride
        },

        textureCoordinates: {
            data: textureCoordinatesBuffer,
            length: normals.length,
            stride: glb.json.bufferViews[glb.json.accessors[primitive.attributes.TEXCOORD_0].bufferView].byteStride
        }
    };

    return {
        buffers: buffers,
        texture: texture
    }
}
```

Some utils:

```
async getTexture(glb, textureIndex) {

    const textureDef = glb.json.textures[textureIndex];
    const imageDef = glb.json.images[textureDef.source];
    const bufferViewDef = glb.json.bufferViews[imageDef.bufferView];
    const binChunk = glb.binChunks[0]; // TODO handle external uri

    const data = new Uint8Array(binChunk.arrayBuffer, binChunk.byteOffset + bufferViewDef.byteOffset, bufferViewDef.byteLength);
    const bitmap = await createImageBitmap(new Blob([data], { type: imageDef.mimeType } ));

    return Utils.loadTextureFromImageBitmap(this.gl, bitmap.width, bitmap.height, bitmap);
}

static getAccessorData(glb, accessorIndex) {

    const binChunk = glb.binChunks[0];

    const accessorDef = glb.json.accessors[accessorIndex];
    const bufferViewDef = glb.json.bufferViews[accessorDef.bufferView];
    const componentType = accessorDef.componentType;
    const count = accessorDef.count;

    const byteOffset = binChunk.byteOffset + (accessorDef.byteOffset || 0) + bufferViewDef.byteOffset;

    let numberOfComponents = null;
    switch (accessorDef.type) {
        case "SCALAR": numberOfComponents = 1; break;
        case "VEC2": numberOfComponents = 2; break;
        case "VEC3": numberOfComponents = 3; break;
        case "VEC4": numberOfComponents = 4; break;
        case "MAT2": numberOfComponents = 4; break;
        case "MAT3": numberOfComponents = 9; break;
        case "MAT4": numberOfComponents = 16; break;
    }

    switch (componentType) {
        case 5120: { return new Int8Array(binChunk.arrayBuffer, byteOffset, count * numberOfComponents); }
        case 5121: { return new Uint8Array(binChunk.arrayBuffer, byteOffset, count * numberOfComponents); }
        case 5122: { return new Int16Array(binChunk.arrayBuffer, byteOffset, count * numberOfComponents); }
        case 5123: { return new Uint16Array(binChunk.arrayBuffer, byteOffset, count * numberOfComponents); }
        case 5125: { return new Uint32Array(binChunk.arrayBuffer, byteOffset, count * numberOfComponents); }
        case 5126: { return new Float32Array(binChunk.arrayBuffer, byteOffset, count * numberOfComponents); }
    }

    return null;
}
```

That's enough to load this 400mb photogrammetry in a few seconds on my little MacBook 🤗 (took several minutes to open the .obj equivalent with OpenSceneGraph 😲) :

<img width="793" alt="Capture d’écran 2021-02-24 à 10 40 51" src="https://user-images.githubusercontent.com/3846288/108981309-e71f0180-768c-11eb-86de-46d3ef9f860b.png">

**Comment by ibgreen** [comment]
@timautin This is amazing. Would you consider contributing this example?

You could add it to `examples/experimental/gltf-raw-webgl`.

**Comment by timautin** [comment]
Sure, will do tomorrow!

**Comment by timautin** [comment]
@ibgreen Wouldn't you prefer it in gilt-with-raw-webgl (like gilt-with-deck.gl)?

**Comment by timautin** [comment]
There you go: https://github.com/timautin/loaders.gl/tree/gltf-with-raw-webgl/examples/experimental/gltf-with-raw-webgl

**Comment by ibgreen** [comment]
Yes your name makes sense. 

Looks great! Would you like to put up a PR from your fork?

**Comment by timautin** [comment]
It's here: https://github.com/visgl/loaders.gl/pull/1225
