### ISSUE TITLE
Shapefile Loader - Invalid dataview Length

### ISSUE THREAD

**Issue by JG145** [visgl/loaders.gl#1173]
I am trying to load a shapefile file through a react start app but running into :
```
SHP file: bad magic number 1008813135 index.js:1
SHP file: bad version 1696742759 index.js:1
Uncaught (in promise) RangeError: invalid data view length
```

Running 

`const data = load(
  "./99bfd9e7-bb42-4728-87b5-07f8c8ac631c2020328-1-1vef4ev.lu5nk.shp",
  ShapefileLoader
);`

The shapefile was download from the ESRI website so should be correctly formatted. Any ideas?

**Comment by ibgreen** [comment]
The fact that the SHP file has a bad magic number is indicating that this is not a pure SHP file. We might need a small sample file to investigate.

**Comment by kylebarron** [comment]
I agree with Ib, it's not really possible to debug this without a minimal example with data.

**Comment by JG145** [comment]
I downloaded this file:
https://hub.arcgis.com/datasets/a21fdb46d23e4ef896f31475217cbb08_1?geometry=107.578%2C-89.888%2C-76.641%2C68.495

**Comment by ibgreen** [comment]
I tried loading this in https://studio.unfolded.ai which uses the `ShapefileLoader` and it looks pretty good.

<img width="1259" alt="Screen Shot 2021-02-13 at 9 46 46 AM" src="https://user-images.githubusercontent.com/7025232/107856943-6b959880-6de0-11eb-842b-7e930cbdb92c.png">

An observation is that loading from local file system paths is not directly possible in the browser. I wonder why `load` is not giving you errors for that path.

**Comment by JG145** [comment]
how would you recommend loading a local file then?

**Comment by ibgreen** [comment]
- only possible through `File` objects. You get this through file selection dialogs and drag and drop targets in your UI. You could poke around in the loaders.gl examples, they do provide drop targets.
- you could also set up a separate server on your machine. This won't work for users of your app though unless they run it as well.

Be aware that there is an additional complication specific to ShapefileLoader. Shapefiles are not a single file but a group of files. This is handled automatically for URLs but makes the Shapefile loader harder to use on local files. It requires using undocumented helper classes in loaders.gl.
