### ISSUE TITLE
examples:website:i3s: `yarn start` doesn't work on master

### ISSUE THREAD

**Issue by belom88** [visgl/loaders.gl#1189]
Steps to reproduce:
1. git checkout master
2. git clean -dfx
3. yarn bootstrap
4. cd examples/website/i3s
5. yarn
6. yarn start
7. The site is shown in browser `http://localhost:8080/`
8. Layer doesn't appear on a map;
9. There are errors in console `A 3D tile failed to load: https://tiles.arcgis.com/tiles/z2tnIkrLQ2BRzr6P/arcgis/rest/services/SanFrancisco_Bldgs/SceneServer/layers/0/nodes/39-0 Unexpected token � in JSON at position 1`

`yarn start-local` works correctly.

**Comment by ibgreen** [comment]
I think this may be a case of loader selection failing - sounds like the 3D Tiles loader is picked.

Let's investigate mime types etc we get from ArcGIS so that we can fine tune the `selectLoader` results.

As a temporary workaround, it could probably be handled in the application by
```
        new =Tile3DLayer({
          // TODO - deck.gl 8.4 supports `loaders` prop
          loader: tileUrl.includes('arcgis') ? I3SLoader : CesiumIonLoader,
          ...
        })
```
