### ISSUE TITLE
Bump deck.gl master to loaders.gl 3.0.0-alpha

### ISSUE THREAD

**Issue by ibgreen** [visgl/loaders.gl#1194]
deck.gl has released 8.4 and `master` branch is now open for v8.5 development.

- The plan is that deck.gl 8.5 will use loaders.gl 3.0 instead of 2.3
- To ensure we catch regressions that affect deck.gl as early as possible, we should bump dependencies on deck.gl master to `loaders.gl@3.0.0-alpha` soon.
- Let's take some time and figure out what changes we want to get tested and then publish a new loaders.gl alpha with those changes, and then we bump deck.

**Comment by ibgreen** [comment]
@Pessimistress @alasarr FYI

**Comment by dryabinin-actionengine** [comment]
https://github.com/visgl/deck.gl/pull/5531 It Was merged.
