### ISSUE TITLE
Specify default loader / handle servers that do not send useful MIME types / extensions

### ISSUE THREAD

**Issue by ibgreen** [visgl/loaders.gl#1198]
### Background: 

deck.gl added support for automatic loader selection. However some servers do not add extensions and signficant MIMEtypes / content-type headers to their response, causing loader selection to fail.

It is possible to hook into the selection process with explicit `fetchFile` and `selectLoader` calls but this pushes to much logic into deck / the application layer.

### Ideas:

- Allow specification of a default loader
- Allow user to specify a server/url map that overrides mime types or specifies loaders.

### Default Loader

Could be specified by id or loader object

```typescript
  load(url, loaders, {fallbackLoader: MVTLoader});
  load(url, loaders, {fallbackLoaderId: 'mvt'});
```
The first option adds more data to the options object but should be more natural to use in cases when the loader import is available. The second option might be useful when the loader import is in another file.

### server url map

Some partial URLs and wildcarding 

```typescript
  load(url, loaders, {servers: {
     '...gis.com/vector-tiles/...', {headers: 'content-type': 'application/vnd.mapbox-vector-tile'}
     '...gis.com/.....', MVTTileLoader}
   }
```

@Pessimistress 
@kylebarron

**Comment by Pessimistress** [comment]
I think we want to avoid non-serializable content in the `options` object as much as possible. Options are passed into/between workers and option 1 may have unexpected consequences.

**Comment by ibgreen** [comment]
Addressed with `options.mimeType` in 3.0
