### ISSUE TITLE
Address bundle size growth

### ISSUE THREAD

**Issue by ibgreen** [visgl/loaders.gl#1226]
The module sizes are growing at an alarming rate, we need make a pass and understand what is driving it and what we can do about it.

- @dryabinin-actionengine @belom88 perhaps you can look at the tile modules?
- I will look at the core libraries.

## module sizes in 2.3
modules/3d-tiles/dist/dist.min.js 170K
modules/arrow/dist/dist.min.js 253K
modules/basis/dist/dist.min.js 24K
modules/compression/dist/dist.min.js 2.9M
modules/core/dist/dist.min.js 78K
modules/crypto/dist/dist.min.js 33K
modules/csv/dist/dist.min.js 33K
modules/draco/dist/dist.min.js 33K
modules/flatgeobuf/dist/dist.min.js 45K
modules/gltf/dist/dist.min.js 73K
modules/i3s/dist/dist.min.js 145K
modules/images/dist/dist.min.js 27K
modules/json/dist/dist.min.js 47K
modules/kml/dist/dist.min.js 33K
modules/las/dist/dist.min.js 241K
modules/mvt/dist/dist.min.js 37K
modules/obj/dist/dist.min.js 30K
modules/pcd/dist/dist.min.js 23K
modules/ply/dist/dist.min.js 21K
modules/polyfills/dist/dist.min.js 549K
modules/potree/dist/dist.min.js 12K
modules/shapefile/dist/dist.min.js 125K
modules/tables/dist/dist.min.js 35K
modules/terrain/dist/dist.min.js 22K
modules/tiles/dist/dist.min.js 158K
modules/video/dist/dist.min.js 37K
modules/wkt/dist/dist.min.js 18K
modules/zip/dist/dist.min.js 112K

## module sizes in 3.0 alpha
modules/3d-tiles/dist/dist.min.js 408K
modules/arrow/dist/dist.min.js 286K
modules/compression/dist/dist.min.js 120K
modules/core/dist/dist.min.js 120K
modules/crypto/dist/dist.min.js 59K
modules/csv/dist/dist.min.js 58K
modules/draco/dist/dist.min.js 86K
modules/excel/dist/dist.min.js 901K
modules/flatgeobuf/dist/dist.min.js 45K
modules/gltf/dist/dist.min.js 154K
modules/i3s/dist/dist.min.js 379K
modules/images/dist/dist.min.js 85K
modules/json/dist/dist.min.js 137K
modules/kml/dist/dist.min.js 35K
modules/las/dist/dist.min.js 296K
modules/mvt/dist/dist.min.js 40K
modules/obj/dist/dist.min.js 111K
modules/pcd/dist/dist.min.js 103K
modules/ply/dist/dist.min.js 129K
modules/polyfills/dist/dist.min.js 575K
modules/potree/dist/dist.min.js 12K
modules/shapefile/dist/dist.min.js 159K
modules/tables/dist/dist.min.js 41K
modules/terrain/dist/dist.min.js 79K
modules/textures/dist/dist.min.js 128K
modules/tiles/dist/dist.min.js 261K
modules/video/dist/dist.min.js 37K
modules/wkt/dist/dist.min.js 18K
modules/zip/dist/dist.min.js 197K

**Comment by dryabinin-actionengine** [comment]
@ibgreen I checked this growing bundle size issue and find out that my previous changes in [PR](https://github.com/visgl/loaders.gl/pull/1144) are related to the bundle sizes growing. I revert `@babel/plugin-transform-modules-commonjs` plugin from bundle.js and all dist.min.js files becomes smaller.
I think we need spend more time on that and find better way to solve the following issues: [first](https://github.com/visgl/loaders.gl/issues/1065) and [second](https://github.com/visgl/loaders.gl/issues/1132)

**Comment by ibgreen** [comment]
For the first  IE11 issue we could potentially build a separate dist.es5.min.js script that is bigger, without regressing the main script.

For the second one I would need to take another look at the issue.

**Comment by ibgreen** [comment]
Great work, thanks.
