### ISSUE TITLE
Add parseInBatches support to ShapefileLoader

### ISSUE THREAD

**Issue by nreese** [visgl/loaders.gl#1267]
Are there plans to add parseInBatches support to ShapefileLoader? The documentation does not list parseInBatches yet ShapefileLoader does set parseInBatches.

My use case is that I have a web application that reads files and writes them to a data store. Streaming the file is important so that the entire file is never in memory at a single time on the client.

**Comment by nreese** [comment]
Looking into the code, [ShapefileLoader](https://github.com/visgl/loaders.gl/blob/master/modules/shapefile/src/shapefile-loader.js#L30) exposes  parseInBatches. Using parseInBatches throws the exception "RangeError: invalid array length". The error this thrown in (parseShx)[https://github.com/visgl/loaders.gl/blob/master/modules/shapefile/src/lib/parsers/parse-shx.js#L12]. Looking into some of the the other files in the parsers folder, the files expose both a parseInBatches and a parse method. Should parse-shx expose a parseInBatches method? Is ShapefileLoader.parseInBatches stable?

**Comment by ibgreen** [comment]
@nreese Great to hear that you are using the Shapefile loader.

I believe `parseInBatches` should be working (I think there are test cases for it - if you find it you can replace `test(` with `test.only(` and run `yarn test node` to confirm).

I believe we only stream the DBF and SHP files. The SHX file only contains indices and is usually quite small relatively speaking (e.g. a few MB compared to 100MB) so the value of streaming that is limited. I am not sure we fully use the SHX file yet as we have not encountered shapefiles that cannot be read without it, but I believe we do read the file if it is supplied.

Let me know if that helps.

**Comment by nreese** [comment]
@ibgreen thanks for the response. I can run the tests locally. However, I can not run ShapefileLoader in the browser. When running ShapefileLoader in the browser, the url is set to an http address instead of the file. Can ShapefileLoader be run in the browser?

When running the test, [shxResponse.url](https://github.com/visgl/loaders.gl/blob/master/modules/shapefile/src/lib/parsers/parse-shapefile.js#L166) resolves to the expected file path "/Users/.../loaders.gl/modules/shapefile/test/data/shapefile-js/boolean-property.shx".

When running in the browser, [shxResponse.url](https://github.com/visgl/loaders.gl/blob/master/modules/shapefile/src/lib/parsers/parse-shapefile.js#L166) resolves to "http://localhost:5601/zjw/app/maps/boolean-property.shx". Why is shxResponse.url different when using ShapefileLoader in the browser?

For context, I can successfully get JSONLoader working in the browser. I am just trying to swap out JSONLoader with ShapefileLoader but running into these troubles.

**Comment by ibgreen** [comment]
Keep in mind that Shapefile is a multi-file loader. It tries to load multiple files. You can't load directly from files in the browser but if you are providing a URL to the `.shp` file it will look for other files (.dbf, .shx, .prj, .cpg) by substituting the file name in the provided URL. 

I think the loader should not fail if the .shx file is not present. I assume you are trying to load the `.shp`, not the `.shx`?

**Comment by nreese** [comment]
> Keep in mind that Shapefile is a multi-file loader. It tries to load multiple files. You can't load directly from files in the browser

Our use case is loading files in the browser. Would it be possible to create new File objects for each extension and load the File objects that way?

> I think the loader should not fail if the .shx file is not present. I assume you are trying to load the .shp, not the .shx?

I am loading .shp, the directory contains .shp, .shx. and so one. For example, I am trying to load the file from loaders.gl/modules/shapefile/test/data/shapefile-js/boolean-property.shp

**Comment by ibgreen** [comment]
> Would it be possible to create new File objects for each extension and load the File objects that way?

Yes, the way we do it is we provide a custom `options.fetch` function that reads from a map of File objects.

**Comment by nreese** [comment]
> Yes, the way we do it is we provide a custom options.fetch function that reads from a map of File objects.

But those File objects read from a URL. Would it be possible to have a user select the .shp file and the browser read .shp, .shx, and and other files? Or does the browser not allow javascript to read files other then the one the user selected for security concerns?

**Comment by ibgreen** [comment]
The user needs to select all the files in the FilePicker, you would get a `FileList` back (effectively `File[]`) and you'd use these files in the custom `fetch`.

The only way to get File objects in the browser is through a file selection dialog, drag and drop, or manually instantiating them on data (e.g. ArrayBuffers). You can load a URL using fetch and create a File object on the loaded content but that doesn't buy you much. 

And you cannot get a URL from a browser created file object as the browser truncates the file name for security reasons, and you couldn't load it anyway since the browser doesn't allow you fetch from local files.

**Comment by nreese** [comment]
> And you cannot get a URL from a browser created file object as the browser truncates the file name for security reasons

Thanks. That is the disconnect I was missing. That makes a lot of sense. Guess you don't want a rogue javascript process reading a bunch of files from the file system. 

> The user needs to select all the files in the FilePicker, you would get a FileList back (effectively File[]) and you'd use these files in the custom fetch.

That is one idea. Another would be to have a ZippedShapefileLoader that would take a zip file. I will do a little experimenting and see what works. I will share back here when I have something worked out.

Thank you for the help. I am going to close the issue since ShapefileLoader does indeed support parseInBatches. I looked through the shapefile parsing code and its really well laid out and easy to follow. Thanks for the great project.

**Comment by ibgreen** [comment]
Yes - You should be able to use the ZipLoader in loaders.gl and create a `fetch` wrapper around that.
