### ISSUE TITLE
classifyRings implementation is broken

### ISSUE THREAD

**Issue by felixpalmer** [visgl/loaders.gl#1274]
The `classifyRings` function doesn't actually classify the rings passed to it because of a bug in the [signedArea](https://github.com/visgl/loaders.gl/blob/494eb1689e5e41b73dec15c1a20a469d4e46f46f/modules/mvt/src/lib/mapbox-vector-tile/vector-tile-feature.js#L219) function.

The `signedArea` function assumes that the points are passed in a `{x: 1, y:1}` format, as can be seen in the following line:

```javascript
sum += (p2.x - p1.x) * (p1.y + p2.y);
```

but the points are in fact arrays and thus should be accessed like `p2[0]` etc. This can be seen [here](https://github.com/visgl/loaders.gl/blob/494eb1689e5e41b73dec15c1a20a469d4e46f46f/modules/mvt/src/lib/mapbox-vector-tile/vector-tile-feature.js#L57)

The result is `signedArea` always returns `NaN`, which in turn means that the classification in `classifyRings` doesn't work. If you follow through the logic it can be shown that `classifyRings` just does `rings.map( r => [r] )`, in other words it treats each passed ring as an exterior polygon and none as holes.

The fix is simple, as noted above, however as noted in https://github.com/visgl/loaders.gl/issues/1128 the binary output format that accepts the parsed output from the above code doesn't seem to have any concept of holes in the rendering path, thus it is necessary to fix that also before this issue can be resolved.

**Comment by kylebarron** [comment]
Note that the code in question was copied from Mapbox's `vector-tile-js`: https://github.com/mapbox/vector-tile-js/blob/58df1e9344ee64f26deee84a9f54cee11fb95ef6/lib/vectortilefeature.js#L197-L233

I believe `vector-tile-js` always uses objects internally rather than arrays. I haven't dug into our vector tile loader recently; I think @alasarr has been working with it and might have a comment.

**Comment by felixpalmer** [comment]
Yes, I noticed that it was taken from there, and that is the source of the problem. The Mapbox implementation uses a `Point` class, whereas ours does not: https://github.com/mapbox/vector-tile-js/blob/58df1e9344ee64f26deee84a9f54cee11fb95ef6/lib/vectortilefeature.js#L71

Perhaps in an older version Mapbox also used arrays

**Comment by alasarr** [comment]
Good catch! I agree we need to fix it before addressing #1128 (we need that to fix holes in MVTLayer with binary enabled)

**Comment by felixpalmer** [comment]
I fixed this as part of implementing triangulation in the MVTLoader (https://github.com/visgl/loaders.gl/pull/1356), both for the binary and legacy codepaths
