### ISSUE TITLE
JSONLoader test fails

### ISSUE THREAD

**Issue by belom88** [visgl/loaders.gl#1304]
It is reproduced only on nodejs v10.
https://github.com/visgl/loaders.gl/pull/1298/checks?check_run_id=2287634440

Failing test:
https://github.com/visgl/loaders.gl/blob/f7c91a39aa8b47b4a19676236b1d6155dd77b612/modules/json/test/json-loader.spec.js#L176

Message: 
```
not ok 3212 should be equal
  ---
    operator: equal
    expected: 10
    actual:   5
```

I found out that it works if I comment another test https://github.com/visgl/loaders.gl/blob/f7c91a39aa8b47b4a19676236b1d6155dd77b612/modules/json/test/json-loader.spec.js#L37

I tried to debug and found that in nodejs v10 the chunk length is less then in other cases:
```
'{\n    "version": "v1",\n    "data": {\n        "id": "ea951213-dec7-4405-8f7e-2a6f8249954f",\n        "label": "sf_incidents.csv",\n        "color": [\n            0,\n            92,\n            255\n        ],\n        "allData": [\n            [\n                160919032,\n                "VANDALISM",\n                "MALICIOUS MISCHIEF, VANDALISM OF VEHICLES",\n                "Friday",\n                "11/11/16 7:00",'
```
vs
```
'{\n    "version": "v1",\n    "data": {\n        "id": "ea951213-dec7-4405-8f7e-2a6f8249954f",\n        "label": "sf_incidents.csv",\n        "color": [\n            0,\n            92,\n            255\n        ],\n        "allData": [\n            [\n                160919032,\n                "VANDALISM",\n                "MALICIOUS MISCHIEF, VANDALISM OF VEHICLES",\n                "Friday",\n                "11/11/16 7:00",\n                "MISSION",\n                "NONE",\n                "1400 Block of U…        [\n                166166053,\n                "LARCENY/THEFT",\n                "GRAND THEFT FROM LOCKED AUTO",\n                "Tuesday",\n                "7/26/16 19:30",\n                "NORTHERN",\n                "NONE",\n                "3600 Block of LYON ST",\n                -122.4482784,\n                37.80427189\n            ],\n            [\n                166170048,\n                "LARCENY/THEFT",\n                "PETTY THEFT OF PROPERTY",\n                "Saturday",\n'
```

Unfortunately, I could not find the root cause.

**Comment by ibgreen** [comment]
Yes I see the test is a bit fragile as it makes assumptions about the chunk length. 

The good news is then that it is not a hard error, just a test error.

Since Node 10 is just about at end of life, I recommend we just remove it from the test setup for now https://nodejs.org/en/about/releases/

**Comment by ibgreen** [comment]
@belom88 Can you make a one line PR? https://github.com/visgl/loaders.gl/blob/master/.github/workflows/test.yml#L15
