### ISSUE TITLE
How can I convert "3d tiles" with textures to "I3S" using the "tile-converter"?

### ISSUE THREAD

**Issue by kataya** [visgl/loaders.gl#1313]
I tried to convert "3d tiles" to "I3S" using "tile-converter", but the texture is missing.

The "3d tiles" I used can be obtained from this link.
https://gic-plateau.s3-ap-northeast-1.amazonaws.com/2020/Tokyo23ku3DTiles/13101_chiyoda-ku.zip

The command I tried is as follows.
>npx tile-converter --input-type 3DTILES --tileset ./13101_chiyoda-ku/tileset.json --name 13101_chiyoda-ku --output ./13101_chiyoda-ku_output --slpk

**Comment by belom88** [comment]
I'll check

**Comment by belom88** [comment]
It is done

**Comment by ibgreen** [comment]
@belom88 Maybe indicate which version of the tile-converter package this is published in?

**Comment by belom88** [comment]
Yes. Please use https://www.npmjs.com/package/@loaders.gl/tile-converter/v/3.0.0-alpha.11
