### ISSUE TITLE
Failed to fetch resource .pgm when debugging tile-converter

### ISSUE THREAD

**Issue by KeyboardSounds** [visgl/loaders.gl#1322]
When running: 
`node ./modules/tile-converter/dist/scripts/converter.js --input-type i3s --tileset mytileset.slpk --name foo --output bar`
I get:
`Uncaught Error: Failed to fetch resource <absolute path to fs root>/loaders.gl/deps/egm2008-5.pgm (400):`
Even though I've already run `--install-dependencies`, and `<absolute path to fs root>/deps/egm2008-5.pgm` exists.

**Comment by belom88** [comment]
Unfortunately, i3s loader can't load *.slpk files, only http[s] services can be used.
For running converter from root path of @loaders.gl:
```
#build the project
yarn bootstrap
# install pgm in `deps/egm2008-5.pgm`
npx tile-converter --install-dependencies
# run conversion
npx tile-converter  --input-type I3S --tileset https://tiles.arcgis.com/<path-to-tile>/SceneServer/layers/0 --name tileset_name --max-depth 2
```

You also can use npx without clonning the repo:
`npx -p @loaders.gl/tile-converter tile-converter`

**Comment by ibgreen** [comment]
It sounds like you didn't install the earth gravity model file?

```
npx tile-converter --install-dependencies
```
