### ISSUE TITLE
parse mvt data invalid tile options

### ISSUE THREAD

**Issue by laijackylai** [visgl/loaders.gl#1341]
The code snippet below shows my code querying a pbf file generated by tippecanoe containing some geojson features.

![code](https://user-images.githubusercontent.com/66239914/115815600-d2ab7b00-a429-11eb-96b3-0985c58ac6ba.png)

The buffer is the data from the queried file which I unzipped to be able to parse.
The question is that with the tileOptions passed in, it will spit out an error, saying:

![error](https://user-images.githubusercontent.com/66239914/115817098-bfe67580-a42c-11eb-9154-13741883cd5e.PNG)

 I don't know what is wrong here, please help thank you

**Comment by alasarr** [comment]
A tile MVT has the data in local tile coordinates.

When you set `coordinates:'wgs84'` parse function will try to return the geometries in WGS84, but to do the transformation you need to pass the tileIndex (Z,X,Y) of the tile you're about to parse. It looks tile what you're sending to parse is not correct.

If you don't need coordinates in WGS84, you can use this https://loaders.gl/modules/mvt/docs/api-reference/mvt-loader#geojson-with-local-coordinates.

Checking your code snippet, it looks that instead of :
```
{
    x: zoom,
    y: xtile,
    z: ytile
}
```
Should be something like:
```
{
    x: xtile,
    y: ytile,
    z: zoom
}
```

As a general rule, if you don't have a specific reason for WGS84, use local since it has a better performance

**Comment by laijackylai** [comment]
First of all, thanks for your reply.

I tried changing the tileIndex but the result is the same, same error.

As for the WGS84, because my application is based on deck.gl and I want to get back the original lon and lat of the geojson.

One fun fact is that the parse function works flawlessly when the tileOptions were not passed in, and I can get the corresponding local coordinates.

**Comment by alasarr** [comment]
Why don't you use deck.gl [MVTLayer](https://deck.gl/docs/api-reference/geo-layers/mvt-layer)?  This layer manages conversions to WGS84 on the fly? For example, hover and click events returns the data in lat/lng.

**Comment by alasarr** [comment]
Maybe I'm losing something, but I feel what you want is to render tiles generated by tippecanoe. For me, it would have more sense to serve the MVT and consume them using the MVTLayer

**Comment by laijackylai** [comment]
Yes, I generated the pbf files with different zoom level and tiles using tippecanoe and I am currently serving them to a mvt layer in deckgl which is working perfectly

But why I want to do this is because I want to implement a feature that allows the user to download the data they are viewing on the website. That's why I want to get back the geojson features from the pbf files that I generated

**Comment by laijackylai** [comment]
The load and parse functions works in the browser and I can get the data there, but I'd like to do the data translation on the server as my deckgl application is already quite large, implementing this on the browser might further reduce it's performance.

**Comment by laijackylai** [comment]
Thanks for the opinions.

I just checked deckgl docs, there seems to be a new callback function called [getRenderedFeatures](https://deck.gl/docs/whats-new#query-rendered-features) which can get the current rendered features on screen.

I think I'll use this function instead and download the data from the browser directly, which can also reduce the additional query to the database as well.

Thanks again guys

**Comment by laijackylai** [comment]
I'll close this issue now, thx again
