### ISSUE TITLE
`array` option for `options.csv.rowFormat`?

### ISSUE THREAD

**Issue by davidcalhoun** [visgl/loaders.gl#1358]
# Quick summary
Hi folks, thank you for this great library!  For CSV `rowFormat` there's an `object` option to force rows to be objects, and I'm curious if a case can be made for also having an `array` option to force rows to arrays?

# Longer context
I'm not sure of the logic of the `auto` behavior (maybe something to do with the total row size, some option in Papa Parse?), but some CSV inputs get parsed as arrays and some as objects, and I'd prefer if I could force it all to arrays.

## CSV data where rows end up being objects (when `rowFormat` is set to `auto`)
```csv
LATITUDE,LONGITUDE,emissions_1B2b_Natural_Gas_Production,emissions_1B2b_Natural_Gas_Processing,emissions_1B2b_Natural_Gas_Transmission,emissions_1B2b_Natural_Gas_Distribution,emissions_1B2a_Petroleum,Total_CH4_kg_h
20.0499992,-129.9499969,0,0,0,0,0,0
...(~245k total rows)
```

## CSV data where rows end up being arrays (when `rowFormat` is set to `auto`)
```csv
Longitude,Latitude,Amount_Flared_Bcf,Avg_Temp_K,Type,,
-103.813257,32.2222,1.888555528,1778,upstream,,
...(~1.7k total rows)
```

**Comment by ibgreen** [comment]
@davidcalhoun This is discussed in #1355, I am positive to dropping the `auto` option and make the choice between object and array explicit.

@manassra

**Comment by davidcalhoun** [comment]
Sounds great, thanks for the heads up!
