### ISSUE TITLE
KMLLoader option gis.format does not have a default value as specified in docs

### ISSUE THREAD

**Issue by harveylee** [visgl/loaders.gl#1381]
Using v3.0.0-alpha.14:
The docs state that gis.format as default `'geojson'` but if you leave the `options` parameter unspecified in:

```js
const data = await load(url, KMLLoader, options);
```

then `parseTextSync` throws an error [here](https://github.com/visgl/loaders.gl/blob/9f99ef7d045a97527915e8e2e880886b5d975a74/modules/kml/src/kml-loader.js#L51).

A workaround is to always specify the options object, e.g.
```js
const data = await load(url, KMLLoader, { gis: { format: 'geojson' } });
```

**Comment by kylebarron** [comment]
v3 has a new parser for KML, in that PR there was a discussion of what fallback to use (https://github.com/visgl/loaders.gl/pull/1019#discussion_r559731853). 

So either we don't provide a fallback or I believe here 
https://github.com/visgl/loaders.gl/blob/9f99ef7d045a97527915e8e2e880886b5d975a74/modules/kml/src/kml-loader.js#L30-L32
we'd need to add 
```js
gis: {format: 'geojson'}
```
