### ISSUE TITLE
Highlighting buildings in I3SLoader example

### ISSUE THREAD

**Issue by tkhrmeme** [visgl/loaders.gl#1401]
Hello, all.

My purpose is to pick individual objects in 3DTiles (.b3dm) to show property of each object as like Cesium. And I found I3S example.

When I run I3SLoader example (https://loaders.gl/examples/i3s), I can click each building to highlight it and show properties such as OBJECTID and NAME. But I can't click and highlight any buildings with i3s example (https://github.com/visgl/loaders.gl/tree/master/examples/website/i3s) when executing locally. 

Are they built from different source codes ?

Is there any method to execute picking individual object for 3DTiles or I3S ?

**Comment by belom88** [comment]
Hello, @tkhrmeme .
The feature is experimental now. You can run it in https://github.com/visgl/loaders.gl/tree/master/examples/experimental/i3s-17-and-debug : `yarn start-local`

**Comment by tkhrmeme** [comment]
Hi, @belom88 .
Thank you very much for you information. I will try it!!
