### ISSUE TITLE
tile-converter: better error messages for splk and expired token

### ISSUE THREAD

**Issue by giserkej** [visgl/loaders.gl#1412]
hi. I want to use your tile-converter tools to convert i3s service to 3D Tiles. Here is my CLI code:
npx tile-converter --input-type I3S --tileset http://kejin.geoscene.cn/server/rest/services/Hosted/GRID1/SceneServer/layers/0 --output D:\Esri\3dtiles --name D:\Esri\3dtiles\3dtiles.json
However, error occurs that unexpected token < in JSON at position 0. Here is my Screenshot:
![image](https://user-images.githubusercontent.com/37581179/120288315-a7526080-c2f2-11eb-99cb-d1597d242918.png)
Previously, I tried using "https" instead of "http"  to invoke my I3S service, but it bugged with message: "Failed to fetch resources". Therefore, I changed my service type to HTTP. I checked my service, it is Ok. So could you please give me a good solutions? Thank you in advance.

**Comment by dryabinin-actionengine** [comment]
Hey @baker5516 . Thanks for using our service. `I3S -> 3DTiles` conversion feature is experimental now and issues can occur.
It will be helpful if you provide your tileset for debugging and fixing process.

**Comment by baker5516** [comment]
ok, my slpk layer? How can I get it to you?

**Comment by dryabinin-actionengine** [comment]
> ok, my slpk layer? How can I get it to you?

`I3S->3DTiles `converter can't convert from slpk file. It can convert only if i3s tileset hosts on some service. You can share your service url.

**Comment by baker5516** [comment]
my service URL: https://tiles.arcgis.com/tiles/cNXlkTk36vCn8KGq/arcgis/rest/services/GRID1/SceneServer?token=q9eLILtOJ43dQy4pKc6rkCiZEkAF0jYDRGoGbQht67Fig76b0jRyzV3HZqPau2BiVfXrRE7s9znmqM9lbDL4ZvBUdHObhCrYH2TIC00GF7IhwTPy8y4MPCQlS8n1K8ZmN1h-QJO7iBQRJSQWGI9SRE5KpcVRHYnMPRzLMyI6unLPlPZueTaOfbVc9_W9_ngG3sfiRhfKL-y3GNqIKcX9KpAzh1yXiGk5iQuVaIATQ74TI0FFni_4Gb1U8JsXgqBPvThLCpD3Oto0qfXwMF7fWQ..

**Comment by dryabinin-actionengine** [comment]
> my service URL: https://tiles.arcgis.com/tiles/cNXlkTk36vCn8KGq/arcgis/rest/services/GRID1/SceneServer?token=q9eLILtOJ43dQy4pKc6rkCiZEkAF0jYDRGoGbQht67Fig76b0jRyzV3HZqPau2BiVfXrRE7s9znmqM9lbDL4ZvBUdHObhCrYH2TIC00GF7IhwTPy8y4MPCQlS8n1K8ZmN1h-QJO7iBQRJSQWGI9SRE5KpcVRHYnMPRzLMyI6unLPlPZueTaOfbVc9_W9_ngG3sfiRhfKL-y3GNqIKcX9KpAzh1yXiGk5iQuVaIATQ74TI0FFni_4Gb1U8JsXgqBPvThLCpD3Oto0qfXwMF7fWQ..

![image](https://user-images.githubusercontent.com/70207219/120318131-2726fd80-c2e8-11eb-8e53-5aa89a026cb8.png)

**Comment by ibgreen** [comment]
@dryabinin-actionengine 
- Would be great if we could find a way to show this error message from the `tile-converter` command.
- Also if we could detect that the user is trying to convert an slpk and issue a message saying this is not yet supported.

**Comment by dryabinin-actionengine** [comment]
> @dryabinin-actionengine
> 
> * Would be great if we could find a way to show this error message from the `tile-converter` command.
> * Also if we could detect that the user is trying to convert an slpk and issue a message saying this is not yet supported.

@morphoix Please take this two tasks.

**Comment by baker5516** [comment]
try this:
http://www.arcgisonline.cn/server/rest/services/Hosted/GRID1/SceneServer

**Comment by dryabinin-actionengine** [comment]
@baker5516 @ibgreen  I checked our  tile-converter and find out that we don't have token support in options yet. We need to implement it before adding checks for invalid token.

**Comment by dryabinin-actionengine** [comment]
> try this:
> http://www.arcgisonline.cn/server/rest/services/Hosted/GRID1/SceneServer

Ok. Thank you. Will take a look.

**Comment by dryabinin-actionengine** [comment]
> try this:
> http://www.arcgisonline.cn/server/rest/services/Hosted/GRID1/SceneServer

I successfully converted this tileset to 3DTiles.
Result in cesium Ion:
![image](https://user-images.githubusercontent.com/70207219/120620922-1bf9dc00-c466-11eb-937b-0c84f56f09c1.png)

Looks like it is only token issue now. And also we should implement load from `slpk` files in the future.

**Comment by baker5516** [comment]
Could you show me your CLI? Next, do I need token if I convert i3s to 3dtiles?

发自我的iPhone

**Comment by dryabinin-actionengine** [comment]
> Could you show me your CLI? Next, do I need token if I convert i3s to 3dtiles? 发自我的iPhone
> […](#)
> 在 2021年6月3日，17:22，Daniil Ryabinin ***@***.***> 写道： ﻿ try this: http://www.arcgisonline.cn/server/rest/services/Hosted/GRID1/SceneServer I successfully converted this tileset to 3DTiles. Result in cesium Ion: Looks like it is only token issue now. And also we should implement load from slpk files in the future. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

![image](https://user-images.githubusercontent.com/70207219/120630818-da6e2e80-c46f-11eb-8419-4d851ede592d.png)
I use `max-depth 3` just not to do conversion for all nodes. To convert full tileset just don't apply `max-depth` option.

I found your problem url should be http://www.arcgisonline.cn/server/rest/services/Hosted/GRID1/SceneServer/layers/0

So try the following commands:
`npx -p @loaders.gl/tile-converter tile-converter --install-dependencies`
`npx -p @loaders.gl/tile-converter tile-converter --input-type i3s --tileset http://www.arcgisonline.cn/server/rest/services/Hosted/GRID1/SceneServer/layers/0 --name Hosted --output data`

**Comment by baker5516** [comment]
Ok, thanks a lot.

发自我的iPhone

**Comment by baker5516** [comment]
Hi, I noticed that updated command adds parameters "-p" and "@loaders.gl/tile-converter". What does these parameters means?  Thank you in advance.

**Comment by dryabinin-actionengine** [comment]
> Hi, I noticed that updated command adds parameters "-p" and "@loaders.gl/tile-converter". What does these parameters means? Thank you in advance.

**Comment by baker5516** [comment]
I converted one slpk file of 70MB to 3DTiles of 140MB, I thought it was quite large. Do you have plan to optimze that? By the way, you mentioned that you would implement load from slpk directly, when?

**Comment by baker5516** [comment]
Also, I thought my problem was that my first service URL is LAN, but when using WAN service URL, it would be OK. Can I assume that this module do not support LAN service URL?

**Comment by ibgreen** [comment]
@baker5516  Not sure if this helps, but I am not sure I can see why the URL matters. But obviously we expect an I3S server to follow a certain protocol. The tileset is served incrementally via various subpaths. Perhaps the arcgis server is responding differently that your server?

**Comment by belom88** [comment]
@giserkej Can you provide you url format. There are possible some limitations in @loaders.gl/polifills

**Comment by belom88** [comment]
> @giserkej Can you provide you url format? There are possible some limitations in @loaders.gl/polifills

**Comment by giserkej** [comment]
Sure. My service URL is as follows: https://tiles.arcgis.com/tiles/cNXlkTk36vCn8KGq/arcgis/rest/services/GRID1/SceneServer

**Comment by belom88** [comment]
```npx -p @loaders.gl/tile-converter tile-converter --input-type i3s --tileset https://tiles.arcgis.com/tiles/cNXlkTk36vCn8KGq/arcgis/rest/services/GRID1/SceneServer/layers/0 --name grid1```
Does work for me.
I close this issue. If you have another issue, feel free to create a new ticket.

**Comment by ibgreen** [comment]
> * Would be great if we could find a way to show this error message from the `tile-converter` command.
> * Also if we could detect that the user is trying to convert an slpk and issue a message saying this is not yet supported.

Nit: While it is great that this is working... were the error messages ever improved per the discussion (& title of the issue)? Good error message are really valuable to new users and improve their experience of using the tool. 

Also such error messages are usually very small development effort to add, relatively speaking..

**Comment by belom88** [comment]
It is message in the loader. From the converter we don't see what is wrong, just `null` in the result of the `load` function.
