### ISSUE TITLE
Investigate slow build of i3s-content-worker

### ISSUE THREAD

**Issue by ibgreen** [visgl/loaders.gl#1455]
The i3s-content-worker takes almost 4 minutes to build. Something is going on.

This negatively affects development speed as it delays bootstrap and CI.

Not yet sure why? Perhaps because it includes something from CompressedTextures?

**Comment by belom88** [comment]
Rows | Module | Start Row | End Row
-- | -- | -- | --
563 | @babel/runtime | 89 | 652
627 | @luma.gl/constants | 654 | 1281
**3947** | **@math.gl/core** | **1283** | **5230**
570 | @math.gl/geospatial | 5232 | 5802
403 | @probe.gl/stats | 5804 | 6207
**5707** | **Gl-matrix** | **6209** | **11916**
16 | Ktx-parse | 11918 | 11934
195 | Process | 11936 | 12131
2589 | ../core | 12162 | 14751
1304 | ../draco | 14753 | 16057
1138 | ../images | 16059 | 17197
1569 | ../loader-utils | 17199 | 18768
1725 | ../textures | 18770 | 20495
1585 | ../worker-utils | 20497 | 22082
793 | ./src | 22084 | 22877

`i3s-content-worker.js` code takes 22877 lines. To compare:

- compressed-texture-worker.js - 4740 lines;
- draco-worker.js - 4623.

The largest modules: `@math.gl/core` and `gl-matrix`. But there are `loaders.gl` dependencies that also take a lot of space all together.

**Comment by belom88** [comment]
Can we close it due to migration to ESBUILD

**Comment by ibgreen** [comment]
If you look at the build you can see that it is still extremely slow relatively speaking but of course with esbuild making everything more than 10x faster it is not currently a major issue.
