### ISSUE TITLE
The conversion tool is not very stable

### ISSUE THREAD

**Issue by haitunxiaomo** [visgl/loaders.gl#1484]
hi , sir
The conversion tool is not very stable.
common-line:npx tile-converter --input-type I3S --tileset https://tiles.arcgis.com/tiles/u0sSNqDXr7puKJrF/arcgis/rest/services/Frankfurt2017_v17/SceneServer/layers/0  --name arcgisIntegratedMesh --max-depth 3
When I switch, three things happen.
1、Conversion success
2、Conversion failure
![image](https://user-images.githubusercontent.com/8519144/121650092-ceb3e500-cacb-11eb-9aee-095703b4e3c6.png)

3、Has been stuck or stoped.
![image](https://user-images.githubusercontent.com/8519144/121650262-f86d0c00-cacb-11eb-8271-6f450c71533e.png)

**Comment by dryabinin-actionengine** [comment]
Hello @haitunxiaomo ! Thanks for using tile-converter. At first sight on the screenshot with error it looks like a connection issue to ArcGis service. And description about not stable conversion one more detail to confirm my point. Anyway we will check it and let you know about results.

**Comment by dryabinin-actionengine** [comment]
So I tried to run converter multiple times with different` --max-deps` levels. All my tries are succeed!
Looks like it is argGis connection problem.

**Comment by belom88** [comment]
It happens sometimes for me. I noticed it related to internet provider, wifi-router and other such things

**Comment by ibgreen** [comment]
As mitigations we could 
- add cleaner error handling - it looks like we just continue and it crashes in some later code, which makes the tool look broken.
- Retry requests (exponential backoff) - this was supposed to be added to the RequestScheduler but not sure about latest status.

I'd start with an error handling improvement if not hard.

**Comment by haitunxiaomo** [comment]
> So I tried to run converter multiple times with different` --max-deps` levels. All my tries are succeed!
> Looks like it is argGis connection problem.

I published the i3S service data myself, and the conversion is quite smooth.But problems arise when using ArcGIS data.

**Comment by haitunxiaomo** [comment]
> So I tried to run converter multiple times with different` --max-deps` levels. All my tries are succeed!
> Looks like it is argGis connection problem.

I also think it's the Internet

**Comment by dryabinin-actionengine** [comment]
@haitunxiaomo In that case I think we should close the issue.

**Comment by haitunxiaomo** [comment]
> @haitunxiaomo In that case I think we should close the issue.

Local services are sometimes error-prone, but relatively stable

**Comment by dryabinin-actionengine** [comment]
You are welcome to use it and if any errors please open another issues. I'll close this one.

**Comment by haitunxiaomo** [comment]
> You are welcome to use it and if any errors please open another issues. I'll close this one.

ok, thanks!
