### ISSUE TITLE
Issue with i3s 3D tiles conversion

### ISSUE THREAD

**Issue by RushiMUFC** [visgl/loaders.gl#1487]
Hi, I am facing some issue when converting i3s to 3D tiles. 

For example, I use https://tiles.arcgis.com/tiles/P3ePLMYs2RVChkJx/arcgis/rest/services/DevA_BuildingShells/SceneServer/layers/0

npx tile-converter --input-type I3S --tileset https://tiles.arcgis.com/tiles/P3ePLMYs2RVChkJx/arcgis/rest/services/DevA_BuildingShells/SceneServer/layers/0 --name test [--egm C:/Users/Rushi/Desktop/New folder/deps/egm2008-5.pgm]

![image](https://user-images.githubusercontent.com/85739604/121673568-4de7ef80-cab1-11eb-8f63-32760d6f4508.png)

If I use https://steinbeis-3dps.eu/scenelayers/hftbldg2/layers/0

![image](https://user-images.githubusercontent.com/85739604/121673999-cfd81880-cab1-11eb-897b-81828fc368de.png)

Connection to the services are also uninterrupted.

Can you help ?

Thank you,
Rushi

**Comment by dryabinin-actionengine** [comment]
@RushiMUFC Thank you for your attention to our product. Will take a look at this issue and keep you posted about results.

**Comment by RushiMUFC** [comment]
@dryabinin-actionengine Many thanks :-)

**Comment by dryabinin-actionengine** [comment]
@RushiMUFC I found a place where error is occur. The problem related to parsing `name` attribute from attribute binary file. Some  binary files have wrong internal structure. They consist only from 13 bytes but it should be multiple of 4. It should follow the following [spec](https://github.com/Esri/i3s-spec/blob/master/docs/1.7/attributeStorageInfo.cmn.md#string).
I think we should do additional validation for such files. I attached some screenshots of binary attribute files from your tileset.
Wrong attribute binary file:
![image](https://user-images.githubusercontent.com/70207219/121686761-454fe300-caca-11eb-9170-cb5644948633.png)
Good attribute binary file:
![image](https://user-images.githubusercontent.com/70207219/121686926-703a3700-caca-11eb-8653-25a73753ae2e.png)

**Comment by dryabinin-actionengine** [comment]
@RushiMUFC I added some validation in parse string attribute function. After that I done conversion successfully.![image](https://user-images.githubusercontent.com/70207219/121688919-ac6e9700-cacc-11eb-9661-7a75e8886554.png)
Also I see some warnings related to the textures: `Unexpected texture format in I3S` Will investigate this.

**Comment by RushiMUFC** [comment]
@dryabinin-actionengine I see. Many thanks for pointing this out. Additionally, I now used  https://tiles.arcgis.com/tiles/1lplwYilIlo008hQ/arcgis/rest/services/stuttgartLoD1_HfTLoD4_slpk/SceneServer/layers/0 and the conversion to 3D tiles works fine but with broken textures. Also, can you suggest any hint on how to move from Esri terrain to Cesium world terrain during the conversion process?

**Comment by dryabinin-actionengine** [comment]
@ibgreen Yes I wasn't really clean about spec. It is more related to how JS works with binary data. And yes we have such error when we want to get `String count` by using  `const stringsCount = new Uint32Array(arrayBuffer, 0, 4)[0];` At this case if `arrayBuffer` is not multiple of 4 we will get an error about that.

**Comment by dryabinin-actionengine** [comment]
@RushiMUFC What do you mean by terrain? Is it a base map under geometry or some differences in elevation?

**Comment by RushiMUFC** [comment]
> @RushiMUFC What do you mean by terrain? Is it a base map under geometry or some differences in elevation?

@dryabinin-actionengine I meant the elevation differences for eg. if buildings in i3s are referenced using Esri  world elevation https://elevation.arcgis.com/arcgis/rest/services/WorldElevation/Terrain/ImageServer then during the i3s-3d tiles conversion snapping it on Cesium world terrain

**Comment by dryabinin-actionengine** [comment]
@RushiMUFC The only way to change elevation is to use more accurate EGM model from this resource https://geographiclib.sourceforge.io/html/geoid.html .
@belom88 Am I right? I you have more info please provide it below.

**Comment by belom88** [comment]
Elevation conversion (Geoid <-> Ellipsoid) is implemented. The Earth Gravity Model file is used for this purpose. You are installing it with
`tile-converter --install-dependencies` . Without this model file conversion doesn't work.

**Comment by RushiMUFC** [comment]
> Elevation conversion (Geoid <-> Ellipsoid) is implemented. The Earth Gravity Model file is used for this purpose. You are installing it with
> `tile-converter --install-dependencies` . Without this model file conversion doesn't work.

@belom88 yes, may be in the first place, I just used the file as it is. If I am not wrong, I need to do some interpolation and change some values in .pgm file ?

**Comment by belom88** [comment]
Converter already does this interpolation.

**Comment by RushiMUFC** [comment]
> Converter already does this interpolation.

@belom88 ohh! Then there is something missing. During the conversion, there was no change in the output 3D tiles elevation

**Comment by ibgreen** [comment]
Probably pointing out the obvious, but just to be clear, the geoid adjustment is fairly minor (couple of meters) and does not represent actual terrain / land elevations. It just represents the difference between a perfect ellipsoid and the (extended) sea level variation due to the "gravitational lumpiness" of the earth.

**Comment by dryabinin-actionengine** [comment]
@RushiMUFC @ibgreen I merged fix for multiple of 4 error while string attribute parsing. I see a few issues were discussed in this one. If some issues are not resolved by my fix, my suggestion is to create more issues with another descriptions.

**Comment by ibgreen** [comment]
Agreed. We need one clean github issue per problem. We can always reference the discussion here if we open new issues.

**Comment by RushiMUFC** [comment]
> @RushiMUFC @ibgreen I merged fix for multiple of 4 error while string attribute parsing. I see a few issues were discussed in this one. If some issues are not resolved by my fix, my suggestion is to create more issues with another descriptions.

@dryabinin-actionengine yes sure. Many thanks for your help and fix. I will give it a try.
