### ISSUE TITLE
Title-Converter API Error

### ISSUE THREAD

**Issue by haitunxiaomo** [visgl/loaders.gl#1501]
I want to use the API to convert i3s to 3dObject,but i ran into some problems when i adding dependency files.
Steps are as follows:
1、run 'npm install @loaders.gl/core' and 'npm install @loaders.gl/tile-converter'  under the 'loaders.gl\examples\experimental\3d-tiles-with-three.js' directory.

2、Run 'npm start', is OK 。 But add 'import {Tiles3DConverter} from '@loaders.gl/tile-converter';' under the 'loaders.gl\examples\experimental\3d-tiles-with-three.js\threejs-3d-tiles\three-tileset.js' directory, then Running 'npm start', error on command line .
![image](https://user-images.githubusercontent.com/8519144/122003734-0aa9bb80-cde6-11eb-95be-5c2dec75dbba.png)

**Comment by haitunxiaomo** [comment]
![image](https://user-images.githubusercontent.com/8519144/122004220-b6eba200-cde6-11eb-84ca-a1adae4867fe.png)

Install '@loaders.gl/core' and '@loaders.gl/tile-converter' files into ''loaders.gl' folder or 'loaders.gl\examples\experimental'?

**Comment by belom88** [comment]
Unfortunately, tile-converter is nodejs tool. It can't be used in a web browser due to nodejs dependencies. `fs` is a nodejs module which works with the file system.

**Comment by haitunxiaomo** [comment]
So how does this API work

**Comment by haitunxiaomo** [comment]
Can command-line tools convert SLPK files?

**Comment by belom88** [comment]
> Can command-line tools convert SLPK files?

No

**Comment by haitunxiaomo** [comment]
![image](https://user-images.githubusercontent.com/8519144/122011795-12219280-cdef-11eb-9f7e-41fb61b3c270.png)
Can't I also convert the SLPK file after unzipping it?

**Comment by belom88** [comment]
> So how does this API work

npx -p @loaders.gl/tile-converter@beta tile-converter --help 
npx -p @loaders.gl/tile-converter@beta tile-converter --install-dependencies
npx -p @loaders.gl/tile-converter@beta tile-converter --input-type I3S --tileset https://tiles.arcgis.com/tiles/u0sSNqDXr7puKJrF/arcgis/rest/services/Frankfurt2017_v17/SceneServer/layers/0 --name I3S_Frankfurt --max-depth 5

**Comment by belom88** [comment]
> ![image](https://user-images.githubusercontent.com/8519144/122011795-12219280-cdef-11eb-9f7e-41fb61b3c270.png)
> Can't I also convert the SLPK file after unzipping it?

No. Unfortunately, I3SLoader only supports loading from http/https service.

**Comment by haitunxiaomo** [comment]
> > So how does this API work
> 
> npx -p @loaders.gl/tile-converter@beta tile-converter --help
> npx -p @loaders.gl/tile-converter@beta tile-converter --install-dependencies
> npx -p @loaders.gl/tile-converter@beta tile-converter --input-type I3S --tileset https://tiles.arcgis.com/tiles/u0sSNqDXr7puKJrF/arcgis/rest/services/Frankfurt2017_v17/SceneServer/layers/0 --name I3S_Frankfurt --max-depth 5


This is the same as the command line!

**Comment by haitunxiaomo** [comment]
![image](https://user-images.githubusercontent.com/8519144/122014597-e3f18200-cdf1-11eb-82b8-ff71630b17b1.png)

This is the API used!

**Comment by belom88** [comment]
This is command line but it uses Tiles3DConverter . If you want to use this class in your application start from the test case as example:
https://github.com/visgl/loaders.gl/blob/master/modules/tile-converter/test/3d-tiles-converter/3d-tiles-converter.spec.js

Don't mind it is commented. It works. We commented it because it uses 3rd-party http service and can be flaky.

**Comment by haitunxiaomo** [comment]
One more question,
Does the i3S file only support IntegratedMesh data?Does it support 3Object data?

**Comment by belom88** [comment]
See the layerType field in your tileset: https://github.com/Esri/i3s-spec/blob/master/docs/1.7/3DSceneLayer.cmn.md

I3S support both layer types

**Comment by dryabinin-actionengine** [comment]
@haitunxiaomo As I see a lot of problem were discussed here. I think the main problem related to using tile-converter in browser were discussed and everything is clear from that perspective. I think we should close this one. Also I think it is make sense to improve tile-converter documentation to avoid such misunderstanding.

**Comment by dryabinin-actionengine** [comment]
I created an [issue](https://github.com/visgl/loaders.gl/issues/1541) related to improving tile-converter documentation
