### ISSUE TITLE
Tile-Converter--TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by haitunxiaomo** [visgl/loaders.gl#1503]
![image](https://user-images.githubusercontent.com/8519144/122041372-781c1300-ce0b-11eb-833a-9482648a2b70.png)
 
I published a 10GB file locally and the conversion failed.Please check what causes it.

**Comment by belom88** [comment]
Make sure you the URL from your screenshot works in a web browser.

**Comment by haitunxiaomo** [comment]
The url is ok.
I can get map information by this url.
![image](https://user-images.githubusercontent.com/8519144/122143159-7b52e580-ce83-11eb-9fba-f1462458b9f9.png)
![image](https://user-images.githubusercontent.com/8519144/122143213-99204a80-ce83-11eb-8d5f-c8328201473a.png)

**Comment by dryabinin-actionengine** [comment]
@haitunxiaomo Is this still reproduced or it was connection issue? If it still reproduced please provide failed url and we will take a look.
Also after such bugs we decided to improve error messaging in tile-converter. I created an [issue](https://github.com/visgl/loaders.gl/issues/1539) for that.

**Comment by dryabinin-actionengine** [comment]
@haitunxiaomo Please try to reproduce it again. If any problems you are welcome to reopen the issue.
