### ISSUE TITLE
Tile converter conversion from i3s to 3D Tiles does not support texture atlases

### ISSUE THREAD

**Issue by haitunxiaomo** [visgl/loaders.gl#1510]
![image](https://user-images.githubusercontent.com/8519144/122148280-d3421a00-ce8c-11eb-8f06-4482bb738b86.png)
![image](https://user-images.githubusercontent.com/8519144/122148412-0d132080-ce8d-11eb-8fd1-1c9eb66c3407.png)

The image one is i3s data and two is 3dtileset data.
I convert i3s to 3dtileset, but the result data is error. The material is garbled.

**Comment by belom88** [comment]
Apparently, source I3S texture is atlas. We don't support atlas texture conversion now. I'll take a look what we can do.

**Comment by ibgreen** [comment]
Core glTF does not support atlased textures, but it can be done by adding support for the [KHR_texture_transform](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_texture_transform) extension.

- For conversion this would require the ability to generate glTF files with texture transform extension objects, which is probably not too hard.
- However for rendering such 3D tiles with deck.gl, we would also need to add support for such transforms to luma.gl and perhaps also deck.gl.

**Comment by belom88** [comment]
This issue should be fixed by https://github.com/visgl/loaders.gl/pull/1894

**Comment by 2496772010** [comment]
<img width="1236" height="763" alt="Image" src="https://github.com/user-attachments/assets/1e77c1d2-fcd6-44db-ae57-13d401d730e5" />
the i3s to 3dtiles remain has the texure bug，please help me
