### ISSUE TITLE
Tile converter, some models are displayed transparently

### ISSUE THREAD

**Issue by haitunxiaomo** [visgl/loaders.gl#1516]
I'm sorry to ask you another question。
I converted some 3Dtiles to I3s files.When the converted file is displayed in ArcGIS, some models are displayed transparently, but click to get the outsourcing box.

![image](https://user-images.githubusercontent.com/8519144/122344038-f0ecad80-cf78-11eb-9b0d-2d342cfd639d.png)

**Comment by dryabinin-actionengine** [comment]
@haitunxiaomo  No worries it is good that you find more and more issues. It helps us to improve our product. So you are welcome!
As for current tileset: Are you able to provide tileset url for us to debug this issue?

**Comment by haitunxiaomo** [comment]
> @haitunxiaomo No worries it is good that you find more and more issues. It helps us to improve our product. So you are welcome!
> As for current tileset: Are you able to provide tileset url for us to debug this issue?

This file is too large and I don't have an online URL.Let me see if there is a small file that can reproduce the problem.

**Comment by haitunxiaomo** [comment]
> @haitunxiaomo No worries it is good that you find more and more issues. It helps us to improve our product. So you are welcome!
> As for current tileset: Are you able to provide tileset url for us to debug this issue?

Oddly enough, the model sometimes loads, and I rotate it a couple of times, and all of a sudden it loads, and sometimes it doesn't come out for a long time.

![image](https://user-images.githubusercontent.com/8519144/122361603-fd2d3680-cf89-11eb-9d0a-55c6255713e5.png)

**Comment by haitunxiaomo** [comment]
If so, I think it is caused by the large amount of data.But you can't load all the data at once. You need to drag and zoom the map to trigger the map to load the model data.

**Comment by haitunxiaomo** [comment]
There is also a problem that 3DTile data loads are white by default.However, the data converted to SLPK is loaded in black.
![image](https://user-images.githubusercontent.com/8519144/122363511-93ae2780-cf8b-11eb-9aa8-053fde42dc5f.png)

**Comment by dryabinin-actionengine** [comment]
> If so, I think it is caused by the large amount of data.But you can't load all the data at once. You need to drag and zoom the map to trigger the map to load the model data.

@haitunxiaomo Such behavior is possible when a lot of child nodes are on the same level of details.
I mean a situation when parent node has a lot of child nodes with identical LOD value. And when traversal of tiles is happening a lot of nodes are loaded and rendered at the same time.

@belom88 Your thoughts?

**Comment by dryabinin-actionengine** [comment]
> There is also a problem that 3DTile data loads are white by default.However, the data converted to SLPK is loaded in black.
> ![image](https://user-images.githubusercontent.com/8519144/122363511-93ae2780-cf8b-11eb-9aa8-053fde42dc5f.png)
Tile-converter actual version is [beta](https://www.npmjs.com/package/@loaders.gl/tile-converter) now. And all last code and fixes are there.
@belom88  I think we already fixed such "black" issue in tile-converter earlier. 
@haitunxiaomo  Please try to convert it by using our `beta` version of tile-converter by command:
`npx -p @loaders.gl/tile-converter@beta tile-converter ...`

**Comment by haitunxiaomo** [comment]
> > There is also a problem that 3DTile data loads are white by default.However, the data converted to SLPK is loaded in black.
> > ![image](https://user-images.githubusercontent.com/8519144/122363511-93ae2780-cf8b-11eb-9aa8-053fde42dc5f.png)
> > Tile-converter actual version is [beta](https://www.npmjs.com/package/@loaders.gl/tile-converter) now. And all last code and fixes are there.
> > @belom88  I think we already fixed such "black" issue in tile-converter earlier.
> > @haitunxiaomo  Please try to convert it by using our `beta` version of tile-converter by command:
> > `npx -p @loaders.gl/tile-converter@beta tile-converter ...`

I use `npx -p @loaders.gl/tile-converter@beta tile-converter ...` , the model is still black.
[cz.zip](https://github.com/visgl/loaders.gl/files/6669253/cz.zip)

You can try this tileset.

**Comment by belom88** [comment]
`npx -p @loaders.gl/tile-converter@beta tile-converter --input-type 3DTILES --tileset ../tilesets/3d-tiles/cz/tileset.json --name cz-beta`:

![image](https://user-images.githubusercontent.com/18549629/122568114-18637900-d052-11eb-9f24-fe30c13311b5.png)

**Comment by haitunxiaomo** [comment]
> `npx -p @loaders.gl/tile-converter@beta tile-converter --input-type 3DTILES --tileset ../tilesets/3d-tiles/cz/tileset.json --name cz-beta`:
> 
> ![image](https://user-images.githubusercontent.com/18549629/122568114-18637900-d052-11eb-9f24-fe30c13311b5.png)

Try adding '--slpk'

**Comment by belom88** [comment]
I don't have a way to open slpk. What you do for opening it?

**Comment by dryabinin-actionengine** [comment]
@haitunxiaomo I am gonna close it for now. If this issue is still reproduced please let us know.
