### ISSUE TITLE
Tile Url fix

### ISSUE THREAD

**Issue by yan-map** [visgl/loaders.gl#1520]
Hi!
my tileset contains a complex path like
`"content": {"url": "../../../../250/230-48/Tile_p3680_p768/Tile_p3680_p768.json"}`
which the loaders.gl cannot handle and causes an error:
`index.js:27 deck: error during update of Tile3DLayer({id: 'tileset'}) TypeError: e.distanceToCamera is not a function`
can you fix it?

Here's a sample code:
https://nv6d7.csb.app/

**Comment by dryabinin-actionengine** [comment]
@yan-map I create a PR with Fix for your issue. Waiting for @ibgreen review.

**Comment by yan-map** [comment]
I connected loaders.gl `v3.0.0-beta.1` to my sample code https://nv6d7.csb.app/ and same error still exists
i am doing something wrong?

**Comment by ibgreen** [comment]
Current version is `v3.0.0-beta.21`

**Comment by yan-map** [comment]
> Current version is `v3.0.0-beta.21`

can't fint it anyway
![1](https://user-images.githubusercontent.com/53347730/122840556-065c3180-d303-11eb-84d4-74381c17c4fe.png)
![2](https://user-images.githubusercontent.com/53347730/122840560-08be8b80-d303-11eb-86ea-45bd3e567df6.png)

**Comment by ibgreen** [comment]
Sorry my mistake, `beta.1` using the latest version. Mistook for a different issue where someone was using an early alpha version. 

@dryabinin-actionengine this sounds strange, I am pretty sure your PR landed before we published.

I don;t see any calls to `distanceToCamera` see https://github.com/visgl/loaders.gl/search?q=distanceToCamera

@yan-map maybe remove your node_modules directory and reinstall just to be sure?

**Comment by yan-map** [comment]
reinstalled, your changes are applied, as we can see from the loaded source code
![4](https://user-images.githubusercontent.com/53347730/122842995-1a099700-d307-11eb-8095-75ba48a1034f.png)
But the error appears
![5](https://user-images.githubusercontent.com/53347730/122843033-30175780-d307-11eb-8b25-1214096d6a6b.png)

My opinion - there is a problem with building a path to tileset with such a complex "uri" `"content": {"url": "../../../../250/230-48/Tile_p3680_p768/Tile_p3680_p768.json"}`
