### ISSUE TITLE
[@loaders.gl/textures] : path resolution for using basis files

### ISSUE THREAD

**Issue by nicoNz** [visgl/loaders.gl#1524]
As I tried to use parse a .basis file, I had the following error, file at @loaders/texture/lib/../.js cannot be found. I tried to move the lib folder out of the src folders in the node module, which allowed me to run my code sample. 

Is the lib folder at the wrong place or did I did something wrong ?

Thanks

**Comment by ibgreen** [comment]
Not sure I understand your setup... normally loaders.gl loads workers from unpkg CDN.

Are you using loaders.gl in an app or trying to modify the code? 

Are trying to run without internet access?

**Comment by nicoNz** [comment]
I want to create an npm library which use basis, that can work in an electron app or a web app. I thought the decoders were working without CDN and installing the npm packages was enough.

so here is my setup 
  "dependencies": {
    "@loaders.gl/core": "^2.3.13",
    "@loaders.gl/textures": "^3.0.0-alpha.2",

here is how I use it
```
import {BasisLoader} from '@loaders.gl/textures';
import {load} from '@loaders.gl/core';
```
```
fetch(url).then(e=> load(url, BasisLoader, {})).catch(e=>console.error(e))
```

this is the error I get

`Uncaught Error: Cannot find module '@loaders.gl/textures/lib/parsers/parse-compressed-texture'
`

**Comment by ibgreen** [comment]
Understood. Before we dig into this, can you make sure you test with the latest `alpha.21` release? 

FWIW - We are getting close to releasing an official 3.0 so it is a good time to make any final fixes.

**Comment by nicoNz** [comment]
I set 
"@loaders.gl/textures": "^3.0.0-alpha.2" to explicitly "@loaders.gl/textures": "3.0.0-alpha.21",
It fixed it ! Hope it makes sense for you.
thanks

**Comment by ibgreen** [comment]
Great! 

Yes I have also seen that the semver version wildcards (`^`) do not seem to work well with alpha releases.
