### ISSUE TITLE
I3SAttributeLoader not accept custom headers

### ISSUE THREAD

**Issue by Radik24** [visgl/loaders.gl#1537]
I3SAttributeLoader is not accepting custom headers, so I'm not able to use jwt token as header

**Comment by Radik24** [comment]
I suggest to modify `loadFeatureAttributes` method (modules/i3s/src/i3s-attribute-loader.ts):

```
...
let loadOptions = { attributeName, attributeType };

// @ts-ignore
if (options.loadOptions) {
  loadOptions = {
    ...loadOptions,
    // @ts-ignore
    ...options.loadOptions
  };
}

const promise = load(url, I3SAttributeLoader, loadOptions);
...
```

**Comment by ibgreen** [comment]
@Radik24 that seems like a reasonable change. 

Though in 3.0.0-beta.1, `options.headers` is no longer supported, only `options.fetch.headers`.

I wonder if it might make sense at this time for loaders.gl to export its internal `mergeOptions` function.

Just out of curiosity, which service are you using that is causing problems here?

**Comment by Radik24** [comment]
Hi I got inspired by https://loaders.gl/examples/i3s-debug few weeks ago. Don't know if there is some change since then, will check. I set jwt auth recently on my services an realised it's not working now

**Comment by ibgreen** [comment]
Great. I did a pass to remove some deprecated features just before `beta.1` (a major version bump is the only chance we have to do that), and we are eager to make sure everything works as expected.

@dryabinin-actionengine will help you make sure any issues in the demo examples are taken care of.
