### ISSUE TITLE
loadOptions.fetch.headers is ignored

### ISSUE THREAD

**Issue by Radik24** [visgl/loaders.gl#1538]
I switched to 3.0.0-beta.1 and headers does not work anymore. On older version (3.0.0-alpha.21) I was using loadOptions.headers and it worked (there was a warning it'll be deprecated but it worked). Now it's deprecated and not working. It seems to be a global issue, I tried it on Tile3DLayer, I3SLayer and GeoJsonLayer from deck.gl. It seems to be loaders.gl issue, not deck.gl.

**Comment by ibgreen** [comment]
Yes the deprecated top level fetch options are removed. We issue the deprecation warnings so that you get time to update your code before the next major release. 

Just replace `options.headers` with `options.fetch: {headers}`

**Comment by Radik24** [comment]
Yeah I did it and I can't see any headers in browser network

**Comment by ibgreen** [comment]
@dryabinin-actionengine let's make sure we properly merge loadOptions in all places.

**Comment by Radik24** [comment]
Hi,
I'm on 3.0.0-beta.5 and I don't see any deprecation warning now, but there are no headers in request

Tested on TerrainLayer and Tile3DLayer

```
loadOptions: {
  ...
  fetch: {
    headers: this.requestHeaders()
  }
}
```

Don't know if it's issue in loaders.gl repo or deck.gl

**Comment by Radik24** [comment]
Sorry I just realised I had caching enabled on api, so headers are not working on any layer.

deck.gl 8.5.0-alpha.6
loaders.gl 3.0.0-alpha.21

So I'm not sure if it's issue for deck.gl repo or this

**Comment by ibgreen** [comment]
FWIW, loaders.gl is now on `3.0.0-beta.5`, being stabilized for release. 
- There have been a couple of PRs aligning the headers handling for `Tileset3D`, we should be closed to having everything fixed in loaders and a PR is coming into deck `Tile3DLayer`.
- `loadOptions.fetch.headers` should work on other layers. `loadOptions.headers`  no longer works in 3.0.
