### ISSUE TITLE
semantic error TS2322: 'gltf' does not exist in type 'LoaderOptions'. 

### ISSUE THREAD

**Issue by Avnerus** [visgl/loaders.gl#1575]
Hi!
I am using the following code to fetch tiles:
```
    const tileset = new Tileset3D(tilesetJson, {
      loadOptions: {
        maxConcurrency: options.maxConcurrency,
        worker: options.worker,
        gltf: {
          loadImages: false,
        },
        '3d-tiles': {
          loadGLTF: true
        },
      }
    });
```

But this results in an error:
```
[!]  TS2322: Type '{ maxConcurrency: number; worker: boolean;
gltf: { loadImages: false; }; '3d-tiles': { loadGLTF: boolean; }; }' is not assignable to type 'LoaderOptions'.
Object literal may only specify known properties, and 'gltf' does not exist in type 'LoaderOptions'.
```

`LoaderOptions` is defined [here](https://github.com/visgl/loaders.gl/blob/a21a0d49c3b6869591016e1c289c1a9fb7f0b2b6/modules/loader-utils/src/types.ts#L21-L46).

Thanks!

```

**Comment by ibgreen** [comment]
We just need to uncomment this line 
https://github.com/visgl/loaders.gl/blob/a21a0d49c3b6869591016e1c289c1a9fb7f0b2b6/modules/loader-utils/src/types.ts#L45

I commented it out temporarily to help debugging.

**Comment by Avnerus** [comment]
Thanks! Fixed now.
