### ISSUE TITLE
How to package a single module？

### ISSUE THREAD

**Issue by alanwhy** [visgl/loaders.gl#1589]
Hello. I want to ask how to package a single module. Because I fork the code and modify the content by myself, I have to package it in full through yarn bootstrap every time. It takes a long time each time, because I will consider publishing it to my private server npm repository.
It makes me wait for a long time for each full package, which makes me uncomfortable. I looked at some of the documentation in the docs directory but couldn’t find the instructions for packaging a single module (or maybe I didn’t find it?)
I may not have very good technical ability, I hope to get your help, thank you!

**Comment by ibgreen** [comment]
The build system automatically detects and builds every package in the modules folder. Maybe you can just create a `modules-nobuild` folder and move the other packages there?

You could also merge back your changes - if of general interest we might accept them, then you could use public modules. It depends on what you are doing - if you just need some minor config, perhaps we could provide a hook so you don't have to fork?

**Comment by ibgreen** [comment]
Closing but feel free to keep discussing.

**Comment by alanwhy** [comment]
> The build system automatically detects and builds every package in the modules folder. Maybe you can just create a `modules-nobuild` folder and move the other packages there?
> 
> You could also merge back your changes - if of general interest we might accept them, then you could use public modules. It depends on what you are doing - if you just need some minor config, perhaps we could provide a hook so you don't have to fork?

Thank you, this can avoid packaging all modules. Although you need to copy the modules you need back and forth, I think the effect is much better than the original one.

Regarding the latter things, I don't think about it. After all, I will not make too many practical functions here.

good luck!
