### ISSUE TITLE
Texture worker issue in Safari

### ISSUE THREAD

**Issue by dryabinin-actionengine** [visgl/loaders.gl#1637]
@ibgreen  Safari doesn't support `ImageBitmap` +  looks like it doesn't support an `Image` API in Safari when we are in the worker thread.
Therefore I3s-app doesn't work with 1.6 data which has image textures.
Screenshot of `i3s-content-worker.js` code:
![image](https://user-images.githubusercontent.com/70207219/124923625-4b6eac00-e003-11eb-9fae-7c7bce5afd7a.png)
One of possible solutions is to remove creating textures from `i3s-content-worker.ts` file to perform this code outside of worker.

**Comment by ibgreen** [comment]
I assume this is not a problem with the ImageLoader itself, as the loader system is designed to delegate subloaders back to the main thread. If that is not working it is an important bug we need to fix.

You are calling some image handling function in the worker?

Once way to get around this would be to specify `type: data` to the image worker, then you will get back a decoded image (basically a typed array) which workers can process.

**Comment by dryabinin-actionengine** [comment]
> I assume this is not a problem with the ImageLoader itself, as the loader system is designed to delegate subloaders back to the main thread. If that is not working it is an important bug we need to fix.
> 
> You are calling some image handling function in the worker?
> 
> Once way to get around this would be to specify `type: data` to the image worker, then you will get back a decoded image (basically a typed array) which workers can process.

Yes when we use I`3S-content-worker` it includes code related to image parsing and there is no `Image` or `ImageBitmap`  classes inside worker thread in Safari. For example In Chrome browser `Image` class  is available. So we get `loadType` as `data` [here](https://github.com/visgl/loaders.gl/blob/master/modules/images/src/lib/parsers/parse-image.ts#L20)
when we try to parse image as data on this [line](https://github.com/visgl/loaders.gl/blob/master/modules/images/src/lib/parsers/parse-image.ts#L32) 
When we fail on assert [here](https://github.com/visgl/loaders.gl/blob/e4c0e56687b9803666ba82914e73375fa424a138/modules/images/src/lib/parsers/parse-to-node-image.ts#L11) just because we don't have `_parseImageNode` in browser window (global) object.
My point is Safari doesn't support Image class in the worker thread. 
You can check it to add option _workerType: 'test'  to this [line](https://github.com/visgl/loaders.gl/blob/e4c0e56687b9803666ba82914e73375fa424a138/modules/i3s/src/i3s-loader.ts#L80) and comment out the env checking [here](https://github.com/visgl/loaders.gl/blob/e4c0e56687b9803666ba82914e73375fa424a138/scripts/webpack/worker.js#L118) to enable development mode for workers. When do `yarn bootstrap` to create local workers and run 1.6 San Francisco in Safari browser.

**Comment by ibgreen** [comment]
I recommend running `yarn test browser` and opening the URL in Safari. If it fails as you describe, then the test cases should fail.

**Comment by dryabinin-actionengine** [comment]
> I recommend running `yarn test browser` and opening the URL in Safari. If it fails as you describe, then the test cases should fail.

As for `i3s-content-loader.spec.js`  no it doesn't fail just because in tests we use `CompressedTextureLoader`.
<img width="1333" alt="Снимок экрана 2021-07-12 в 10 12 42" src="https://user-images.githubusercontent.com/70207219/125246073-fcbe5c00-e2f9-11eb-9746-ee6b789073e1.png">

Actually we do have test cases for `ImageLoader` with` worker=true` flag. They are all passed.
`const IMAGE_SUPPORTED = typeof Image !== 'undefined';`
`IMAGE_SUPPORTED is true.`

Maybe this problem related to the nested workers in Safari. 
For example I moved out code related to texture parsing outside of I3sContentLoader in this [PR](https://github.com/visgl/loaders.gl/pull/1638) and it works well in Safari.
`IMAGE_SUPPORTED is true.`

**Comment by dryabinin-actionengine** [comment]
@ibgreen Also today I created a worker for `ImageLoader` and tried to run browser tests with worker flag set true. And tests are failed because no Image object inside worker.

**Comment by ibgreen** [comment]
Quick notes:
- I did a PR some time ago to load images in workers: https://github.com/visgl/loaders.gl/pull/650. The performance benefits were not clear so I wasn't convinced that the complexity was worth it.
- The fact that we are hitting the `_parseImageNode` function in the browser seems to be a bug
- I tried the tests in Safari, they don't show the issue (just as you say). One approach could be to make sure we have a test that fails on Safari before we start fixing this.

**Comment by dryabinin-actionengine** [comment]
### My observations related to the data option for ImageLoader:
Looks like ImageLoader code definitely performs in worker thread when ImageLoader is used in i3sContentLoader worker for the following reasons:

 ### I put `image: {type: 'data'}` option to ImageLoader
**Safari behaviour:**
 `Image` and `ImageBitmap` are not available [there](https://github.com/visgl/loaders.gl/blob/06b8128acab1591980c0a9891ff0c60015ba1636/modules/images/src/lib/category-api/image-type.ts#L38). So we go throw `data` case and we fails on this [line](https://github.com/visgl/loaders.gl/blob/06b8128acab1591980c0a9891ff0c60015ba1636/modules/images/src/lib/parsers/parse-to-node-image.ts#L11) just because `_parseImageNode` polyfill function doesn't exist in global object.
**Chrome behaviour:**
Even if we provide an image type `data` option we still go throw `imageBitmap` case [there](https://github.com/visgl/loaders.gl/blob/06b8128acab1591980c0a9891ff0c60015ba1636/modules/images/src/lib/category-api/image-type.ts#L38)  and we fails [there](https://github.com/visgl/loaders.gl/blob/06b8128acab1591980c0a9891ff0c60015ba1636/modules/images/src/lib/category-api/parsed-image-api.ts#L37) just because we don't have a `document` in worker thread.
![image](https://user-images.githubusercontent.com/70207219/125420297-eeaadc73-b64c-4bf2-8a5a-5a2586e8fd1a.png)

@ibgreen Actually in this particular case if one loader with worker calls another the second one is not performed in main thread.
Next step is try to write a test case to cover Safari worker issue.

**Comment by dryabinin-actionengine** [comment]
@ibgreen Here a [PR](https://github.com/visgl/loaders.gl/pull/1663)  with test case which fails in Safari browser

**Comment by ibgreen** [comment]
@dryabinin-actionengine As mentioned separately, a loader calling a sub loader should do so through `context.parse()`, rather than `load()`. There is some documentation on this [here](https://loaders.gl/docs/developer-guide/creating-loaders-and-writers#calling-loaders-inside-loaders). 

I updated the code in #1665 to do this, please fix remaining tests and land.
