### ISSUE TITLE
Syntax Error on classes/tile-3d-batch-table-hierarchy.js file

### ISSUE THREAD

**Issue by HariAkunuri** [visgl/loaders.gl#1713]
Issue:
Syntax error in tile-3d-batch-table-hierarchy.js file. Error as below.

ERROR in ./node_modules/@loaders.gl/3d-tiles/dist/esm/lib/classes/tile-3d-batch-table-hierarchy.js
Module build failed: SyntaxError: "classIds" is read-only

  38 |     classIds.type = AttributeType.SCALAR;
  39 |     binaryAccessor = getBinaryAccessor(classIds);
> 40 |     classIds = binaryAccessor.createArrayBufferView(binaryBody.buffer, binaryBody.byteOffset + classIds.byteOffset, instancesLength);
  41 |   }
  42 | 
  43 |   let parentIndexes;

**Comment by ibgreen** [comment]
This is happening when you are building loaders.gl, not when you are running it?

What bundler / tool chain are you using?

**Comment by HariAkunuri** [comment]
This is happening during run time. We see an error in one of the files. Please refer to line 49 in the below file. A const variable is being tried to re-assigned.
https://github.com/visgl/loaders.gl/blob/master/modules/3d-tiles/src/lib/classes/tile-3d-batch-table-hierarchy.js

**Comment by HariAkunuri** [comment]
I see someone already raised a PR with this issue. Merging and publishing new version with this change should help me get this fixed.
https://github.com/visgl/loaders.gl/pull/1714/files

**Comment by HariAkunuri** [comment]
Hi @ibgreen . I see the PR is merged but the changes are not published yet. This is a blocking change for us as it blocks our production pipeline. Could you please help us publish a new version with these changes?
https://github.com/visgl/loaders.gl/pull/1714/files

**Comment by ibgreen** [comment]
@dryabinin-actionengine publishes patches, I believe he is about to publish 3.0.7?

Did this suddenly regress for you? Did you update some dependency, or this was autoupdated? 

If you are using deck.gl, perhaps you do not have a lock file and this happened when deck.gl 8.5 was published last night, which caused loaders.gl 3.0.0 to be pulled in? 

If so, until the patch is out, you could pin to deck.gl 8.4

**Comment by HariAkunuri** [comment]
This change was updated automatically during one of our builds. 
Also, we are not using deck.gl dependency directly in our application. We are using a library called map-gl and that it internally using deck.gl. Im afraid we do not have control to lock versions in that library. I am only waiting for this patch to get published.
@dryabinin-actionengine - Can you please help us publish this patch version?

**Comment by ibgreen** [comment]
In the mean time, note the "resolutions" field in your package.json. It allows you to override the version of any dependency in project, even indirect dependencies.

**Comment by dryabinin-actionengine** [comment]
@HariAkunuri @ibgreen We have published v3.0.7 version. Please check the issue is gone.
