### ISSUE TITLE
Module not found: Error: Can't resolve 'util'  with Webpack 5

### ISSUE THREAD

**Issue by ruizmarc** [visgl/loaders.gl#1744]
Hi!

After upgrading from deck.gl 8.4.20 to 8.5.2 we found out that we cannot compile our application due to Webpack 5 not including 'util' polyfill by default, well non of node core.

As in an Angular Application, Webpack config is not directly exposed, so the suggested workaround by webpack is not feasible unless we build our very own angular builder which is not very desirable. It would be great to get the lib to compile by itself without the need of extending custom webpack configs  

```
./node_modules/@loaders.gl/loader-utils/dist/esm/lib/node/fs.js:3:0-33 - Error: Module not found: Error: Can't resolve 'util' in 'frontend/node_modules/@loaders.gl/loader-utils/dist/esm/lib/node'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
        - install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "util": false }

```

**Comment by ibgreen** [comment]
@ruizmarc This does not sound good.  Webpack should not be bundling the file that is causing problems. There is a rule that excludes it for browser builds:

https://github.com/visgl/loaders.gl/blob/master/modules/loader-utils/package.json#L34

You can try to add `{"util": false}` to those excludes by hand editing the package.json in your node modules directory. If that helps we can make the change in the library.

**Comment by ruizmarc** [comment]
Just added `{"util": false}` and the error has disappeared! Thanks!

However it doesn't seem we can get this update on angular 12. After fixing this a new error appeared due to angular target es2015. I don't know if you want me to open a new issue or just wait until angular can target to a modern target

```
Error: Optimization error [405.1625a688d307e4bc7f7c.js]: Error: Transform failed with 7 errors:
405.1625a688d307e4bc7f7c.js:21601:8: error: Transforming for-await loops to the configured target environment ("es2015") is not supported yet
405.1625a688d307e4bc7f7c.js:23058:6: error: Transforming for-await loops to the configured target environment ("es2015") is not supported yet
405.1625a688d307e4bc7f7c.js:23067:6: error: Transforming for-await loops to the configured target environment ("es2015") is not supported yet
405.1625a688d307e4bc7f7c.js:23107:0: error: Transforming async generator functions to the configured target environment ("es2015") is not supported yet
405.1625a688d307e4bc7f7c.js:23124:0: error: Transforming async generator functions to the configured target environment ("es2015") is not supported yet
```

**Comment by ibgreen** [comment]
@morphoix Let's add the `util: false` rule above (one line `package.json` change) for next patch release.
