### ISSUE TITLE
svg loader throws error with utf8 characters in the file

### ISSUE THREAD

**Issue by geohuz** [visgl/loaders.gl#1767]
#### Description

Loading svg into bitmap layer throws error: `DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.`

I've checked the svg file/string which contains utf8 characters, the error disappears after removing those characters.

I've tried two methods to fix the issue but all failed:

```
function svgToDataURL(svg) {
  //return `image/svg+xml;base64,${btoa(unescape(encodeURIComponent(svg)))}`
  //return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`
}
```

The svg element with characeters like below: 

```
<text id="你好" font-family="PingFangSC-Regular, PingFang SC" font-size="12" font-weight="normal" fill="#000000">
            <tspan x="375" y="146">你好</tspan>
        </text>
```

**Comment by Pessimistress** [comment]
Looks like it happens here: https://github.com/visgl/loaders.gl/blob/79f3346a933f84ebbcc63597b3cc923ecee91469/modules/images/src/lib/parsers/svg-utils.ts#L16-21

**Comment by geohuz** [comment]
Is there any workaround for this issue? It is urgent for our project as we are using deck.gl

Thanks

**Comment by ibgreen** [comment]
@dryabinin-actionengine @morphoix This looks like a quick one line fix, let's target next patch release.
