### ISSUE TITLE
textures module requires loaders.gl/core alpha version

### ISSUE THREAD

**Issue by ibgreen** [visgl/loaders.gl#1785]
Reported by @trxcllnt 

It is just a devDependency - can we remove it?

loader modules should not depend on core, but I seem to remember that there was a complication here..

**Comment by Pessimistress** [comment]
Not just devDependency: https://github.com/visgl/loaders.gl/blob/v3.0.9/modules/textures/package.json#L44-L45

There are 3 packages referencing `3.0.0-alpha.18` in their dependencies: textures, geotiff and zarr

There is no mentioning of `@loaders.gl/core` in textures/src, not sure why it's a dependency

**Comment by Pessimistress** [comment]
This issue should not be closed. Note that you need separate PRs to master and to the 3.0-release branch to match all internal dependencies with the package version.

**Comment by morphoix** [comment]
> This issue should not be closed. Note that you need separate PRs to master and to the 3.0-release branch to match all internal dependencies with the package version.

Thank you for observing :)

It was closed automatically as I closed the linked PR
As we have current milestone https://github.com/visgl/loaders.gl/milestone/34 in the project we will add it to release branch by cherry-picking separately
