### ISSUE TITLE
Node Build Default Export Needed in `modules/loader-utils/src/lib/node/fs.ts`

### ISSUE THREAD

**Issue by ilan-gold** [visgl/loaders.gl#1815]
I think this is a repeat issue in another spot of the issue behind #1741:  https://github.com/visgl/loaders.gl/blob/master/modules/loader-utils/src/lib/node/fs.ts#L4

**Comment by ibgreen** [comment]
Node dependencies have been fully moved to `@loaders.gl/polyfills` in 4.0 so this should no longer be an issue.
