### ISSUE TITLE
Slowly when load multiple file large PCD

### ISSUE THREAD

**Issue by sonphambk** [visgl/loaders.gl#1858]
HI.
I tried to use loader.gl to load PCD file. When I uploaded file with small size, it is smooth. But I tried to load multi PCD file (about 300MB) at the same time. PCD is very slow when I zoom in and zoom out, drag left or right.
Can you help me?
Thanks.

**Comment by ibgreen** [comment]
This seems expected. Check how many points you have. A typical laptop handles around 1M points fairly well, and performance starts to break down at 5-10M points. 

You may want to look for ways to tile you large datasets using e.g. 3D tiles.
