### ISSUE TITLE
rollup issue with typings in 3.x

### ISSUE THREAD

**Issue by farfromrefug** [visgl/loaders.gl#1895]
In 3.x the typings for `@loader.gl ` packages point to `ts` files and not `d.ts` file.
this make the build fail with rollup. (i actually have never seen such typings).
Is that normal? Do you see how to fix rollup?

Right now i am stuck at 2.x

Thanks

**Comment by farfromrefug** [comment]
@ibgreen awesome! thanks for the feedback!

**Comment by ibgreen** [comment]
From 3.1, clean typings are now generated by `tsc`, so this issue should be solved.

Note that there are some other issues being reporting on rollup specifically, those are being worked through separately.
