### ISSUE TITLE
DracoLoader doesn't load a gltf-pipeline converted draco

### ISSUE THREAD

**Issue by zzhmark** [visgl/loaders.gl#1910]
I want to load some draco gltf compressed using gltf-pipeline, which can be open by three.js dracoloader.

I failed with the following message.

![image](https://user-images.githubusercontent.com/47688877/140039643-2b3f2f8f-d70b-49e7-83ec-61a335a724dd.png)

No clue why it's identified as not, the suffix was indeed .drc.

Or you can suggest a more _proper_ tool to do the compression.

**Comment by zzhmark** [comment]
[54.zip](https://github.com/visgl/loaders.gl/files/7466656/54.zip)

For anyone want to try, here's one of my draco.

**Comment by ibgreen** [comment]
Your file is not a Draco file, it is a glTF file that contains a draco encoded geometry inside a data URL. loaders.gl tries to decode it as draco because you are using the `.drc` extension. Try using the `.gltf` extension and the `GLTFLoader`.

This is the content of your file (with data url truncated), as you can see it is glTF JSON not binary Draco.

```
{
  "accessors": [
    {
      "name": "grp1_1_0_indices",
      "componentType": 5123,
      "count": 9696,
      "min": [
        0
      ],
      "max": [
        1619
      ],
      "type": "SCALAR"
    },
    {
      "name": "grp1_1_0_positions",
      "componentType": 5126,
      "count": 1620,
      "min": [
        4742.949975621717,
        5374.900170934217,
        4252.469995152967
      ],
      "max": [
        8103.039770472033,
        6808.144915052897,
        7117.319615262045
      ],
      "type": "VEC3"
    },
    {
      "name": "grp1_1_0_normals",
      "componentType": 5126,
      "count": 1620,
      "min": [
        -1.0076712694822574,
        -1.0077068534551883,
        -1.0071656432806277
      ],
      "max": [
        0.9838124459865045,
        1.0072983232198975,
        1.007839533394458
      ],
      "type": "VEC3"
    }
  ],
  "asset": {
    "generator": "obj2gltf",
    "version": "2.0"
  },
  "buffers": [
    {
      "name": "54",
      "byteLength": 5916,
      "uri": "data:application/octet-stream;base64,RFJBQ08CAgEBAAAC1AygGQGeGYwBAAEBIP8G1EtL..."
    }
  ],
  "bufferViews": [
    {
      "buffer": 0,
      "byteOffset": 0,
      "byteLength": 5914
    }
  ],
  "materials": [
    {
      "name": "mtl1",
      "pbrMetallicRoughness": {
        "baseColorFactor": [
          0.5,
          0.5,
          0.5,
          1
        ],
        "metallicFactor": 0,
        "roughnessFactor": 1
      },
      "emissiveFactor": [
        0,
        0,
        0
      ],
      "alphaMode": "OPAQUE",
      "doubleSided": false
    }
  ],
  "meshes": [
    {
      "name": "grp1_1",
      "primitives": [
        {
          "attributes": {
            "POSITION": 1,
            "NORMAL": 2
          },
          "indices": 0,
          "material": 0,
          "mode": 4,
          "extensions": {
            "KHR_draco_mesh_compression": {
              "bufferView": 0,
              "attributes": {
                "POSITION": 0,
                "NORMAL": 1
              }
            }
          }
        }
      ]
    }
  ],
  "nodes": [
    {
      "name": "grp1",
      "mesh": 0
    }
  ],
  "scene": 0,
  "scenes": [
    {
      "nodes": [
        0
      ]
    }
  ],
  "extensionsRequired": [
    "KHR_draco_mesh_compression"
  ],
  "extensionsUsed": [
    "KHR_draco_mesh_compression"
  ]
}
```

**Comment by zzhmark** [comment]
I understand what you mean. I've actually tried the GLTFLoader, the error message showed there was something wrong with loading the geometry, which I guess was due to compression.

I think draco is just for geometry & material compression, whether the whole file is a gltf or a glb, which are quite identical formats for many model viewers and loading libs. The suffix and whether it's a binary doesn't really matter.

Anyway, my question becomes, will converting my gltf(draco-style) to glb(draco-style) solve the issue? What exactly, beside the very compression, does a drc need for your loading function?

**Comment by zzhmark** [comment]
Didn't work either, perhaps you're right.

> Each encoded geometry is effectively one binary .drc blob embedded inside the gltf / glb.

So the `Dracoloader` is actually for the stand alone compressed geometry, and I still have to use the `GLTFLoader` and keep the suffix gltf/glb instead?

Then it seems that the function here doesn't have a decompression step, so it doen't recognize the blob.

Based on your info, if I need the compression, I'll have to separate the geometry of one mesh to make it a .drc and load it directly.

This explanation makes sense to me, I'll give it a try.

**Comment by zzhmark** [comment]
After checking Google's doc, I found my draco-compressed gltf was actually not quite straight forward. Yeah, I should start with some OBJ.
