### ISSUE TITLE
tile-converter, incorrect conversion

### ISSUE THREAD

**Issue by skemaikin** [visgl/loaders.gl#1915]
Hi!
There is some problem with b3dm -> slpk conversion. I cannot normally convert tiles.
Original b3dm-tile (Cesium view):
![image_0](https://user-images.githubusercontent.com/62253043/140515722-62d581fa-9f3f-4193-b9ae-e42668772bb2.png)
Result of conversion (loaders.gl view):
![image](https://user-images.githubusercontent.com/62253043/140515597-4ea8072d-25be-480a-a322-7d465999342a.png)

Best regards,
Serge

**Comment by belom88** [comment]
Hi! Could you provide failing dataset to understand the root cause?

**Comment by skemaikin** [comment]
> Hi! Could you provide failing dataset to understand the root cause?

Hi!
[The link.](https://drive.google.com/file/d/1p2z5RK0KvUmsSCcsuDiorVsSk1LOZQlo/view?usp=sharing)

**Comment by belom88** [comment]
I meant source 3DTiles dataset

**Comment by skemaikin** [comment]
> I meant source 3DTiles dataset

oops...
[The source.](https://drive.google.com/file/d/1UNc09MZYgBYbopZKSNeLRsym8cuD89Fw/view?usp=sharing)

**Comment by belom88** [comment]
Thank you for report, I will take a look

**Comment by skemaikin** [comment]
""  closed this in #1968 3 hours ago

Not corrected yet (

**Comment by ibgreen** [comment]
> Not corrected yet 

@skemaikin Just to be clear, did you test this on latest master or are you making the observation that the pull request that just landed (which auto closed the issue) has not been published yet?

**Comment by skemaikin** [comment]
Hi! Sorry for keeping you waiting with the answer. I've just got the latest version and checked it. It works fine! 
Good job, thank you!!!
