### ISSUE TITLE
Link to converted SLPK does not work

### ISSUE THREAD

**Issue by ladislavhorky** [visgl/loaders.gl#2012]
The link in section https://github.com/visgl/loaders.gl/blob/5ff371e858803898f5bb85e642377628ce986bf0/modules/tile-converter/docs/cli-reference/tile-converter.md#show-converted-layer-on-a-map

shows a blank map - probably testing URL to i3s server?
Dev console:
```
loaders.gl: The __VERSION__ variable is not injected using babel plugin. Latest unstable workers would be fetched from the CDN.
...
GET http://localhost/SceneServer net::ERR_CONNECTION_REFUSED
```

**Comment by belom88** [comment]
i3s-server doesn't support slpk. To check you data with i3s-server you need to convert it without `--slpk` option. Actually "no slpk" mode is done specially for this i3s-server application.

**Comment by ladislavhorky** [comment]
Aah, silly me. Sorry, now I get it. I thought this should show some example SLPK available on your site but this is the last step I should do after deploying all the stuff :neutral_face: :palm_tree: . On the second read it is clear. Nevermind. Closing is OK.
