### ISSUE TITLE
__VERSION__ is not injected to worker builds.

### ISSUE THREAD

**Issue by Avnerus** [visgl/loaders.gl#2014]
Hi!
I tried to migrate [three-loader-3dtiles](https://github.com/nytimes/three-loader-3dtiles) to loaders.gl v3.1.1, but now this console error appears in runtime despite using the official npm version:
```
version.ts:10 loaders.gl: The __VERSION__ variable is not injected using babel plugin. 
Latest unstable workers would be fetched from the CDN.
```
The error originates in the draco worker at: https://unpkg.com/@loaders.gl/draco@3.1.1/dist/draco-worker.js

I checked and noticed that workers are now being built using `esbuild`, but those are not configured to use babel nor the `version-inline` plugin. Therefore the  `__VERSION__` variable is left undefined in the worker.

**Comment by ibgreen** [comment]
Yes. We need to find a way to address this with esbuild. Using babel is no longer an option. The build times for the loaders.gl repo were getting close to 20 minutes, which was a massive drag on productivity. 

To clarify is this just an error message. I.e. are things otherwise working?

**Comment by Avnerus** [comment]
Yes, I still have some more testing to, but so far everything seems to work.
Are you planning on resolving this issue in the 3.1 release branch? I would prefer to release a new version of the threejs loader when there are no errors in the console.

**Comment by ibgreen** [comment]
> Are you planning on resolving this issue in the 3.1 release branch?

I think it would require moving to the esbuild JS API rather than using the CLI: https://github.com/evanw/esbuild/issues/69

And yes I'd love to see it fixed in 3.1. Not sure I can get to it given my current workload in luma.gl. But I'd certainly accept a PR.

**Comment by Avnerus** [comment]
How about something like this?
```
 "build-worker": "esbuild src/workers/draco-worker.ts --outfile=dist/draco-worker.js 
--define:__VERSION__=\\\"$npm_package_version\\\" --bundle --minify --sourcemap"
```
Seems to work on my end, but should be tested also on windows.

**Comment by ibgreen** [comment]
Sure, if there is a command line option we can use that.

I suspect this will still might have a problem in that lerna builds the library before bumping the version. But it should work as it did before. Being one patch version off is mostly not a problem.

**Comment by Avnerus** [comment]
Hi @ibgreen, thank you for merging the PR.
I noticed that it was merged into `master` but not yet into `3.1-release `, is it still planned toward that?

**Comment by ibgreen** [comment]
Apologies, must have missed this in the scramble to unbreak 3.1 bundling. Now marked for next patch.

**Comment by Avnerus** [comment]
Hi, no worries! Thank you, can definitely wait for the next patch.

**Comment by belom88** [comment]
v3.1.4 has been published

**Comment by Avnerus** [comment]
Thank you! Works well on my end.
