### ISSUE TITLE
Revert make-node-iterator

### ISSUE THREAD

**Issue by ibgreen** [visgl/loaders.gl#2021]
See discussion: https://github.com/visgl/deck.gl/pull/6511

**Comment by alasarr** [comment]
It's an important bug, all the users who are linked to the latest version of loaders (^3.1.0) without a package-lock are failing.

**Comment by jessekrubin** [comment]
This also causes issues with vite/rollup

Explicitly setting a preferred version of 3.1.1 seems to work, but didnt like having to figure that one out.

**Comment by ibgreen** [comment]
> didnt like having to figure that one out.

In that case you probably want to be a bit wary before you test 3.1.3 but at least it does now seem to pass CI in deck.gl.
