### ISSUE TITLE
Doesn't draw textured model 

### ISSUE THREAD

**Issue by skemaikin** [visgl/loaders.gl#2027]
Hi!
I have the textured model that cannot be drawn correctly. The mouse click allows select the model and highlight it, but normally I cannot view the object.
![image](https://user-images.githubusercontent.com/62253043/146387449-8f618f18-6e4b-440b-8a6b-9ae2590a8b07.png)

[The model](https://drive.google.com/file/d/1vJ28n42HVX1JOZBP1DGC0NX_OCd1SZgT/view?usp=sharing)

Best regards,
Serge

**Comment by ibgreen** [comment]
@dryabinin-actionengine can SLPKs be opened in the loaders.gl website when running the i3s-server?

**Comment by skemaikin** [comment]
> @dryabinin-actionengine can SLPKs be opened in the loaders.gl website when running the i3s-server?

Yes, loaders.gl opens the file, but cannot draw it correctly. Console log: **BLEND alphaMode might not work well because it requires mesh sorting**.

**Comment by belom88** [comment]
@skemaikin could you explain how do you open the file? We don't support slpk parsing in @loaders.gl now. This is only plan for the next year.
