### ISSUE TITLE
tile-converter is storing duplicated textures when converting 3dtiles to i3s slpk bloating slpk size

### ISSUE THREAD

**Issue by Tamrat-B** [visgl/loaders.gl#2047]
Texture resources are being duplicated when converting 3dtiles to i3s slpk. 

In addition to the correct texture output in the slpk, there is a duplicated texture (0\index.jpg and/or 1\index.ktx2) that should only be output when creating content for serving i3s (not in slpk).

**Comment by belom88** [comment]
Converted slpk has file structure:
![image](https://user-images.githubusercontent.com/18549629/149013716-a1f80213-438e-4d67-acf1-18d23d9aa24a.png)
Expected result:
![image](https://user-images.githubusercontent.com/18549629/149013799-0593723a-4cca-441f-8ed2-38ca6c0e5993.png)

**Comment by belom88** [comment]
spec: https://github.com/Esri/i3s-spec/blob/master/format/Indexed%203d%20Scene%20Layer%20Format%20Specification.md#example-18-slpk-structure-summary-for-3d-objects-

**Comment by belom88** [comment]
3.1.5 has been published
