### ISSUE TITLE
Is there any relation between .bin and .gltf(or .glb)?

### ISSUE THREAD

**Issue by learnerandtrainer** [visgl/loaders.gl#2053]
Hi everyone ,
I want to appologise if my ask is too simple because of I am new about i3s format.
I saw isContentSupported function when  read source code of 'i3s-converter'. But I didnt see transform of mesh . Can we say .bin content equals to gltf mesh content.  Is there any relation beetwen them?

**Comment by belom88** [comment]
> Can we say .bin content equals to gltf mesh content.
`.bin` is a binary chunk for a GLTF model. There should be `.gltf` file which contain external link to that `.bin` file.

**Comment by learnerandtrainer** [comment]
thank you belom88
