### ISSUE TITLE
I3S Layer that created by loaders.gl cant be loaded by loader?

### ISSUE THREAD

**Issue by learnerandtrainer** [visgl/loaders.gl#2061]
Hi,
I have a 3d-tile and I can preview this on cesium like below. But when I convert it to i3s layer. it didnt load except root .
Can any one help me where is my problem?
in cessium
![image](https://user-images.githubusercontent.com/66632022/149928038-ecbc56aa-07f9-4877-883e-164fb8fc4c7b.png)
in i3s client
![image](https://user-images.githubusercontent.com/66632022/149928757-7854046f-7e9d-42eb-8020-2e24fce3cdec.png)
b3dm file
[Texture.zip](https://github.com/visgl/loaders.gl/files/7888614/Texture.zip)
i3s file
[i3stexture.zip](https://github.com/visgl/loaders.gl/files/7888615/i3stexture.zip)

**Comment by belom88** [comment]
Check if source data has correct elevation. I checked on ArcGis:
![image](https://user-images.githubusercontent.com/18549629/150325178-9cd9f261-8a2c-41c3-a49b-3bea31d2ff3f.png)

If I use the base map transparency - buildings are there. It is because ArcGis has terrain. Cesium doesn't have terrain and we see floating buildings:
![image](https://user-images.githubusercontent.com/18549629/150325620-5790bc8b-b377-4547-98e5-af340e9ef402.png)

**Comment by learnerandtrainer** [comment]
Hi belom88, 
When I test it on arcgis.com like you did, it load every thing but doesnt show anything .If you recreated i3s files, can you send me. 
![image](https://user-images.githubusercontent.com/66632022/150338293-87a07100-1463-4e49-933e-a101a6b49498.png)

**Comment by belom88** [comment]
[Texture-20210120-1.zip](https://github.com/visgl/loaders.gl/files/7906817/Texture-20210120-1.zip)

**Comment by learnerandtrainer** [comment]
Hi belom88,
I dont know why but when I wanted to show i3s files that you sended ,I didnt see any thing . Is There  any configuration on arcgis.com to make it visible except I showed on image .
![image](https://user-images.githubusercontent.com/66632022/150475929-e759080f-b4a8-4a9f-b6dd-aa6076ca5ec7.png)

**Comment by belom88** [comment]
I guess you have errors in the console log. For the ArcGIS you need to have particular route like: `/tiles/z2tnIkrLQ2BRzr6P/arcgis/rest/services`. This part of route is important for ArcGIS. I don't know why. We don't support ESRI services. FYI on I3SExample app it should work as well:
https://loaders.gl/examples/i3s?url=http://localhost/tiles/z2tnIkrLQ2BRzr6P/arcgis/rest/services/Texture-20210120-1/SceneServer

**Comment by learnerandtrainer** [comment]
thank you belom88,
its about my iis default pages. when arcgis loader send iis like /geometry/0/ , my iis doesnt return index.bin I saw when trace network . thank you so much
