### ISSUE TITLE
Overly strict peer dependency breaks npm install

### ISSUE THREAD

**Issue by Pessimistress** [visgl/loaders.gl#2070]
See https://github.com/visgl/deck.gl/discussions/6586#discussioncomment-2055351

https://github.com/visgl/loaders.gl/blob/v3.1.6/modules/3d-tiles/package.json#L46
https://github.com/visgl/loaders.gl/blob/v3.1.6/modules/gltf/package.json#L46
https://github.com/visgl/loaders.gl/blob/v3.1.6/modules/i3s/package.json#L46
https://github.com/visgl/loaders.gl/blob/v3.1.6/modules/ply/package.json#L46
https://github.com/visgl/loaders.gl/blob/v3.1.6/modules/tiles/package.json#L46

This prevents any `@loaders.gl/core` version other than 3.1.0 from being installed.

**Comment by belom88** [comment]
Do you mean in v3.1.7 there should be 
```
"peerDependencies": {
    "@loaders.gl/core": "^3.1.7"
  }
```

**Comment by Pessimistress** [comment]
Peer dependencies usually just specify the lowest compatible version, in this case `^3.0.0`.

**Comment by ibgreen** [comment]
maybe `^3.1.0` is a reasonable middle ground. That way we give some flexibility and we don't need to bump it every release but still keep it reasonably fresh?
