### ISSUE TITLE
Huge/wrong extents in 3dSceneLayer.json.gz if source 3DTiles contain "empty tiles"

### ISSUE THREAD

**Issue by ladislavhorky** [visgl/loaders.gl#2108]
Hello,

when converting 3D Tiles dataset - textured mesh b3dm - [(very small example)](https://github.com/ladislavhorky/slpk-debug/blob/master/test.3dtiles.zip) to SLPK, extents of the resulting SLPK [(result from said example)](https://github.com/ladislavhorky/slpk-debug/blob/master/test.slpk) span half of Europe and ArcGIS never "zooms to layer" which is actually some 50x50m dataset.

Command used for the conversion:
```
$ tile-converter --output ./test.slpk --input-type 3DTILES \
                 --slpk --name test --tileset test.3dtiles/tileset.json
```

The issue seem to be that the 3Dtiles dataset utilitzes "empty tiles" and the dataset lays somewhere deep in the HLOD structure whose LOD 0 spans whole world. Those empty tiles are a valid approach as by [the spec](https://docs.opengeospatial.org/cs/18-053r2/18-053r2.html#51) as far as I understand. They certainly do not cause any problems for any 3D Tiles renderer we encountered so far. All empty tiles have the same size `region` that covers the entire dataset, the geometric error grows appropriately to make the culling work.

Resulting SLPK has everything correct in `nodes/` data (bounding spheres etc.) but extent in 3dSceneLayer.json.gz is
```
        "extent": [
            -2.1053344313647013,
            41.52837601254435,
            23.28348157456591,
            60.34807896225844
        ],
```
where it should be something like
```
        "extent": [
            14.82501633177731,
            50.29116110162847,
            14.825998322644445,
            50.29199349909371
        ],
```
After finding resulting SLPK on the map, all the data look OK as well, so I suspect the extents are the only thing.

Making the 3D Tiles start closer to the data (custom grid, tightly fitting to the data) alleviates this issue but for longer term we need the common grid - and thus the empty tiles - in the 3D Tiles dataset. 

ArcGIS Pro "upgrading" the SLPK also fixes the issue, but it seem to double the amount of texture (thus nearly doubling the size) in the SLPK as well.

ArcGIS version 2.9, tile-converter version 3.1.8

Let me know if you need any additional inputs.

Thanks,
Ladislav

**Comment by belom88** [comment]
Thank you for report. We will check
