### ISSUE TITLE
[doc] postProcessGLTF urls out of sync

### ISSUE THREAD

**Issue by andreasplesch** [visgl/loaders.gl#2120]
There are a number of places where the url to the postProcessGLTF page leads to 404.

https://loaders.gl/modules/gltf/docs/api-reference/gltf-loader#overview
https://loaders.gl/modules/gltf/docs/api-reference/gltf-loader#options
https://loaders.gl/modules/gltf/docs/api-reference/gltf-loader#with-post-processing

https://loaders.gl/modules/gltf/docs#gltf-post-processing

This is the corrected url:

https://loaders.gl/modules/gltf/docs/api-reference/post-process-gltf

(There are also other doc internal urls which are out of sync, perhaps after an reorganization.)

I think

https://github.com/visgl/loaders.gl/blob/master/modules/gltf/docs/api-reference/gltf-loader.md

and 

https://github.com/visgl/loaders.gl/blob/master/modules/gltf/docs/README.md

is the source for these doc pages.

If so, I can provide a quick PR.

**Comment by ibgreen** [comment]
Thanks for reporting. PR is welcome.
