### ISSUE TITLE
3dtiles to i3s lost texture on version 3.1.8

### ISSUE THREAD

**Issue by xuncanzhe** [visgl/loaders.gl#2125]
test data: https://1drv.ms/u/s!AkXxHoUK23z6hOkn91OaG-UW5WDb0w?e=SfS56s
Command1:  npx tile-converter --input-type 3DTILES --tileset /d/Web/data/nicehouse/Tileset.json --name nice --output nice_i3s  
Command2:  npx tile-converter --input-type 3DTILES --tileset /d/Web/data/nicehouse/Tileset.json --name nice --output nice_i3s --generate-textures 
both Effect
![6KXP@CN{WT{PLG9{HH9X 9](https://user-images.githubusercontent.com/7651130/160336062-d75b273a-2d77-43db-bb20-7401e7a72e44.png)
Is there anything wrong with my command line? Can anyone help me with this issue?

**Comment by belom88** [comment]
The source tileset is of glTF v1.0 . We have the code that normalizes glTF to v2.0 but it is experimental.
For the material normalization we expect texture key `tex`. In your data we have texture key `texture2d_0`. I'll create a PR to process `texture2d_0` key as well.
![image](https://user-images.githubusercontent.com/18549629/164425710-1a00af44-9662-42de-82e1-fb7cadb7f229.png)
