### ISSUE TITLE
Any working examples of glTF parsing on node.js?

### ISSUE THREAD

**Issue by xeolabs** [visgl/loaders.gl#2174]
Hi, can anyone share a work example/demo of using loaders.gl (and polyfills) to parse glTF on Node.js?

I just needing a working reference, to help determine if an issue I'm having is on my end, or something I should log here.

Specifically, I'm using ````@loaders.gl/core````, ````@loaders.gl/gltf```` and ````@loaders.gl/polyfills````, but any example that runs on Node would be great.

Thanks!

**Comment by belom88** [comment]
Look at tests: https://github.com/visgl/loaders.gl/blob/master/modules/gltf/test/gltf-loader.spec.js . These work on nodejs as well. You still need to import `@loaders.gl/polyfills`.
