### ISSUE TITLE
load 3d-tiles with babylon.js

### ISSUE THREAD

**Issue by xinnianyoulin** [visgl/loaders.gl#2180]
Hi!

I have some doubts when using @loaders.gl/3d-tiles and @loaders.gl/tiles to load 3dtiles. Is the gltf in the parsed tileHeader result the description of the model? I'm trying to render via babylon.js but get this error message. 

![image](https://user-images.githubusercontent.com/32128165/169185292-7380972b-8521-4e97-a60a-c519921bbf85.png)

![image](https://user-images.githubusercontent.com/32128165/169185247-50bcee16-5b08-4d6a-b283-a637930caeac.png)

![image](https://user-images.githubusercontent.com/32128165/169185137-c519b175-597d-4001-81ec-34dc6ad29eb7.png)

![image](https://user-images.githubusercontent.com/32128165/169185336-68ed77f2-e7d1-48b8-b23a-fba73735da86.png)

Sorry i'm a newbie, has anyone implemented loading 3dtiles with babylon.js?

**Comment by Hypnosss** [comment]
Meeting the same problem, many properties should be the index rather than an object(like `scene`, it should be 0 in the example). And I noticed it works fine in the reality capture demo of [three-loader-3dtiles](https://github.com/nytimes/three-loader-3dtiles). I tried the same edition but failed, still trying to find other reasons.

**Comment by xinnianyoulin** [comment]
> Meeting the same issue, many properties should be the index rather than an object(like `scene`, it should be 0 in the example). And I noticed it works fine in the reality capture demo of [three-loader-3dtiles](https://github.com/nytimes/three-loader-3dtiles). I tried the same edition but failed, still trying to find other reasons.

Thanks for sharing, great project, I will check it out. Currently I use gltf.meshs to render via BABYLON.VertexData.

**Comment by ibgreen** [comment]
By default, loaders.gl performs some post processing on glTF to clean up the data, handle some glTF extensions, and make it easier to traverse etc.

You should be able to disable this by passing [gltf loader options](https://loaders.gl/modules/gltf/docs/api-reference/gltf-loader#options)
```typescript
{
  gltf: {
    postProcess: false
  }
}
```

Another approach is that you can disable gltf parsing completely, and pass the embedded GLB binary to your Babylon.js glTF parser (assuming it can consume an ArrayBuffer). See [Tiles3DLoader options](https://loaders.gl/modules/3d-tiles/docs/api-reference/tiles-3d-loader#options)

```typescript
{
  '3d-tiles: {
    loadGLTF: false
  }
}
```

**Comment by xinnianyoulin** [comment]
> By default, loaders.gl performs some post processing on glTF to clean up the data, handle some glTF extensions, and make it easier to traverse etc.
> 
> You should be able to disable this by passing [gltf loader options](https://loaders.gl/modules/gltf/docs/api-reference/gltf-loader#options)
> 
> ```ts
> {
>   gltf: {
>     postProcess: false
>   }
> }
> ```
> 
> Another approach is that you can disable gltf parsing completely, and pass the embedded GLB binary to your Babylon.js glTF parser (assuming it can consume an ArrayBuffer). See [Tiles3DLoader options](https://loaders.gl/modules/3d-tiles/docs/api-reference/tiles-3d-loader#options)
> 
> ```ts
> {
>   '3d-tiles: {
>     loadGLTF: false
>   }
> }
> ```

Thank you, I read the source code and tried to match the gltf parsing result with the gltf model description file to facilitate direct overlay.

After I modified `gltf.postProcess = false`, I got an error message: `Unable to load from file:model.gltf: /meshes/0/primitives/0/indices: Failed to find index ([object Object] )`.

Then I modified `gltf.decompressMeshes = false`, the error message indicated that I was missing buffer and image resources, then I converted the arrayBuffer data in buffers and images to base64 and placed it on the uri field.

It still failed to load in the end, with a new error message `Unsupported geometry type`, it seems that the accessors are missing bufferView index value and the related extensions in gltf (meshs[number].primitives[number]) also caused this error. I need to manually delete the contents of the extensions in gltf and add the accessors.bufferView field, but I don't know what value to add, so I gave up this solution.

**Comment by xinnianyoulin** [comment]
> Another approach is that you can disable gltf parsing completely, and pass the embedded GLB binary to your Babylon.js glTF parser (assuming it can consume an ArrayBuffer). See [Tiles3DLoader options](https://loaders.gl/modules/3d-tiles/docs/api-reference/tiles-3d-loader#options)
> 
> ```ts
> {
>   '3d-tiles: {
>     loadGLTF: false
>   }
> }
> ```
Thanks a lot, now I use Babylonjs' GLTFFileLoader to load the parsed gltfArrayBuffer, although it takes some waiting time when loading large data, but it works well.

**Comment by swarmt** [comment]
Are you able to post a minimum working example? 
Would be much appreciated.

**Comment by Mrzhubingxin** [comment]
> > 一种方法是您可以完全禁用tf解析，并将其嵌入的GLBTiles另外提供3D文件传递给glTF解析器（假设它可以使用ArrayBuffer加载[器）。](https://loaders.gl/modules/3d-tiles/docs/api-reference/tiles-3d-loader#options)
> > ```ts
> > {
> >   '3d-tiles: {
> >     loadGLTF: false
> >   }
> > }
> > ```
> 
> 非常感谢，现在我使用Babylonjs的GLTFFileLoader来加载解析后的gltfArrayBuffer，虽然在加载大数据的时候需要一些等待时间，但是效果很好。

可以分享一下你的PG吗哥

**Comment by FreakTheMighty** [comment]
@ibgreen is this the correct way of disable gltf loading?

```typescript
    const tilesetJson = await load(tilesetUrl, Tiles3DLoader, {'3d-tiles': {loadGLTF: false}});
```

When I do this, I still see http requests for the glb's in the content and the tile loads with content, but I'm not entirely sure what the expected behavior is with this disabled.

**Comment by andreasplesch** [comment]
It would be really helpful to have a full example like this where loader.gl 3D tile loader is used outside of the visgl framework, eg. babylon.js or another gltf renderer.

**Comment by ibgreen** [comment]
> It would be really helpful to have a full example like this where loader.gl 3D tile loader is used outside of the visgl framework, eg. babylon.js or another gltf renderer.

There is https://github.com/visgl/loaders.gl/tree/master/examples/experimental/3d-tiles-with-three.js. It is written against an older loaders.gl version, but otherwise complete and should be indicative.

**Comment by ibgreen** [comment]
I see the contributor turned that example into its own repo: https://github.com/nytimes/three-loader-3dtiles

**Comment by andreasplesch** [comment]
Thanks, that is great.
