### ISSUE TITLE
3D Tiles: Tileset3d crashes when loading root-tileset with `boundingVolume.center = [0,0,0]`

### ISSUE THREAD

**Issue by usefulthink** [visgl/loaders.gl#2196]
I am working with a large tileset for an entire planet, where the bounding-box center of the root-tileset is the center-point (`[0,0,0]`) of the ellipsoid. 

In this case, the cartographicCenter can not be reasonably be computed in `Tileset3d.calculateViewPropsTiles3D()` (`Ellipsoid.WGS84.cartesianToCartographic` returns `undefined`). This in turn leads to `getZoomFromBoundingVolume` to fail hard, since cartographicCenter is undefined: `TypeError: Cannot read properties of undefined (reading '2')`.

Is there something that could be done in this situation?

**Comment by belom88** [comment]
There is infinite number of cartographic coordinates for the cartesian coordinate [0, 0, 0]. What the expected behavior? because it is not clear what place on map you want to start to explore from.
I guess a fix in https://github.com/uber-web/math.gl is required to handle this extremum case.

**Comment by usefulthink** [comment]
For me it's a bit hard to tell what the best way to handle it would be, as I only just started with this implementation and don't yet know exactly what the significance of `cartographicCenter` is. 

I would think that the behaviour of the math.gl implementation is reasonable here, but the 3d-tiles loader should probably be able to handle it. I think I would go for setting cartographicCenter as `[0, 0, -Ellipsoid.WGS84.radii[0]]`, which seems like a good choice for a global tileset.

Will try that out and see if it would work...

**Comment by ibgreen** [comment]
The current setup is designed to result in a tile which has a lng/lat center and where all points are in small meter offsets from that center. This structure is good for maintaining precision during calculations and allows for very efficient rendering in deck.gl Tile3DLayer.

I agree that the Tile3DLoader should not crash on any tileset, but it is not obvious to me that picking an arbitrary point on the globe is going to work well as many tiles will presumably have very big meter offsets and not render correctly in deck.gl.

Maybe such a tileset needs to set a flag indicating that it is "non cartographic"?

**Comment by usefulthink** [comment]
The thing is, it is a global cartographic tileset. The root tile itself represents the whole spherical earth, but it doesn't have any content of it's own. Subsequent refinements that actually contain the meshes won't have this problem anymore and have non-zero bounding-box centers. This is very similar to the cesium global tilesets, but there the root-tile uses `boundingVolume.region` declaring the whole sphere instead of a `boundingVolume.box`.

The reasoning for using lat 0 / lng 0 was just that it is the centerpoint of most maps, so it would be a slightly better representation for a global tile than any other arbitrary point (maybe one of the poles would also make sense, maybe depending on how the cartographicCenter is used).

**Comment by ibgreen** [comment]
Yes of course. When we say "cartographic" in this context, we happen to mean that it can be expressed in local lat/lng coordinate system, as opposed to a global cartesian coordinate system.

I am suspecting that your root tile doesn't have any geometry associated with it and could probably just be ignored, as long as we don't crash during calculations.

**Comment by usefulthink** [comment]
Yes, exactly what I was thinking. I'll try to manually load a tile one level below and see if that works in the meantime.
