### ISSUE TITLE
I3S fetch error with loadOptions.fetch.signal

### ISSUE THREAD

**Issue by Radik24** [visgl/loaders.gl#2199]
Hi,

after upgrading to `3.2.4` from `3.2.3` I see some errors in `I3SLoader`.

![image](https://user-images.githubusercontent.com/23722745/174581997-96bee671-c73d-49ed-a2d8-b581708b402a.png)

```
new Tile3DLayer({
  ...,
  loadOptions: {
    ...
    fetch: {
      headers: this.requestHeaders(),
      signal: this.abortSignal
    }
  }
})
```

It seems to be fine with other loaders (cesium). It also works fine with I3S BSL, but not with 'regular' I3S.

Thanks

**Comment by belom88** [comment]
Is `this.abortSignal` instance of `AbortSignal`? It cannot be passed to the worker and back.
This issue come because of this fix https://github.com/visgl/loaders.gl/pull/2183 for https://github.com/visgl/loaders.gl/issues/2170 . Textures are loaded in a worker thread.

**Comment by Radik24** [comment]
Yes it is instance of `AbortSignal`.I can remove AbortSignal, but how can i abort requests now? Now when I switch map, it aborts all the queued requests and loads new map and tiles faster.

**Comment by belom88** [comment]
The possible workaround for you is switching off "i3s-content-worker":
```
new Tile3DLayer({
  ...,
  loadOptions: {
    ...
    worker: false,
    fetch: {
      headers: this.requestHeaders(),
      signal: this.abortSignal
    }
  }
})
```
But is will slow down loading of I3S geometry and textures.

**Comment by belom88** [comment]
> it aborts all the queued requests

not textures I guess

**Comment by Radik24** [comment]
Ok Thanks you! Will think about it.
