### ISSUE TITLE
3d-tiles module TypeScript build failure

### ISSUE THREAD

**Issue by Pessimistress** [visgl/loaders.gl#2202]
`_initializeBinaryProperty` is not typed here:
https://github.com/visgl/loaders.gl/blob/3.2-release/modules/3d-tiles/src/lib/classes/tile-3d-batch-table.ts#L218

And get compiled to:
```js
_initializeBinaryProperty(name: any, property: any): {
        typedArray: import("modules/math/src/geometry/types").TypedArray;
        componentCount: any;
        unpack: any;
        pack: any;
    } | null;
```
The import will fail if trying to build a project with this dependency.

See https://unpkg.com/browse/@loaders.gl/3d-tiles@3.2.4/dist/lib/classes/tile-3d-batch-table.d.ts

**Comment by belom88** [comment]
Included in v3.2.5
