### ISSUE TITLE
Upgrade apache-arrow

### ISSUE THREAD

**Issue by Pessimistress** [visgl/loaders.gl#2203]
The current release depend on `apache-arrow@^4.0.0` which is not compatible with the latest TypeScript. 

https://www.npmjs.com/package/apache-arrow

I can confirm that `8.0.0` does not emit any TS build errors, although the upgrade does contain several breaking changes.

**Comment by kylebarron** [comment]
ref https://github.com/visgl/loaders.gl/pull/1931

**Comment by kylebarron** [comment]
As of https://github.com/visgl/loaders.gl/pull/2276, looks like loaders v4 will have an upgraded arrow version

**Comment by ibgreen** [comment]
It is true that we have just landed arrow v9 on 4.0-dev but there is no clear timeline, and it seems there might be some work to be done to handle returning arrow data from worker threads in a good way.

**Comment by ibgreen** [comment]
4.0 beta releases bump to Apache Arrow 13. This brings in two major breaking arrow-js releases (v5 and v11) so there may be impact on applications.
