### ISSUE TITLE
Dependency 'ktx-parse' changing to ES Modules

### ISSUE THREAD

**Issue by donmccurdy** [visgl/loaders.gl#2210]
Hi! This is just a heads up that the [`ktx-parse` package](https://www.npmjs.com/package/ktx-parse) will be publishing only an ES module (without a CommonJS module), beginning with v0.4. Because `loaders.gl/textures` is a popular dependant on the package I wanted to give you a heads up here, in case issues come up.

No changes are should be required, and I don't expect any issues, but downstream users of the Parcel bundler might run into https://github.com/parcel-bundler/parcel/issues/4155, and need to use the workaround described in https://github.com/parcel-bundler/parcel/issues/4155#issuecomment-991866352.

**Comment by ibgreen** [comment]
We haven't had any issues, and loaders.gl 4.0 is now also adopting ES modules so I believe we can safely close this.

**Comment by ibgreen** [comment]
Sounds good, and that is in fact the strategy we chose for the entire vis.gl suite, we are using the package.json exports section in every submodule to offer both ESM and CJS exports, and we have updated our build tools accordingly

The alternative import/require mess would be so painful for our users that we can't stomach the thought of it.

I expect that in a year or two we may well be able to drop the CJS exports.
