### ISSUE TITLE
Can't use @loaders.gl/geopackage with Next.js because of sql.js's dep on fs

### ISSUE THREAD

**Issue by tmcw** [visgl/loaders.gl#2260]
Attempting to use @loaders.gl/geopackage with the default bundler settings from Next.js doesn't work, because of an import to `sql.js` which then tries to access `fs`.

Repro: https://replit.com/@tmcw/loadersglnext-demo#pages/index.tsx

Traceback:

```
error - ./node_modules/sql.js/dist/sql-wasm.js:92:72
Module not found: Can't resolve 'fs'

Import trace for requested module:
./node_modules/@loaders.gl/geopackage/dist/esm/lib/parse-geopackage.js
./node_modules/@loaders.gl/geopackage/dist/esm/geopackage-loader.js
./node_modules/@loaders.gl/geopackage/dist/esm/index.js
./pages/index.tsx
```

**Comment by kylebarron** [comment]
Hmm, I wonder if there's any mention of a similar issue in upstream sql.js issues? As of March I seemed to have issues with sql.js 1.6.x https://github.com/visgl/loaders.gl/pull/2101. There are newer sql.js releases now that might have fixed this? https://github.com/sql-js/sql.js/releases

**Comment by ibgreen** [comment]
Close due to inactivity
