### ISSUE TITLE
i3s 3D Obj texture issue

### ISSUE THREAD

**Issue by davidfungf** [visgl/loaders.gl#2272]
Following with this i3s [tutorial](https://codesandbox.io/s/i3sloadersgldeckgl-34dfp) using my splk file, I found the texture is incorrect. Any parameters are missing? No tutorial is found on loading the texture. Thanks.

[ArcGIS Online](https://tiles.arcgis.com/tiles/6hvouxd2XTE6szh5/arcgis/rest/services/CargoShip/SceneServer)
[Splk file](https://drive.google.com/file/d/1NfAnJGEXDqJXceC-L6pAdBbbVQ-YA0kn/view?usp=sharing)

```
_renderLayers() {
    // construct Tile3DLayer to render I3S tileset
    return [
      new Tile3DLayer({
        id: "tile-3d-layer",
        // Tileset entry point: Indexed 3D layer file url
        data:
          "https://tiles.arcgis.com/tiles/z2tnIkrLQ2BRzr6P/arcgis/rest/services/SanFrancisco_Bldgs/SceneServer/layers/0",
        loader: I3SLoader,
        onTilesetLoad: this._onTilesetLoad.bind(this)
      })
    ];
  }
```
![Capture](https://user-images.githubusercontent.com/3412715/195737799-031f61a9-0bd0-4300-bff6-9bc42d470b4b.PNG)

**Comment by dryabinin-actionengine** [comment]
@davidfungf Hello!
Actually I think you use old verisons of libraries.
Please update viersions and check it again.
This is a sandbox with update versions of loaders.gl and deck.gl - https://stackblitz.com/edit/react-ts-ymz4o5?file=App.tsx,index.tsx,package.json

**Comment by ibgreen** [comment]
Closed due to inactivity
