### ISSUE TITLE
@loaders.gl/3d-tiles,  set clamp to ground ?

### ISSUE THREAD

**Issue by geobuilding** [visgl/loaders.gl#2278]
Sometimes, the 3dtiles data produced is not grounded by default. Is there any way to set height or modelMatrix.

**Comment by ibgreen** [comment]
You should be able to lower it with a modelMatrix however 3D tiles data tends to follow the actual ground elevation - i.e. it is not constant, so the problem is to select the amount of elevation to subtract.

Mixing 2D and 3D data is tricky.

You can also use terrain layer to elevate the ground.
