### ISSUE TITLE
error loading Bitmaplayer in svg with specific width range

### ISSUE THREAD

**Issue by geohuz** [visgl/loaders.gl#2282]
I'm using svg as BitmapLayer over HeatmapLayer,  the following error message displayed in console when loading svg with width range from 1600 to 2600, and the canvas shows nothing other than a black area:

```
WebGL: INVALID_VALUE: textImage2D: width or height out of range
[.WebGL-0000395C003FA900] GL_INVALID_OPERATION: Texture format does not support mipmap generation.
```

The code is like this:

```
<DeckGL views={plain2dView}>
  <Bitmaplayer image = 'background.svg' />
  <HeatmapLayer />
</DeckGL
```

**Comment by ibgreen** [comment]
> `WebGL: INVALID_VALUE: texImage2D: width or height out of range` 

In the first message, WebGL is telling you that the image is too big, see e.g https://stackoverflow.com/questions/14414568/teximage2d-width-or-height-out-of-range-chrome-24

**Comment by ibgreen** [comment]
Based on the fact that it looks like the image loads but then creating a texture fails, I will close this for now as it doesn't appear to be a loaders.gl bug. If you have additional information, feel free to provide it here.
