### ISSUE TITLE
Is there any way to access point cloud data properties?

### ISSUE THREAD

**Issue by jeffpeck10x** [visgl/loaders.gl#2301]
I am tryin the `PointCloudWithPerPointProperties` demo, here:
https://loaders.gl/examples/3d-tiles (select "PointCloudWithPerPointProperties").

The demo does not seem to show a way to view those per-point properties.

I tried loading the data locally, and poking around in the console, I found that the data contains fields "secondaryColor" and "temperature", but I cannot seem to find a way to view that data.

I was hoping to (for example) be able to do something like:
```
getPointColor: d => d.temperature > 50 ? [200, 0, 0] : [0, 200, 0]
```

but `getPointColor` is not even being called, seemingly due to the data already having colors.

How can I access that data from the `Tile3DLayer`?

**Comment by jeffpeck10x** [comment]
Thanks @ibgreen . I just tried that, and it does appear straightforward to subclass and use a custom `renderLayers` to render a custom PointCloud....

but it looks like it is still a challenge to access that data. Here is a screenshot of what the loaded tile header looks like `onTileLoad`:
<img width="599" alt="Screen Shot 2022-12-06 at 1 45 29 PM" src="https://user-images.githubusercontent.com/75277973/205995746-515f4e60-b3bf-4d30-bb22-7b5b50808e5c.png">

You can see those properties `secondaryColor` and `temperature`, but they are seemingly only accessible through `batchTableBinary`. While it is certainly possible for me to use the offsets provided in `batchTableJson` to get at those properties, I am wondering if I am totally missing something. (i.e. I would have expected those properties to be available, just like the case with other properties like `position`, etc.)

Is there a way to bring those properties into `attributes` or just make them more easily accessible per datum?

**Comment by ibgreen** [comment]
Agreed, the loader should extract the data that is there. Especially since we have already loaded it. It was a couple of years since I worked on that so my memory isn't clear but it may be that the batchTable support was not completely finished.

Since it is so easy for you to just attach the necessary typed arrays to the array buffer I am not sure you want to do more work. 

That said I think wiring up a test "tile' file in loaders.gl and making sure this data is actually extracted by the loader would make a lot of sense.

**Comment by jeffpeck10x** [comment]
Aha, gotit.

> Since it is so easy for you to just attach the necessary typed arrays to the array buffer I am not sure you want to do more work.

Can you please elaborate? The above data is from here:
https://raw.githubusercontent.com/visgl/loaders.gl/master/modules/3d-tiles/test/data/PointCloud/PointCloudWithPerPointProperties/tileset.json

Do you mean that I should just try to access the data `onTileLoad` and parse the Uint8Array's there?

I think that is what you mean, but I want to confirm that there is not some easier/better way to do that.

---

And in general, I am wondering why this is not a more common use case. Is there a more common way or better way to store and load properties about points in a 3d point cloud that I am not aware of?

Thanks!

**Comment by ibgreen** [comment]
>  The above data is from here:

OK great, then test data is already in place. I am pretty sure the batchTable handling is already in the code, it is probably just disabled for some reason. Maybe it was never quite completed. Should not take much to get it ready, but...

> Do you mean that I should just try to access the data onTileLoad and parse the Uint8Array's there?

Yes that seems like the path of least resistance.

> And in general, I am wondering why this is not a more common use case. Is there a more common way or better way to store and load properties about points in a 3d point cloud that I am not aware of?

I agree, it is strange - while the 3d tile support in loaders.gl started with the simpler point clouds, which I expected would be of wide interest, surprisingly almost all interest and a very considerable amount of contributions after that has been towards the more complicated "3D model" tiles.

**Comment by jeffpeck10x** [comment]
Aha, well the 3d tiled point clouds are getting some good usage right now in helping me experiment with something, so that work is much appreciated. Thank you for the fast answers and the steering in the right direction.
