### ISSUE TITLE
I3S Loader not working - 404/Requested scene layer node root resource not available

### ISSUE THREAD

**Issue by leefsmp** [visgl/loaders.gl#2309]
Just can't get dataset to load with the I3S loader, it attempts to invoke an endpoint for the root node that doesn't exist on the service. Not sure if the spec isn't correct or if I need to do something on my side to make it work...

https://tiles.arcgis.com/tiles/V6ZHFr6zdgNZuVG0/arcgis/rest/services/BARNEGAT_BAY_LiDAR_UTM/SceneServer/layers/0/nodes/root >> 404 "Requested scene layer node root resource not available."

Sample service:
https://tiles.arcgis.com/tiles/V6ZHFr6zdgNZuVG0/arcgis/rest/services/BARNEGAT_BAY_LiDAR_UTM/SceneServer/layers/0 

Live demo:
https://developers.arcgis.com/javascript/latest/sample-code/layers-pointcloud/live/  

```
const loadTest = async(zoom: number) => {

    const tileseturl = "https://tiles.arcgis.com/tiles/V6ZHFr6zdgNZuVG0/arcgis/rest/services/BARNEGAT_BAY_LiDAR_UTM/SceneServer/layers/0";

  const tileset = await load(tileseturl, I3SLoader);

  const tileset3d = new Tileset3D(tileset, {
    onTileLoad: tile => console.log(tile)
  });

  const viewport = new WebMercatorViewport({
    longitude: -122.431297, 
    latitude: 37.773972, 
    zoom
  })

  tileset3d.update(viewport);

  console.log(tileset3d.tiles)
}
```

**Comment by kauly** [comment]
I'm having the same problem with the cesium-ion-loader. Seems that the bearer token is being modified in the request header.

**Comment by kauly** [comment]
My problem here was that cesium changed the base URL, its working now.

**Comment by leefsmp** [comment]
I think the problem here is that I3S pointcloud tiles API is a bit different than IntegratedMeshes and it's not supported by that loader unfortunately.

**Comment by Tamrat-B** [comment]
@belom88 agreed. Could you pls add an issue to track it.
