### ISSUE TITLE
TS build error in loader-utils

### ISSUE THREAD

**Issue by Radik24** [visgl/loaders.gl#2372]
Hi,

I just updated to 3.3.1 but I can't build my project.

![image](https://user-images.githubusercontent.com/23722745/221130687-e1d36f4c-fd90-469a-8642-b4441e76fd70.png)

I have "skipLibCheck": true, but it's only for d.t files.

I'm not sure why ts is checking something in node_modules. Do you have any ideas what can I do?

Thanks

**Comment by Radik24** [comment]
I think it's similar to https://github.com/visgl/loaders.gl/issues/1828#issue-988868913

'3.2.13' worked fine

**Comment by ibgreen** [comment]
@Radik24 The migration to typescript has been a long process and there have been big improvements done since 3.1. 

If you absolutely cannot upgrade, these 8 issues don't look very hard to fix, maybe you could make a PR on the 3.1-release branch?

**Comment by Radik24** [comment]
Yes! I'll try over the weekend.

**Comment by belom88** [comment]
v3.3.3 has been published
