### ISSUE TITLE
[Bug] loadOptions issue for WMS Loader

### ISSUE THREAD

**Issue by brandonjpierce** [visgl/loaders.gl#2382]
[deck.gl ticket reference](https://github.com/visgl/deck.gl/issues/7747)

### Description

Context:

Trying to reach out to a WMS endpoint that has basic access authentication (meaning we need to pass `Authorization` header).

Given:

```
new WMSLayer({
  ...otherOptions,
  loadOptions: {
    fetch: {
      headers: {
        Authorization: 'Basic <hash>',
      },
    },
  },
}),
```

This does not attach additional headers to the WMS request:

![Screenshot 2023-03-13 at 11 30 50 AM](https://user-images.githubusercontent.com/5483779/224749717-20216642-486b-4e05-b010-d906981d5cd6.png)

### Expected Behavior

Expectation would be that we could see the `Authorization` header in dev tools for the request.

**Comment by ibgreen** [comment]
Published in 3.4.0
