### ISSUE TITLE
getFeatureInfo not working correctly in WMSService

### ISSUE THREAD

**Issue by markendos** [visgl/loaders.gl#2426]
When trying to fetch features from a WMS service using the `getFeatureInfo` method with param `info_format: 'application/vnd.ogc.gml'`, the xml returned by the server is not parsed correctly by the `parseWMSFeatureInfo` method.

WMS server response:
```xml
<?xml version="1.0" encoding="UTF-8"?><wfs:FeatureCollection xmlns="http://www.opengis.net/wfs" xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:pontevedra="pontevedra" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wfs http://geoserver.fiwoo.local/geoserver/schemas/wfs/1.0.0/WFS-basic.xsd pontevedra http://geoserver.fiwoo.local/geoserver/pontevedra/wfs?service=WFS&amp;version=1.0.0&amp;request=DescribeFeatureType&amp;typeName=pontevedra%3Acity_visitors_layer"><gml:boundedBy><gml:null>unknown</gml:null></gml:boundedBy><gml:featureMember><pontevedra:city_visitors_layer fid="city_visitors_layer.fid-6f484b88_187a28ec8f4_-593"><pontevedra:area_id>751</pontevedra:area_id><pontevedra:wkb_geometry><gml:MultiPolygon srsName="http://www.opengis.net/gml/srs/epsg.xml#4326"><gml:polygonMember><gml:Polygon srsName="EPSG:4326"><gml:outerBoundaryIs><gml:LinearRing><gml:coordinates xmlns:gml="http://www.opengis.net/gml" decimal="." cs="," ts=" ">-8.5137,42.4237 -8.5198,42.4042 -8.5152,42.3996 -8.5207,42.3946 -8.5274,42.3929 -8.5338,42.3881 -8.542,42.3908 -8.5441,42.3967 -8.5477,42.3992 -8.5499,42.4034 -8.5657,42.4033 -8.581,42.3937 -8.5846,42.3948 -8.5901,42.3992 -8.5868,42.4026 -8.5824,42.4124 -8.5669,42.421 -8.56,42.4229 -8.5555,42.4304 -8.539,42.4283 -8.5332,42.4301 -8.5214,42.4239 -8.5137,42.4237 -8.5137,42.4237</gml:coordinates></gml:LinearRing></gml:outerBoundaryIs></gml:Polygon></gml:polygonMember></gml:MultiPolygon></pontevedra:wkb_geometry><pontevedra:parent_id>34123636043</pontevedra:parent_id><pontevedra:srid>4326</pontevedra:srid><pontevedra:name>3604303002</pontevedra:name><pontevedra:type>2_1</pontevedra:type><pontevedra:delivery_id>dippontevedra_202201</pontevedra:delivery_id><pontevedra:dst_id>3604303002</pontevedra:dst_id><pontevedra:terrunit_dst>1</pontevedra:terrunit_dst><pontevedra:filter>7-Morning</pontevedra:filter><pontevedra:variable_label>nvisitors_overnightstays_distribution_8_15</pontevedra:variable_label><pontevedra:variable_value>2.1603</pontevedra:variable_value></pontevedra:city_visitors_layer></gml:featureMember></wfs:FeatureCollection>
```

Value returned by `getFeatureInfo` method:
```json
{
    "features": []
}
```

Responsible code is commented with ToDo:
![image](https://user-images.githubusercontent.com/57869508/233620488-d319e4d7-4051-43ad-8bc3-dced9c3e429f.png)

Also, it would be a good addition to add `application/json` as a supported value for the `info_format` parameter.

**Comment by ibgreen** [comment]
Thanks for reporting. Yes your observations are correct. 

If you looked in the source code, you will also a find the beginnings of a [GMLLoader](https://github.com/visgl/loaders.gl/blob/master/modules/wms/src/lib/parsers/gml/parse-gml.ts) which is not quite ready but will eventually be used to parse GML format data including these responses.

While we definitely want to address this, I can't promise a date for these improvements. As you have probably noticed, the `_WMSFeatureInfoLoader` is exported with underscore and not documented, meaning that it is still a work in progress. The OGC standards support in loaders.gl and deck.gl is being developed by Foursquare for the Studio product, so what you get is just the current state of ongoing open development.

PRs are always welcome. If you just wanted to add a couple of MIME types to the `info_format` prop type, that would almost certainly be accepted.

**Comment by ibgreen** [comment]
This should be available from loaders.gl 4.0.0-beta.3 onwards. If this is wanted in 3.4, a new "cherry-pick" PR must be opened against the `3.4-release` branch.
