### ISSUE TITLE
Shapefile: `MultiPatch` geometry support

### ISSUE THREAD

**Issue by vojtatom** [visgl/loaders.gl#2440]
Hello, I am trying to parse a shape file containing only `MultiPatch` geometry (per [Esri Spec FIle](https://www.esri.com/content/dam/esrisites/sitecore-archive/Files/Pdfs/library/whitepapers/pdfs/shapefile.pdf) Geometry type 31), however the parser returns an empty `data` field.  I haven't found the data type [in the code](https://github.com/visgl/loaders.gl/blob/c8141f1caf90bf7cfccd5ee021e3b363ed52ae5b/modules/shapefile/src/lib/parsers/parse-shp-geometry.ts#L13), so I assume it hasn't been implemented. Do you plan on adding the support for this geometry type?

**Comment by ibgreen** [comment]
Thanks for reporting. It would certainly be nice to add this, however there is no contributor working on the Shapefile loader at the moment. PRs are of course welcome. 

Perhaps the minimal step would be to make sure the limitation is documented?

**Comment by ibgreen** [comment]
At the moment loaders.gl only supports the geojson subset (multi) polygon, line, point and collection for all geospatial loaders.. No support for exotic geometry types at this time.

**Comment by vojtatom** [comment]
In case anyone bumps into this issue, I [made this other package](https://github.com/vojtatom/shp.ts) that handles Shapefiles with 3D geometry and MultiPatch. It supports converting MultiPatch to GeoJSON's 3D MultiPolygon as best as possible.

**Comment by ibgreen** [comment]
@vojtatom Wow, you really went all the way! That is easily the nicest and cleanest open source JS shapefile parser out there. Wish it had been around when we wrote the loaders.gl Shapefile parser, would have used or forked this one. 

One difference compared with loaders.gl seems to be that `shp.ts` doesn't handle streaming reads (or did I miss that part)?

FWIW - We might actually consider copying in your multipatch support into loaders.gl at some point, now that you have shown that it can be implemented straightforwardly and in terms of generating known geometries, it doesn't look so bad.

**Comment by vojtatom** [comment]
@ibgreen Thank you, I think I could help with the implementation since I'm using `loaders.gl` anyway, it would be nice to have it all in one package.

Streaming reads are not supported, but since the parser reads the file sequentially without jumping around, I think adding streams will be pretty straight-forward.

Another issue I bumped into was https://github.com/vojtatom/shp.ts/issues/4 `.dbf` encoding-related - I didn't want to include full `iconv-lite` for decoding since making it work in the browser wasn't that straightforward, but reading `.dbf` with basic encodings still works well with basic `TextDecoder`.

**Comment by ibgreen** [comment]
>  I think I could help with the implementation since I'm using loaders.gl anyway, it would be nice to have it all in one package.

@vojtatom That would be great. I just sent you an invite to the repo. If you get serious about contributing to loaders.gl you can find me on the OpenJS foundation slack: https://www.openvisualization.org/#get-involved, and we could also set up a call.

>  I didn't want to include full iconv-lite for decoding since making it work in the browser wasn't that straightforward, but reading .dbf with basic encodings still works well with basic TextDecoder.

Yes, I came to the same conclusion, it would require a lot of work (and additional bundle size) to support this. 

Fortunately it appears to be a rare issue. We have been using the ShapefileLoader in our Foursquare Studio product for a long time and we have never had a request for supporting more encodings. But I suppose in some geographies it could become a big issue.

**Comment by vojtatom** [comment]
> @vojtatom That would be great. I just sent you an invite to the repo. If you get serious about contributing to loaders.gl you can find me on the OpenJS foundation slack: https://www.openvisualization.org/#get-involved, and we could also set up a call.

@ibgreen thanks, I'm in, I'll go through the code and check out the https://github.com/visgl/loaders.gl/pull/2752 when I get a chance. I'll let you know if I have any questions.
