### ISSUE TITLE
Incorrect GPU memory usage calculation for GLTF 3D tiles 

### ISSUE THREAD

**Issue by felixpalmer** [visgl/loaders.gl#2457]
Tileset3D computes the GPU memory being used by summing the `tile.content.byteLength`:

https://github.com/visgl/loaders.gl/blob/master/modules/tiles/src/tileset/tileset-3d.ts#L874

For tiles with `type: scenegraph` the byteLength is missing and thus these tiles are assumed to be 0 bytes. 

As the application loads more tiles, the total memory use of the tileset, `tileset3d.gpuMemoryUsageInBytes`, remains at 0 and thus no tiles are unloaded. This causes the memory to grow without bounds and on mobile devices the page is killed by the browser within 10 seconds as the user moves around.

**Comment by ibgreen** [comment]
Fixed in 3.3.5
