### ISSUE TITLE
update flatgeobuf dependency

### ISSUE THREAD

**Issue by amarant** [visgl/loaders.gl#2459]
Hi,
would it be possible to update the flatgeobuf dependency from 3.6.5 to the [last one at this time](https://www.npmjs.com/package/flatgeobuf) and at least 3.20.0+, because the current one doesn't support [heterogeneous geometry types](https://github.com/flatgeobuf/flatgeobuf/pull/159) and returns unknown geometry type so silently error out with loader.gl.

Thanks.

**Comment by ibgreen** [comment]
@amarant that would be great, the old version has many issues. Unfortunately there is a huge complication in that flatgeobuf moved to ES modules after the currently used version which are not compatible with non-ES module modules.

The goal is for loaders.gl to move to ES modules in the upcoming 4.0 release and then we'll make sure to upgrade to very latest flatgeobuf assuming there are no other major surprises.

It may take 2-3 month before 4.0 is ready to release.

**Comment by ibgreen** [comment]
An update to latest flatgeobuf landed in #2684 and will soon be available in 4.0-beta releases. 

I am a little concerned that it will only work for modern ES module compatible apps, as the author requires us to access the mjs build directly, but for now that is the best I can do with limited time.
