### ISSUE TITLE
loaders.gl in Angular 15 typescript

### ISSUE THREAD

**Issue by qi-326** [visgl/loaders.gl#2465]
https://github.com/visgl/loaders.gl/blob/3aaf994e53c4050eaa4177bc5525ad34c9372083/modules/loader-utils/src/lib/node/fs.ts#L2

loaders.gl doesn't compile in Angular 15. There seems to be a typing issue for this line ('import fs from 'fs';'). Can you investigate?

Error: node_modules/@loaders.gl/loader-utils/dist/lib/node/fs.d.ts:1:8 - error TS1192: Module '"fs"' has no default export.
1 import fs from 'fs';

![image](https://github.com/visgl/loaders.gl/assets/133215099/61831788-73a2-4c3b-89b1-a122ac109596)

**Comment by ianjoneill** [comment]
I think the solution to this is similar to as described here: https://github.com/visgl/loaders.gl/pull/1741#issuecomment-893487031

**Comment by qi-326** [comment]
Found another temp solution in a similar issue - "can enable skipLibCheck in tsconfig to ignore this issue"

**Comment by ibgreen** [comment]
fs imports have been moved to `@loaders.gl/polyfills` in 4.0
