### ISSUE TITLE
Minimal example glTF + luma.gl

### ISSUE THREAD

**Issue by korywka** [visgl/loaders.gl#248]
You already have one example for glTF loader: https://loaders.gl/examples/gltf

But it is hard to understand for entry level. I believe a lot of code here because of select boxes.

Examples for feature - only are better for documentation: https://threejs.org/docs/index.html#examples/loaders/GLTFLoader

If you expect that your library will use only experienced developers in webgl, you can close this issue unresolved.

**Comment by ibgreen** [comment]
@bravecow Thanks for the feedback. I agree that the example is too complicated. 

As a first step, we could break out the option panel handling into a separate file, which we have done in the other examples.

**Comment by bravecow** [comment]
If there will be some GLTF Loader + luma example (or mapbox) something like this one: https://docs.mapbox.com/mapbox-gl-js/example/add-3d-model/ please, ping me. I want to try to switch to luma from three.js.

**Comment by ibgreen** [comment]
@bravecow I opened a PR on a deck.gl example (which uses luma.gl internally) which is much simpler. #416 

I did one round of cleanup on the luma.gl example, but we may still need an RFC on glTF API simplifications in luma.gl, perhaps from @tsherif and @georgios-uber to enable the next round of simplifications.
