### ISSUE TITLE
Google 3D Tiles: "Request contains an invalid argument"

### ISSUE THREAD

**Issue by RELNO** [visgl/loaders.gl#2488]
**issue**: 
- I'm testing the new 3d tiles API as as described here https://developers.google.com/maps/documentation/tile/use-renderer#deckgl_renderer_examples

- when using deck's Tile3DLayer with the new google 3d tiles API, requests for further tiles (json/glb) fail with code 400
<img width="412" alt="Screenshot 2023-05-18 at 4 24 48 PM" src="https://github.com/visgl/loaders.gl/assets/14296774/e1a5d609-c8d5-43e4-bc33-710d7aa7902d">

The inspector shows a request **that fails to include the API** key after the session.
`https://tile.googleapis.com/v1/3dtiles/datasets/CgA/files/UlRPVEYubm9kZWRhdGEucGxhbmV0b2lkPWVhcnRoLG5vZGVfZGF0YV9lcG9jaD05NDYscGF0aD0wMyxjYWNoZV92ZXJzaW9uPTYsaW1hZ2VyeV9lcG9jaD05NjY.glb??session=CK_blahBlah`

the URL in the image below might be the issue:
<img width="200" alt="Screenshot 2023-05-18 at 4 37 09 PM" src="https://github.com/visgl/loaders.gl/assets/14296774/c2baa075-a0c4-40f3-bac5-94b595618d65">

**possible fix**: 
change the loader code so that the `key` is carried with each request, similar to how `session` is. Note the format of the request  [described here](https://developers.google.com/maps/documentation/tile/create-renderer#requests-and-responses) i.e:

`https://tile.googleapis.com/v1/3dtiles/datasets/CgA/files/UlRPVEYubm9k.glb?session=CIqhrPOFvdHSYg&key=YOUR_API_KEY`

**Comment by ibgreen** [comment]
Fixed in 3.4.3
