### ISSUE TITLE
tile-converter not working

### ISSUE THREAD

**Issue by landajaromir** [visgl/loaders.gl#2531]
Hi, 
I am trying to use the tile-converter to convert i3s service to 3D Tiles. So far I have managed to only convert very simple scene without any textures. Even services mentioned in examples cannot be converted. For example:

npx tile-converter --input-type I3S --tileset "https://tiles.arcgis.com/tiles/z2tnIkrLQ2BRzr6P/arcgis/rest/services/Admin_Building_v17/SceneServer/layers/0" --name TEST 
will produce Error: 3D Tile: boundingVolume must contain a sphere, region, or box

or 
npx tile-converter --input-type I3S --tileset https://tiles.arcgis.com/tiles/z2tnIkrLQ2BRzr6P/arcgis/rest/services/SanFrancisco_3DObjects_1_7/SceneServer/layers/0 --name TEST 
will produce Error: Cannot read properties of null (reading 'dispatcher') which is very common for almost all services i tried to create in ArcGIS Pro. 

I have no idea what I should change or how the service must be create to work.

**Comment by belom88** [comment]
Could you provide us more details regarding your environment (OS, NodeJS version) and steps to reproduce (because there are many ways to run the tile-converter).
FYI, at the moment tile-converte doesn't support NodeJS >=18. 
These steps work for me (Ubuntu 22.04.2, NodeJS 16):
```bash
~$ mkdir tmp
~$ cd tmp
~/tmp$ npm install @loaders.gl/tile-converter
~/tmp$ npx tile-converter --install-dependencies
~/tmp$ npx tile-converter --input-type I3S --tileset https://tiles.arcgis.com/tiles/z2tnIkrLQ2BRzr6P/arcgis/rest/services/SanFrancisco_3DObjects_1_7/SceneServer/layers/0 --name SF --max-depth 2
```

**Comment by landajaromir** [comment]
There is no message. The problem was the Node.js version. It works with a Node.js 16. Thank you
