### ISSUE TITLE
wrong import in wms service

### ISSUE THREAD

**Issue by Hiller** [visgl/loaders.gl#2615]
wms.service.d.ts contains wrong import 
parse: typeof import("modules/images/src/lib/parsers/parse-image").default;
this is causing compilation error.
package version 3.4.13

**Comment by ibgreen** [comment]
@Hiller thanks for reporting.

Took a look in the source code, couldn't find anything obvious. This doesn't seem to affect all users. 

Put up a PR addressing some findings, but likely unrelated.

Will be on the lookout for more information about this issue.

PS - Might be worth doing a clean install to make sure it is not just a messed up installation?

**Comment by Hiller** [comment]
https://www.npmjs.com/package/@loaders.gl/wms?activeTab=code
@loaders.gl/wms/dist/lib/services/ogc/wms-service.d.ts line 231
it's here.

**Comment by ibgreen** [comment]
@Hiller thanks that is helpful. PR updated.

**Comment by ibgreen** [comment]
The fixes went into 3.4.14.
