### ISSUE TITLE
3D Tiles: GLTF postProcess = false causes crash

### ISSUE THREAD

**Issue by sweco-sefure** [visgl/loaders.gl#2688]
Hi,

Loading 3D Tiles with GLTF post-processing turned off causes a crash on this line:

https://github.com/visgl/loaders.gl/blob/c2833462d3d0ec42e540de3682475813ac2ac380/modules/gltf/src/lib/gltf-utils/gltf-utils.ts#L144C16-L144C16

![image](https://github.com/visgl/loaders.gl/assets/14555367/579e9e22-1aea-4c9c-8704-1c14762ae9f6)

When post-processing is turned off the width and height should be extracted from image, not image.image.

Could this be a bug or is postProcess = false not supported in the 3D Tiles loader?

**Comment by ibgreen** [comment]
Yes it could be a bug, which would surely be an easy to fix if we had a quicj reproduction case. With the info in this report we would need to start testing different tilesets until we hit the bug, which I don't expect maintainers have time to do.

Also we are putting the final touches on loaders.gl 4.0, in which glTF post processing is no longer done by the glTF loader, and instead performed separately after loading. This makes me suspect this bug would likely not exist in the new version (though it is of course possible).

**Comment by sweco-sefure** [comment]
This was solved in loaders.gl 4.0.
