### ISSUE TITLE
Issue - Unable to Extract "glTF" in parse3DTile Method

### ISSUE THREAD

**Issue by IDONKN** [visgl/loaders.gl#2716]
I am currently trying to load a glTF using the 3DTILES_content_gltf extension, along with the corresponding tilesjson file. However, I am encountering an error in the parse3DTile method where tile.type = getMagicString fails to extract "glTF" correctly.

I would appreciate it if someone could provide an example of loading the glTF content extension 3DTILES_content_gltf extension, along with the tilesjson file. Additionally, I need assistance in resolving the error I'm facing while extracting "glTF" in the parse3DTile method.

Thank you for your help!

<img width="839" alt="b1efe00a5ce55c7110de871d5add183" src="https://github.com/visgl/loaders.gl/assets/25627076/c03ab91e-0183-48c1-9c27-6b6f39ea60a3">
<img width="896" alt="206586892a4d5443b27fcda7e6f89ac" src="https://github.com/visgl/loaders.gl/assets/25627076/bb1c0a61-c900-45db-8fd7-c8a17497eaa4">

**Comment by ibgreen** [comment]
My understanding is that when using `3DTILES_content_gltf`, the tiles **are** gltf/glb (i..e there is no longer any embedded  gltf in the tile).

@belom88 I believe this format is handled by the tile-converter and should be well supported.

**Comment by IDONKN** [comment]
Thank you for your help~
