### ISSUE TITLE
[Bug] deck.gl website can't import luma constants in loaders.gl

### ISSUE THREAD

**Issue by chrisgervang** [visgl/loaders.gl#2725]
I was testing loaders.gl v4 beta.5 on deck.gl's website and came across errors during the build pointing to:
https://github.com/visgl/loaders.gl/blob/a25f026ffef00acb8033ce7f9853736b1644583f/modules/i3s/src/lib/parsers/constants.ts#L1

Luma v9 doesn't export GL constants as the default export, so it throws `export 'default' (imported as 'GL') was not found in '@luma.gl/constants' (possible exports: GL)`

Should it be `import {GL} from '@luma.gl/constants'`?

Repro:
1. `master` branch on deck.gl
2. `yarn bootstrap && cd website && yarn && yarn start`

**Comment by ibgreen** [comment]
Good catch. loaders.gl should not depend on luma.gl. 

The layers in the architecture are as follows, so loaders can import math and probe, but not luma or deck.

deck.gl < luma.gl < loaders.gl < math.gl / probe.gl
