### ISSUE TITLE
ParquetLoader: compression-worker.js has no exports

### ISSUE THREAD

**Issue by m-mohr** [visgl/loaders.gl#2732]
I'm trying to load a GeoParquet file using the loaders.gl 4.0.0-beta.7:

```
import {ParquetLoader} from '@loaders.gl/parquet';
import {load} from '@loaders.gl/core';
// ...
const parquet = await load(geoparquet.href, ParquetLoader, {
  worker: false,
  parquet: {
    shape: 'geojson-table',
    preserveBinary: true,
  },
});
```

Unfortunately, I'm getting:

> ERROR in ../node_modules/@loaders.gl/compression/dist/index.js 10:0-78
> export 'CompressionWorker' (reexported as 'CompressionWorker') was not found in './compression-worker.js' (module has no exports)
> ERROR in ../node_modules/@loaders.gl/compression/dist/index.js 10:0-78
> export 'compressOnWorker' (reexported as 'compressOnWorker') was not found in './compression-worker.js' (module has no exports)

I'm building with webpack 5.88.2.

**Comment by m-mohr** [comment]
Meh, must be something in the environment. A pure webpack example works...

**Comment by m-mohr** [comment]
So I've tried it in the webpack-5 example that is in this repo and it works if I run it as a TS project, but in a JS project (so I removed the tsconfig and renamed index.ts to index.js) I get the same issue as reported above. I assume loaders.gl is meant to also work with JS projects and not just TS?

**Comment by belom88** [comment]
As a temporary solution, I've added 
```
parser: {
      javascript: {
        exportsPresence: "warn",
      },
    },
```
to the `webpack.config` in "I3S Explorer". See https://github.com/visgl/loaders.gl-showcases/blob/master/webpack.prod.config.js#L11

**Comment by ibgreen** [comment]
I am hoping changes in this PR will fix it: https://github.com/visgl/loaders.gl/pull/2730. 

I think the root cause was a an output file was being clobbered in the new build tooling setup so I renamed it. 

Let's test again when beta.8 comes out, hopefully later today.

**Comment by m-mohr** [comment]
It did, thanks a lot!
