### ISSUE TITLE
 package "@loaders.gl/3d-tiles" "peerDependencies" version error

### ISSUE THREAD

**Issue by aliothor** [visgl/loaders.gl#2754]
![image](https://github.com/visgl/loaders.gl/assets/60435548/ddd3a569-5a4a-47ab-b536-300b42c309a6)

**Comment by ibgreen** [comment]
@aliothor thanks for reportin, (and for trying out our new 4.0 version. 

- PR up, scheduled for 4.0.2 patch (I expect it to publish sometimes this week).

**Comment by aliothor** [comment]
@ibgreen thank you for your reply.
