### ISSUE TITLE
3D Tiles Implicit Tilesets with multiple subtrees not loading

### ISSUE THREAD

**Issue by Kaapp** [visgl/loaders.gl#2820]
Hi,

We're leaning into generating and supporting implicit tilesets at Sensat and encountered some issues loading v1.1 implicit tilesets, particularly those that had multiple subtrees (such as [this one from Cesium themselves](https://github.com/CesiumGS/3d-tiles-samples/tree/main/1.1/SparseImplicitOctree)). 

After a little hunting, I found three small bugs and an issue with the test file which I've raised a PR for in our own fork to unblock our work but we'd quite like to upstream these fixes for everyone to make use of:
- A pass-by-ref bug in the recursive parsing algorithm which would lead to calculating tile and morton indices incorrectly once we reached the maximum depth of the tree and attempted to evaluate a second subtree
- Shifting the global tile coordinate values too far leading to requesting the wrong tile content URIs
- Requests being made for content in tiles which had no `contentAvailability`
- `contentAvailability` in the test tileset which did not match the content structure beyond the first few levels, so I've replaced it with Cesium's demo file and increased the depth of the test to query subtrees (i believe Cesium's test file is under the same Apache 2.0 licence based on their [contributor licence agreement](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md))

I'd be happy to raise a PR from my [original branch](https://github.com/sensat/loaders.gl/pull/5) in our repo if the team would be happy for us to upstream these (with any needed review feedback), or can split things up if you prefer to isolate the changes 🙏 

Thanks,
Chris

**Comment by ibgreen** [comment]
@Kaapp Hi, good to hear from you. Yes I think we would very much appreciate this PR. 

I can't say a priori if separate PRs are needed, so if it is a lot of extra work then maybe just start with a single PR.

If there are structural code changes (renaming, moving lines, etc) that don't include functional changes it is often nice to start with a PR that gets those changes out of the way so the following PRs are small and easy to review.

Test cases, generous TSDoc comment and where appropriate, markdown docs are also appreciated.

If you join our [OpenJS slack](https://www.openvisualization.org/#get-involved) I'll add you to the 3D Working Group channel where reviewers can discuss offline as well.

**Comment by ibgreen** [comment]
@belom88 FYI
