### ISSUE TITLE
@loaders.gl/tile-converter Failed to execute yarn bootstrap

### ISSUE THREAD

**Issue by Brave-Jun** [visgl/loaders.gl#2916]
Hi everyone!

I am getting error after executing yarn bootstrap in cmd:

$ echo postinstall
postinstall
Incorrect file name, directory name, or volume label syntax.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

I'm using node version v20.5.1 and yarn version 1.22.19. I followed this procedure: https://loaders.gl/docs/modules/tile-converter/api-reference/build-instructions

Any suggestions for troubleshooting, thanks!

**Comment by belom88** [comment]
Hi, @Brave-Jun !

Which OS do you use?
loaders.gl don't build on Windows.

**Comment by Brave-Jun** [comment]
> Hi, @Brave-Jun !
> 
> Which OS do you use? loaders.gl don't build on Windows.

Hi @belom88 

Thank you for your reply. The OS I am using is windows 10. I have since abandoned this option and installed tile-converter directly using the command npm i @loaders.gl/tile-converter.
