### ISSUE TITLE
Parse svg image error: Failed to execute 'btoa' on SVG with Chinese characters

### ISSUE THREAD

**Issue by ForeverArt** [visgl/loaders.gl#294]
When .svg files contain, for example chinese characters, [parse-image.js](https://github.com/uber-web/loaders.gl/blob/master/modules/images/src/lib/parse-image.js) throws error: `Uncaught (in promise) DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.`

Using `btoa(unescape(encodeURLComponent(xml)))` instead of `btoa(xml)` could solve this problem to make `parse-image.js` more robust.

**Comment by ibgreen** [comment]
Finally got around to looking at this and confirming:

- `btoa` is known to not support extended characters https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/btoa
- An easy, but "expensive" solution is the one proposed by the issue reporter.
- An ArrayBuffer based solution would perform best and fit best with loaders.gl design. MDN recommends create a `UTF8toBase64` function using the `base64-js` lib: https://github.com/beatgammit/base64-js/blob/master/index.js.
- But this looks like slightly too much code to include in loaders.gl to handle a corner case. Unless we find more uses the first option seems preferable...

To get working on on either solution, we would first need a test SVG file that replicates the problem, with e.g. Chinese characters.

**Comment by ibgreen** [comment]
@xintongxia I think this may be fixed with the last round of changes to the SVG image loading. We'd need an example of an SVG with Chinese characters to confirm, is that something you might be able to add?
