### ISSUE TITLE
Basis File Examples

### ISSUE THREAD

**Issue by matthewfdaniels** [visgl/loaders.gl#2968]
Hi there, I'm having some issues with getting the Basis Loader to work, with the error `[.WebGL-0x11406e67a00] GL_INVALID_OPERATION: Texture format does not support mipmap generation.` I have tried using .basis files without a mipmap, resulting in the same error

I couldn't find any examples on how the loaded basis file is used in deck.gl layers. Perhaps there's a missing step to process the texture for use in deckgl layers?

```
import {BasisLoader} from '@loaders.gl/textures';
import {load} from '@loaders.gl/core';
import {Deck, OrthographicView, COORDINATE_SYSTEM} from '@deck.gl/core';
import {IconLayer, BitmapLayer} from '@deck.gl/layers';

const loadOptions = {basis: {}};

const result = await load('assets/test5.basis', BasisLoader, loadOptions);
const image = result[0][0];

deckgl = new Deck({
	views: new OrthographicView(),
	initialViewState: { target: [0, 0, 0], zoom: 5 },
	controller: true,
	layers: [
		new BitmapLayer({
			//data: null,
			image: image,
			id: `_bitmap`,
			bounds: [0,5,5,0]//[0,5,5,0]
		})
	]
})
```

I also tried using a loader, with the same error of `does not support mipmap generation`

```
new BitmapLayer({
	//data: null,
	image: 'assets/test5.basis',
	loaders: [BasisLoader],
	id: `_bitmap`,
	bounds: [0,5,5,0]//[0,5,5,0]
}),
```

Any examples would be really helpful!

**Comment by ibgreen** [comment]
Just a quick thought... Assuming that you are using deck.gl v9, there has been a lot of changes to the luma.gl v9 texture class, and it is quite possible that the BitmapLayer when creating Textures from the compressed texture data, that mipmap generation gets triggered. (For compressed textures, the various mipmap levels are typically present in the compressed texture container and they should be copied into the texture mip levels.) 

So yes, it could very well be a regression / bug.

**Comment by matthewfdaniels** [comment]
Yea here's what I was on:
```
		"@deck.gl/core": "^9.0.1",
		"@deck.gl/geo-layers": "^9.0.3",
		"@deck.gl/layers": "^9.0.1",
		"@loaders.gl/core": "^4.2.0",
		"@loaders.gl/textures": "^4.2.0"
```

Might you have any recommendations on what versions I should try to see if this is a regression bug?

**Comment by ibgreen** [comment]
It would have regressed from v8.9 (which uses luma.gl v8.5 and loaders.gl v3.4). 

You can try and see if it is easy to do. But perhaps reverting a entire major version is too much work.

**Comment by matthewfdaniels** [comment]
Ok I just changed versions to deck.gl/core 8.0.17, which runs on luma.gl/core 8.5.21 (I cannot get npm to run a lower version on Luma, which installing deck.gl/core). This is also using loaders.gl/2.0.2.

I still get the same mipmap error.

There is one more error that I neglected to mention:
`texImage2D: no bound PIXEL_UNPACK_BUFFER` —perhaps that's another clue?

Here's also the console log the basis file, once it's loaded using `BasisLoader`:
<img width="752" alt="image" src="https://github.com/visgl/loaders.gl/assets/2880174/75ecd40f-59ea-4a00-b19a-6efa9635a08e">

As in the example in the @loaders.gl repo, I am only passing the first item in the array, which would be:
```
		const loadOptions = {basis: {}};
		const result = await load('assets/test.basis', BasisLoader, loadOptions);
		const imageBasis = result[0][0];
```
My hunch is that I'm doing something wrong when attempting to load it in a DeckGL layer. Does `imageBasis`  need to be processed any further before it's assigned as the `image` parameter of the BitmapLayer, as defined here? https://deck.gl/docs/api-reference/layers/bitmap-layer#image

**Comment by ibgreen** [comment]
@belom88 who integrated basis support in the Tile3DLayer

**Comment by matthewfdaniels** [comment]
hi @belom88 might you have any reactions to this error that deck.gl is producing?

**Comment by matthewfdaniels** [comment]
I believe that I got this working correctly. Here was my solution: 

`		let options = {
			'basis': {
				format: "astc-4x4"
			},
			'compressed-texture': {useBasis: true}
		}
		const result = await load('https://archaeologyart.soot.com/atlases/atlases/atlas.thumbnails128.0.mipmap.basis', BasisLoader, options);
		const image = result[0];
		let texture = {
			data: image,
			compressed: true,
			mipmaps: false,
    	}

		deckgl = new Deck({
			parent: el,
			views: new OrthographicView(),
		    initialViewState: { target: [100, 100, 0], zoom: 2 },
			// onViewStateChange: ({viewState}) => {
			// 	let width = 1422;
			// 	let height = 905;
			// 	const view = new OrthographicView(viewState.main);
			// 	let viewport = view.makeViewport({width, height, viewState})
			// 	bounds = viewport.getBounds();
			// 	zoom = viewport.zoom;
  			// },
			controller: true,
			layers: //layers
			[
				new BitmapLayer({
					image: texture,
					id: `_bitmap`,
					bounds: [50,100,100,50]//[0,5,5,0]
				}),`
