### ISSUE TITLE
error in loading laz file using LASLoader

### ISSUE THREAD

**Issue by vishwadeepakp** [visgl/loaders.gl#2979]
Failed to open file: undefined
    at onMessage (parse-with-worker.ts:87:1)
    at workerThread.onMessage (worker-pool.ts:148:1)
    at worker.onmessage (worker-thread.ts:111:1) 
    
I am trying to parse a Laz file, and I am facing issues.

I used to call the code below many times, and it was working fine. However, after some time, maybe around the 100th time, this error occurred. @ibgreen and @zarov or anyone,   Any suggestions?

    
        let loaderOptions = {
        las: { colorDepth: "auto", fp64: true },
      };
      const filePath = `${s3path}//${name}`;

      console.log("filePath", filePath, loaderOptions);
      const loadedData = await load(filePath, LASLoader, loaderOptions);
    
    
    I want to add some more information: my file path is perfectly fine.

**Comment by ibgreen** [comment]
Not much info here, no error message, rather vague repro. 

Is the same application trying to open 100 LAS files during one session, and it fails after ~100 LAS files? Maybe an out-of-memory condition in the worker?

You should be able to set `options.reuseWorkers: false` to make sure you get a fresh worker every time.

**Comment by vishwadeepakp** [comment]
I use to call many LAS files of size approximately 600KB and render them on the browser  one by one.

I use LASLoader to read LAS files, which works fine initially. However, after calling many files, it gives me an error:

**Uncaught (in promise) Error: Failed to read data: undefined
    at onMessage (parse-with-worker.ts:87:1)
    at workerThread.onMessage (worker-pool.ts:148:1)
    at worker.onmessage (worker-thread.ts:111:1)**
    
    
This error occurs even when calling the same file, which was working fine before.

Below is our code to read the LAS file:

**let loaderOptions = {
    las: { colorDepth: "auto", fp64: true, reuseWorkers: false },
};
const filePath = `${s3path}/${name}`;
console.log("filePath", filePath, loaderOptions);
const loadedData = await load(filePath, LASLoader, loaderOptions);**



This code works fine for approximately 100 LAS files, but then starts giving errors even for files that were previously working fine.


After adding reuseWorkers: false, the issue still persists.

**Comment by ibgreen** [comment]
Is it possible that your browser is running out of memory? 600KB x 100 = 60MB so it doesn't seem to bad, but perhaps there are memory leaks in the LASLoader. You could track memory in e.g. Chrome Developer tools

Not sure if you are using loaders.gl 4.2, but a big memory leak in the LASLoader was plugged in that release.

**Comment by ibgreen** [comment]
> for files that were previously working fine.

If this is this a regression, can you specify the version of loaders.gl that works, and which version breaks?

**Comment by vishwadeepakp** [comment]
@ibgreen , Thank you for your support. Now it is working fine. Previously, I was using version 3.3, which had a memory leak issue. With version 4.2, it works fine.
