### ISSUE TITLE
[Bug] TypeError: Failed to execute 'text' on 'Response': body stream already read

### ISSUE THREAD

**Issue by davidcalhoun** [visgl/loaders.gl#3025]
We have a setup where unfortunately empty tiles are returned from the server with a HTTP 500 Internal Server Error status code and non-JSON text message, e.g. `Tile 10/229/410 not found in foo` - we're still trying to fix this to instead serve HTTP 204 No Content, but this is a separate issue.  For context, we're using TileLayer in `@deck.gl@9.0.14`

Unfortunately trying to load the empty tiles (with HTTP 500 code and non-JSON text) seems to trigger a bad codepath in `@loaders.gl@4.2.1`:

* Chrome 125.0.6422.114: `Uncaught (in promise) TypeError: Failed to execute 'text' on 'Response': body stream already read`
* Firefox 126.0.1: `Uncaught (in promise) TypeError: Response.text: Body has already been consumed.`

The line that triggers it the `response.text()` [here](https://github.com/visgl/loaders.gl/blob/v4.2.1/modules/core/src/lib/utils/response-utils.ts#L97) (in `core/src/lib/utils/response-utils.ts`):

```tsx
  try {
    const contentType = response.headers.get('Content-Type');
    info.reason = contentType?.includes('application/json')
      ? await response.json()
      : response.text();
  } catch (error) {
    // eslint forbids return in a finally statement, so we just catch here
  }
```

**Comment by ibgreen** [comment]
@davidcalhoun Thanks for reporting, putting up a fix.

It would be good to check response status already in the TileLayer and avoid parsing the Response body there so that we can handle missing tiles correctly and take full advantage of error handling logic in loaders.gl.

So it would be interesting to see the stack trace that leads here if you have - just in case it pinpoints things.

**Comment by ibgreen** [comment]
That is what I was looking for. At first blush, it looks like `parse()` here in loaders.gl doesn't check the response status before trying to read the data.

**Comment by ibgreen** [comment]
Fix landed but unfortunately ran into some publishing issues on 4.2 branch... Apologies, will look again when I have more time

**Comment by davidcalhoun** [comment]
Closing this out.  Thank you @ibgreen for fixing this in https://github.com/visgl/loaders.gl/pull/3026 !
