### ISSUE TITLE
ParquetLoader ERRORS

### ISSUE THREAD

**Issue by aycaramba1224** [visgl/loaders.gl#3041]
### Discussed in https://github.com/visgl/loaders.gl/discussions/3040

<div type='discussions-op-text'>

<sup>Originally posted by **aycaramba1224** June 28, 2024</sup>
![image](https://github.com/visgl/loaders.gl/assets/60164178/f4f1c57e-beac-4c3a-95f9-a5e509b69769)

'https://unpkg.com/@loaders.gl/parquet@4.2.1/dist/parquet-worker.js' is wrong url!
'https://unpkg.com/@loaders.gl/parquet@4.2.1/dist/workers/parquet-worker.js' is correct url! 
</div>

**Comment by Beiusxzw** [comment]
I also encountered this. How should I fix this issue?

**Comment by aycaramba1224** [comment]
I can't fix it.

**Comment by belom88** [comment]
parquet-loader-worker.js is not built because of CommonJS relationships in code.
As a temporary solution you can set `worker: false` option:

```
  const result = load(data, ParquetLoader, {worker: false})
```

**Comment by shaunakv1** [comment]
@belom88
 Performance is taking a serious hit when worker is turned to false for me.   Is there anyway to get a pre-compiled  `parquet-loader-worker.js` temporarily?  Or will this ever be fixed in the code?

**Comment by ibgreen** [comment]
@shaunakv1 

> Performance is taking a serious hit when worker is turned to false for me. 

Hmm, was the JavaScript parquet worker loader ever functional? Even if it was, hard to see how it would be faster.
Or is this just a statement that perf is not a good enough using the default JavaScript based loader?

The path to good performance for Parquet is to use the WASM library via ParquetWASMLoader.  That is where effort is being put for now.

**Comment by ibgreen** [comment]
For repo hygiene reasons, we don't discuss in closed tickets. Please open a GitHub discussion if there is more to discuss.

**Comment by shaunakv1** [comment]
thanks for the response @ibgreen . 

Is there any documentation on ParquetWASMLoader that I can refer to?  I am not seeing it in the list of loaders at

https://loaders.gl/docs/modules/parquet/api-reference/parquet-loader

Also will I still be able to use it with Deck.gl?

**Comment by ibgreen** [comment]
As I said, further conversation in the discussions tab, please.
