### ISSUE TITLE
Add unit tests for select-loader helpers

### ISSUE THREAD

**Issue by xintongxia** [visgl/loaders.gl#574]
https://github.com/uber-web/loaders.gl/pull/570

**Comment by ibgreen** [comment]
One thing to consider that in many cases, the MIME types are not unique for the loaders (many may share `application/json` or `application/octet-stream`.

We might want to consider adding "weights" or "points" to the various mime types in the loader objects to indicate with how much certainty that MIME type identifies that loader. Some MIME types are very unique, but other not so good.
