### ISSUE TITLE
Improve request module for 3D tiles

### ISSUE THREAD

**Issue by jianhuang01** [visgl/loaders.gl#608]
The current request module has a duplicated request issue, although we relieve it with some extra logic for now, in the long term it is better to refactor it.

**Comment by ibgreen** [comment]
Are we talking about the `RequestScheduler` class. I have a roadmap in mind for this class, so if you have bigger changes in mind, maybe we should collaborate on an RFC.

**Comment by ibgreen** [comment]
v2.2.0
