### ISSUE TITLE
Why does the loaders.gl 3dtile module load refined: the replace mechanism does not take effect?

### ISSUE THREAD

**Issue by 472542625** [visgl/loaders.gl#630]
![0073247032620bf4f4ffb47943bd730](https://user-images.githubusercontent.com/22317175/72792227-a1b32800-3c73-11ea-9436-322d40ebfa74.png)

**Comment by xintongxia** [comment]
@472542625 

Could you provide more details? Which version of `loaders.gl` are you using? which dataset? It will be more helpful if you could porovide a [codesandbox](https://codesandbox.io/).
