### ISSUE TITLE
3d-tiles: gaps between tiles

### ISSUE THREAD

**Issue by xintongxia** [visgl/loaders.gl#642]
Repro steps:

1. start application
```
cd examples/deck.gl/3d-tiles
yarn && yarn start-local
```

2. zoom in

<img width="504" alt="Screen Shot 2020-02-05 at 11 33 08 AM" src="https://user-images.githubusercontent.com/2927808/73885483-b3bccb00-481c-11ea-9a7b-ee75d40d9086.png">

**Comment by ibgreen** [comment]
See https://github.com/visgl/deck.gl/issues/4262
