### ISSUE TITLE
Proposal: add a generic preload field for loaders

### ISSUE THREAD

**Issue by xintongxia** [visgl/loaders.gl#676]
**Problem:**

Loading tiles from ion servers required 2 steps authorization, 

1. User provides the tileset's assetId (or assetUrl) and access token

```
response = fetch(asset-url, {accessToken: <access-token>})
```

2. Extract the actual token for fetching tiles from the response in step 1, which will be used for requesting the tileset and the tiles.

However, current generic `load` functions does not work with this kind of auth.

**Proposal:**

Add a `preload` field which can be called by user.

```
Tiles3DLoader: {
  preload: (assetId, accessToken) => {headers},
  parse: arraybuffer => decode(arraybuffer)
}
```
```
import {load} from '@loaders.gl/core';
import {Tiles3DLoader} from '@loaders.gl/3d-tiles';
 
const {headers} = loader.preload(url);

load(url, Tiles3DLoader, {...otherOptions, headers});
```

**Comment by xintongxia** [comment]
@ibgreen @Pessimistress

**Comment by ibgreen** [comment]
@xintongxia Thanks for addressing my concern around the ION tokens.

I understand that `preload` is intended to be an additional function exposed by the `Tile3DLoader`, and will be implemented to hit the `ION` service?

General thoughts
- Your code example calls preload manually. I'd love to be able to use 3D in the playground. How do we pass in layer props to preload using JSON payloads? Are you planning some loaders.gl or deck.gl integration with `preload` as a second step?
- We may want to add `preload` to other loaders. Best to make the "function type" as general as possible. I suggest a function that maps general options object (props) to fetch options `(object) => object`: `({assetId, accessToken}) => {headers: {...}}` (Note {assetId, accessToken} is one options param, not two positional params).


The `Tile3DLoader` implements a generic OGC standard. ION is a commercial Cesium service. Albeit it is likely to remain the most important 3D tiles service, it will presumably (hopefully) not be the only one. It is a little odd to have Cesium specific support for this service built into the Tile3DLoader that other server providers may want to use.

Maybe offering a separate `CesiumIONTile3DLoader` that adds this support would be more appropriate?

```js
CesiumIONTile3DLoader : {
  ...Tile3DLoader,
  preload: ({assetId, accessToken}) => {headers: {...} 
}
```

This design is not perfect as it could still be hard to combine this loader with non-Cesium services if an app wanted to support both, but at least it would keep things a bit more separate for now...

**Comment by xintongxia** [comment]
> I understand that `preload` is intended to be an additional function exposed by the `Tiles3DLoader`, and will be implemented to hit the `ION` service?

Yes.

> General thoughts
> 
> * Your code example calls preload manually. I'd love to be able to use 3D in the playground. How do we pass in layer props to preload using JSON payloads? Are you planning some loaders.gl or deck.gl integration with `preload` as a second step?

User need provide `data`(asset url) and `loadOptions.accessToken`, In `Tile3DLayer`, `Tile3DLoader` will call the auth endpoint and resolve the options which will be passed to `load`.

> * We may want to add `preload` to other loaders. Best to make the "function type" as general as possible. I suggest a function that maps general options object (props) to fetch options `(object) => object`: `({assetId, accessToken}) => {headers: {...}}` (Note {assetId, accessToken} is one options param, not two positional params).

My intention is also on your side to make a generic for other loaders, `(object) => object`, that code example is more specific to `Tile3DLoader` (Or `CesiumIONTile3DLoader`).

**Comment by Pessimistress** [comment]
> Your code example calls preload manually. I'd love to be able to use 3D in the playground. How do we pass in layer props to preload using JSON payloads? Are you planning some loaders.gl or deck.gl integration with preload as a second step?

`preload` will be called by `Tile3DLayer`, hidden from the user.

**Comment by Pessimistress** [comment]
> We may want to add preload to other loaders. Best to make the "function type" as general as possible. 

I suggest using a similar interface as `load` for `preload`:

```js
preload: (url, options) => {...}
```
