### ISSUE TITLE
TerrainLoader performance improvements

### ISSUE THREAD

**Issue by kylebarron** [visgl/loaders.gl#691]
I've been testing out the new `TerrainLoader`, and it's great and exciting to work with. I wanted to bring up two points of discussion for potentially improving performance:

- **Reusing `Martini` instance**. 

	(Edit: I just realized that I had accidentally turned off the web worker, so maybe this is a moot point. I can't tell if a new worker is created on each `load` call, or it looks like it reuses workers in a thread pool?)	

	When profiling, the single largest function call inside `getMartiniTileMesh` is to `Martini` here:
	
	https://github.com/visgl/loaders.gl/blob/a9fe9c6932da580823320f97a0542c30167d194f/modules/terrain/src/lib/parse-terrain.js#L75

	![image](https://user-images.githubusercontent.com/15164633/76692952-8cc79500-6623-11ea-8725-1ba88c229f50.png)

	`new Martini` just sets up the martini instance to later generate the RTIN hierarchy and then extract a mesh. Note that its only argument is the image's `gridSize`/`tileSize`. Assuming that all source tiles have the same number of pixels, it would be faster to do
	
	```js
	const martini = new Martini(gridSize)
	const tile1 = martini.createTile(terrain1)
	const tile2 = martini.createTile(terrain2)
	```

	Since `TerrainLoader` is in its own worker, I'm not sure if it's feasible to reuse `Martini`? Possibly an array of `terrain` data could be provided, to iterate over, but I'd have to think more about how to integrate that with `TileLayer`.

	Edit: It looks like the new `initializeWorkers` could be well suited to this?

- **Gradual mesh refinement**. In the [Martini announcement](https://observablehq.com/@mourner/martin-real-time-rtin-terrain-mesh), it's noted:

	> The algorithm generates a **hierarchy of all approximations** of varying precisions — after running it once, you can quickly retrieve a mesh for any given level of detail.

	I.e. once you finish

	https://github.com/visgl/loaders.gl/blob/a9fe9c6932da580823320f97a0542c30167d194f/modules/terrain/src/lib/parse-terrain.js#L75-L76

	the last step of

	https://github.com/visgl/loaders.gl/blob/a9fe9c6932da580823320f97a0542c30167d194f/modules/terrain/src/lib/parse-terrain.js#L77

	is really fast. So theoretically it could be nice to initially provide a high `meshMaxError`, say 50 meters, to quickly display the rough terrain on the screen, and once all the tiles have loaded, then run `getMesh` with progressively lower `meshMaxError`s for more terrain clarity.

**Comment by ibgreen** [comment]
Close due to inactivity.
