### ISSUE TITLE
Shapefile Loader

### ISSUE THREAD

**Issue by kylebarron** [visgl/loaders.gl#701]
There are obviously a [huge number](https://gdal.org/drivers/vector/index.html) of vector geospatial formats that exist, so I'm curious to hear your criteria on what formats to add, and I'd like to potentially suggest two.

This isn't necessarily top priority for me, but I could be interested in making a PR in the moderate term.

### Shapefile

The Shapefile (`.shp`) format is a historical standard and used for a lot of GIS data interchange. There exists a popular, openly-licensed [JS implementation](https://github.com/mbostock/shapefile) which additionally supports streaming.

Pros:

- Popular geospatial format
- Since a Shapefile is a collection of multiple files and is often zipped, would fit in well with the `ZIPLoader`.

Cons:

- Non-standard projections. Very commonly shapefiles come in arbitrary non-WGS84 projections. So if an `SHPLoader` were implemented we'd have to decide whether to reproject coordinates ourselves (e.g. with [Proj4JS](http://proj4js.org/)) or make it clear to the user what coordinate system the origin data is in.
- Not usually a web format. Often shapefiles would be converted to, e.g. GeoJSON on the backend before use on the web.

### GPX

GPX issue moved to #738

**Comment by ibgreen** [comment]
Given the amount of discussion this is likely to generate, I'd suggest making separate issues for these (Shapefile, KML, GPX)

Some quick thoughts about Shapefile:
- Shapefile support is probably the most highly demanded from users, but considered a big chunk of work. Any contribution here would be **super appreciated**.
- I'm not yet fully "read up" on the format, but at first glance the Shapefile format appears complex. The linked implementation seems partial. There is also a promising open source implementation in the mapshaper repo, not sure which is better.
- Shapefile seems to be a multifile format. To do it right, we may need to build out support in ziploader and recursive file loading in loaders.gl/core.
- Existing Shapefile implementation tend to be based on Node.js streams. loaders.gl is based on AsyncIterators ("push vs pull models" loosely speaking). Making this change could represent extra work.

About KML:
- The current implementation is an absolute hack, no concerns about replacing it.
- KML is richer than GeoJson, can contains images etc. A conversion to GeoJson would be lossy in that it would drop certain types of data. It would be ideal to support both (full KML, and `{kml.geojson: true}` option.

About Non-standard projections. 
- This should be done in a format independent way.
- We are building out geospatial math library in the math.gl repo, we could put transformation library there
- We could have helper functions in the GIS category module you are currently working on.


About GPX
- Don't know much about it, but if it geospatial it is worth considering.

**Comment by ibgreen** [comment]
Available in v2.3.0
