### ISSUE TITLE
typescript definitions

### ISSUE THREAD

**Issue by ibgreen** [visgl/loaders.gl#704]
- [x] Make all non-tile code in loaders.gl pass through typescript linting using `tsc` #670
- [ ] Make tile code in loaders.gl pass through typescript linting using `tsc`
- [x] Add `.d.ts` definitions to core modules that export APIs #670
- [ ] Add `.d.ts` definitions to all modules that export APIs

**Comment by cooperrf** [comment]
Hello,

I'm using deck.gl in a project and running into some trouble with loaders.gl.

`node_modules/@loaders.gl/core/src/lib/common.d.ts` imports `fetch-file.browser` from the polyfills module.  I added the polyfills module to my `package.json` file, but the `wip` directory isn't being installed for some reason.

I'm seeing this error when building:
<img width="1112" alt="Screen Shot 2020-07-13 at 9 06 44 AM" src="https://user-images.githubusercontent.com/65512165/87308307-0b0c4900-c4e9-11ea-8c46-26c5b613339d.png">

This is the import in that file:
![Screen Shot 2020-07-13 at 9 13 29 AM](https://user-images.githubusercontent.com/65512165/87308489-51fa3e80-c4e9-11ea-8477-7840da086cae.png)

This is what my `@loaders.gl` directory looks like in `node_modules`:
![Screen Shot 2020-07-13 at 9 14 23 AM](https://user-images.githubusercontent.com/65512165/87308567-6807ff00-c4e9-11ea-987b-11d00c8d388d.png)

And these are the lines in my `package.json` file:
![Screen Shot 2020-07-13 at 9 13 43 AM](https://user-images.githubusercontent.com/65512165/87308603-7524ee00-c4e9-11ea-978a-89425555e8f7.png)

Any ideas?  Thanks!

**Comment by ibgreen** [comment]
@cooperrf Yes, this looks like a bug, that file is still available in the core module, and core should not be looking for it in polyfills.

Try v2.2.7

**Comment by cooperrf** [comment]
That's excellent.  Thanks for the super quick turnaround!!
