### ISSUE TITLE
why the threejs example has dependencies with mapbox?

### ISSUE THREAD

**Issue by kavinforever** [visgl/loaders.gl#724]
Hi：
  I am searching for a solution for Threejs with 3d tiles, loaders.gl sounds a great idea.
However, when i download the code,  I found the threejs example depend on the map instance created by mapbox. 

![image](https://user-images.githubusercontent.com/9795441/79294915-f5977b00-7f09-11ea-866c-8ac00d214dd9.png)

**Comment by kavinforever** [comment]
Also the example dependencies
```
"@loaders.gl/3d-tiles": "^2.1.1"
```
this version not includes "Tileset3D" func, so the exmaple cannot run.

![image](https://user-images.githubusercontent.com/9795441/79296925-55445500-7f0f-11ea-8d70-a448b844b611.png)

**Comment by ibgreen** [comment]
> I am searching for a solution for Threejs with 3d tiles, loaders.gl sounds a great idea.

Yes, loaders.gl is intended to work with any WebGL framework, including THREE.js. That said, so far we do not have any active contributor who helps us build THREE.js examples.

> However, when i download the code, I found the threejs example depend on the map instance created by mapbox.

The mapbox dependency is a "bonus" - it shows how to get a synchronized mapbox basemap under THREE.js rendering. It is not a required dependency. You should be able to easily cut it out of the example if you don't want/need that.

> This version not includes "Tileset3D" func, so the exmaple cannot run.

You are right, this example was a work-in-progress and it has not been updated to the latest version. Unless you have some time to spend on this, I regret to say that right now this is not a working example.

We should probably move it to the `test/apps` folder for now. @xintongxia

**Comment by yoyomule** [comment]
Is the solution using Three.js + LoaderGL feasible now? I found that the 3d-tiles-with-three.js example in examples-experimental does not run properly. I am very much looking forward to the realization of this feature. Thank you.
