### ISSUE TITLE
i3sLayer support 

### ISSUE THREAD

**Issue by The-End-Hero** [visgl/loaders.gl#730]
https://tiles.arcgis.com/tiles/m0PBUckKDOxneVs5/arcgis/rest/services/test_3d_logo/SceneServer/layers/0

For the above services, i3sLayer reports an error.
![image](https://user-images.githubusercontent.com/19590233/80692465-30053880-8b04-11ea-8056-a545991243a6.png)

**Comment by The-End-Hero** [comment]
https://tiles.arcgis.com/tiles/m0PBUckKDOxneVs5/arcgis/rest/services/test_3d/SceneServer/layers/0

**Comment by The-End-Hero** [comment]
https://tiles.arcgis.com/tiles/m0PBUckKDOxneVs5/arcgis/rest/services/test_3d/SceneServer/layers/0
The above services can be displayed normally

**Comment by xintongxia** [comment]
@The-End-Hero 

`I3SLoader` currently doesn't support parsing `region`, also the above link requires a token.

**Comment by mdt-kathur** [comment]
> @The-End-Hero
> 
> `I3SLoader` currently doesn't support parsing `region`, also the above link requires a token.

I post a reply on Deck.gl.
https://github.com/visgl/deck.gl/issues/4554

My guess is the same as yours.

Did you have any idea on how the `region` tag is generated?  I thought the `region` tag result from some special texture effects. The San Francisco one from example despite having texture, there's no `region` tag in JSON file 

https://tiles.arcgis.com/tiles/z2tnIkrLQ2BRzr6P/arcgis/rest/services/SanFrancisco_Bldgs/SceneServer

**Comment by ibgreen** [comment]
@Tamrat-B

**Comment by Tamrat-B** [comment]
@The-End-Hero

The region concept in i3s is not a result of special texture effects but its rather a per vertex texture coordinate information (provided as Umin, Vmin, Umax, Vmax, of 4 Uint16s (they are in the range of 0-1 but normalized as Unit16) needed to wrap the UV coordinates of repeating textures in the texture atlas. Typically the texture is written in the atlas with extra border to avoid bleeding. 

@ibgreen @xintongxia 
In i3s 1.6 and (similarly also in 1.7) the presence or absence of regions are indicated in the 3D Scene Layer resource by `store.defaultGeometrySchema.vertexAttributes ` property and its ordering in the geometry buffer by `store.defaultGeometrySchema.order ` property:

![image](https://user-images.githubusercontent.com/12946567/81255908-cdb8a600-8fe3-11ea-87a3-ed62c6144a49.png)

Here is an an example of an i3s service with Uv region form  a publicly available service in arcgis.com for the City of Lyon:
https://www.arcgis.com/home/item.html?id=972497cf7ddd4b69bfaac2c3310cfeea

Inspecting the _buildings_ layer [service url](https://services2.arcgis.com/cFEFS0EWrhfDeVw9/arcgis/rest/services/STM____FR_Lyon__Textured_buildings/SceneServer/layers/0?f=pjson), you can see that this layer has nodes that have region info:

Here is an example of a node, (node 41 and its descendant child nodes) with region info. Taking a look at the [leaf node](https://services2.arcgis.com/cFEFS0EWrhfDeVw9/arcgis/rest/services/STM____FR_Lyon__Textured_buildings/SceneServer/layers/0/nodes/41-0-0-0-0-0-0-0-0) of this branch you'll notice the 
the presence of region is indicated by the `materialDefinitions.Mat5115.params.vertexRegions`  in the [shared](https://services2.arcgis.com/cFEFS0EWrhfDeVw9/arcgis/rest/services/STM____FR_Lyon__Textured_buildings/SceneServer/layers/0/nodes/41-0-0-0-0-0-0-0-0/shared) resource of the node. Its byte offset is declared in the [feature](https://services2.arcgis.com/cFEFS0EWrhfDeVw9/arcgis/rest/services/STM____FR_Lyon__Textured_buildings/SceneServer/layers/0/nodes/41-0-0-0-0-0-0-0-0/features/0) data document in  `geometryData[0].params.vertexAttributes.region` property. But note that this information could also be directly calculated from the geometry payload itself. Note: loaders.gl has implemented this more efficient traversal pattern avoiding the need to rely on the feature data document.

@xintongxia noted though, I3S Loader in loaders.gl has not yet implemented support for goemetry payloads with the per vertex region info so such nodes will fail when consumed in loaders.gl

Hope this helps.

**Comment by mdt-kathur** [comment]
thanks for the explanation！ I'm wondering, currently, is there a way to ignore `region` info, and publish a clean scene service through ArcGIS pro?

**Comment by Tamrat-B** [comment]
@mdt-kathur 
presence or absence of region info depends on the input data source. The example provided in the loaders.gl example app for San Francisco actually **does not** have any nodes with region info.
The layer item is located [here](https://www.arcgis.com/home/item.html?id=d3344ba99c3f4efaa909ccfbcc052ed5) and its service url can be accessed thru [this](https://tiles.arcgis.com/tiles/z2tnIkrLQ2BRzr6P/arcgis/rest/services/SanFrancisco_Bldgs/SceneServer/layers/0) end point.

**Comment by ibgreen** [comment]
@Tamrat-B What would it take to support this?
- Is the region info "optional"?
- I.e we just need to make sure we ignore it, then we at least can display the rest? 

Of course. long term we should handle all features, but until then I'd generally prefer that we display something rather than nothing.

**Comment by ibgreen** [comment]
@morphoix Perhaps you can test and see if this is still an issue?

**Comment by morphoix** [comment]
@ibgreen I checked tit with the Lyon example which also has 'region' at defaulGeometrySchema 
no errors detected 
![check](https://user-images.githubusercontent.com/53499331/120618963-3af76e80-c464-11eb-877b-5493d0e9ebeb.png)
