### ISSUE TITLE
New geospatial loader: NMEA 0183

### ISSUE THREAD

**Issue by isaacbrodsky** [visgl/loaders.gl#737]
NMEA files are generated by some GPS loggers, and contain location, time, satellites visible/their SNR, etc. data.

For more information, see:
https://en.wikipedia.org/wiki/NMEA_0183
https://wiki.openstreetmap.org/wiki/NMEA

**Comment by ibgreen** [comment]
GPX and TCX are supported now in `@loaders.gl/kml`.

NMEA parser is available here, if we have some test files we can try.
