### ISSUE TITLE
GPX Loader

### ISSUE THREAD

**Issue by kylebarron** [visgl/loaders.gl#738]
A split of https://github.com/visgl/loaders.gl/issues/701 to focus on GPX:

### GPX

A common data format used by GPS devices. In contrast to Shapefiles, would be a more common format for user-provided data on a website not geared towards GIS professionals.

[`mapbox/togeojson`](https://github.com/mapbox/togeojson) is a freely licensed project to convert KML and GPX (which are both XML based) to GeoJSON. I see you currently have a KML parser (though `togeojson` supports both browsers and Node, which would be an improvement).

According to the [spec](https://en.wikipedia.org/wiki/GPS_Exchange_Format#Units), GPX coordinates are always in WGS84, so no reprojection would be needed.

**Comment by kylebarron** [comment]
GPX is a broad specification (closer to KML in my opinion), so loading it to GeoJSON might lose some information, and a GPX -> GeoJSON -> GPX roundtrip might in general be hard to create the same GPX file.

**Comment by ibgreen** [comment]
Replacing the KML parser is fair game, it was a super hacky thing. The only thing it has going for it is small bundle size on browsers.

A long-term ideal implementation would be to build a streaming XML parser on top of sax (similar to how the streaming JSON parser is built on top of clarinet).

But a streaming loader would be a lot of work and current usage of these formats do not justify it (and not clear the size of such files justify it either), so I'd be very supportive of building loaders on top of the mapbox module for now.

**Comment by kylebarron** [comment]
I agree. Good formats to support, but not a priority for performance tuning. Some GPX files can be large, but I think those would tend to be converted to other formats before being used on the web.

> In general I would personally prefer to offer such loaders with two modes / output format - a mode that is not lossy, and a mode that converts to geojson (options.gpx.geojson: true).
> 
> What the non-geojson output format should be is up for discussion. It could be custom for each loader (whatever the underlying loaders return), lightly normalized, or geojson with extensions, etc.

From https://github.com/mapbox/togeojson#should-togeojson-support-feature-x-from-kml

> This module should support converting all KML and GPX features that have commonplace equivalents in GeoJSON.

So I think using the Mapbox library to load KML/GPX only has the lossy option, but is still a wide range of each spec.

**Comment by zarov** [comment]
FIY, the current mapbox module is kinda abandoned, and the original creator is currently maintaining it [here](https://github.com/tmcw/togeojson).

**Comment by kylebarron** [comment]
Thanks for the tip. It looks like `togeojson` would be easy to integrate in a non-streaming manner, so I might try it sometime soon and see if it's quick to do.
