### ISSUE TITLE
GDAL integration for Node.js

### ISSUE THREAD

**Issue by ibgreen** [visgl/loaders.gl#757]
We could offer [GDAL](https://www.npmjs.com/package/gdal)-backed Loaders when under Node.js.

It would be a deviation from the general principle that loaders should be available under all platforms, but likely well worth an exception given the rich format support in GDAL.

@isaacbrodsky

**Comment by kylebarron** [comment]
well it doesn't _have_ to be just Node...

https://github.com/ddohler/gdal-js
https://github.com/azavea/loam

**Comment by ibgreen** [comment]
Interesting. Those emscripten files are probably huge, but if we can use the dynamic CDN loading feature in loaders.gl...

**Comment by kylebarron** [comment]
`gdal.wasm` is 6.1MB, 2.2MB gzipped
