### ISSUE TITLE
Define `lib` in tsconfig

### ISSUE THREAD

**Issue by kylebarron** [visgl/loaders.gl#776]
While developing in loaders.gl modules, my typescript linter complains about multiple language features, e.g.

- Cannot find global value 'Promise'.
- Property 'values' does not exist on type 'ObjectConstructor'.
- An async function or method in ES5/ES3 requires the 'Promise' constructor

I believe this is because the `lib` field in `tsconfig.json` is missing. From [the docs](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#including-built-in-type-declarations-with---lib)

> with `--lib` you can specify a list of built-in API declaration groups that you can chose to include in your project. For instance, if you expect your runtime to have support for `Map`, `Set` and `Promise` (e.g. most evergreen browsers today), just include `--lib es2015.collection,es2015.promise`

So when I define
```json
"lib": ["es5", "es2016", "es2017"],
```
in the `tsconfig.json`, all linter errors go away.

I'm not sure what language features we use in code; the [docs page](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#including-built-in-type-declarations-with---lib) includes a list of allowed values.

**Comment by ibgreen** [comment]
Since this is Atom specific will close for now until we understand this better.
