### ISSUE TITLE
polyfill zlib issue - "Module not found: Error: Can't resolve 'zlib'"

### ISSUE THREAD

**Issue by SterlingMcCall** [visgl/loaders.gl#805]
With [this recent change](https://github.com/visgl/loaders.gl/pull/782/files#diff-6b856ba9b575d2265c289d4b0b3d4643) made by @ibgreen the zlib import was changed from `const zlib = require('zlib');` to `import zlib from 'zlib';`.

This introduction has resulted in the following error when building my application (which uses angular, deck.gl, and the loader.gl polyfills):
```
ERROR in ./node_modules/@loaders.gl/polyfills/dist/esm/fetch-node/utils/stream-utils.node.js
Module not found: Error: Can't resolve 'zlib' in '/home/<REDACTED>/node_modules/@loaders.gl/polyfills/dist/esm/fetch-node/utils'
```

While I don't understand the reasoning completely, my understanding is that node libraries such as fs, http, and zlib are not available in web browsers, and thus need to have entries added in the `package.json`'s `"browser"` field in order to work properly.

I found that adding `"zlib": false` to the `"browsers"` array in [modules/polyfills/package.json](https://github.com/visgl/loaders.gl/blob/master/modules/polyfills/package.json#L28) fixes my problem. However, modifying the `package.json` within my project's `node_modules/@loaders.gl` directory is not a viable long-term fix and I believe it should be changed in this repo.

If this is not the solution and I am doing something wrong, please let me know.

**Comment by ibgreen** [comment]
Yes we added support for compressed data to the fetch polyfill in the new 2.2. release but forgot to exclude the new library in the browser. I have put up a PR and we'll have a patch out today.

**Comment by ibgreen** [comment]
Try 2.2.2
