### ISSUE TITLE
3d-tiles conversion from las/laz

### ISSUE THREAD

**Issue by muyanchen-zen** [visgl/loaders.gl#854]
I use command `./bin/Model3DTiler -i ./lasdata -o out_dir --output-format PNTS --longitude 126.805654 --latitude 31.240908 --altitude 12.9855` to convert my las file into 3d-tiles, but it can't be shown throw websit.
My las files datas' coordinate system is EPSG 4510 ，and what should I do if I want show my data ? 
Thank You!

some info:
```sh
 min x y z:                  367663.3350 3463936.3763 12.6787

$ proj -I +proj=tmerc +k=1 +x_0=5000 +lon_0=123 +ellps=WGS84 -f "%.6f"
367663.3350 3463936.3763 12.6787
126.805654      31.240907 12.6787
```

**Comment by ibgreen** [comment]
This is not supported by loaders.gl, however you might want to look at @hobu 's PDAL which I believe can handle point cloud reprojection: https://pdal.io/workshop/exercises/translation/reprojection.html

Would be great to get an update on whether you get this work.

**Comment by muyanchen-zen** [comment]
Yeah , I've noticed that I must transform coordinate system to epsg 4978 first.
