### ISSUE TITLE
How to load point cloud data on Mapbox gl js

### ISSUE THREAD

**Issue by Georger2323** [visgl/loaders.gl#868]
I use Mapbox gl js and I would like to load point cloud data on the map (in .ply or .las format). However, I haven't found any example yet on how to load a .ply or .las file on Mapbox gl js. 

There are a few examples here and there but they all miss something. For example [this one](https://github.com/visgl/loaders.gl/blob/master/examples/website/pointcloud/app.js) is in React and mapbox is not used (But I use pure JS and mapbox).

[This example](https://gist.github.com/elijahzarlin/b32db94afc2352b326b9063b1228311d)  would be the perfect one, but the data are loaded in .json format and not in .ply, so again, no help from here. 

I would appreciate it if someone could guide me on how to load the desired data.

**Comment by kylebarron** [comment]
In both of these, [deck.gl](https://deck.gl) is doing the point cloud rendering, and Mapbox GL JS is only used for the basemap. Mapbox GL JS does not have support for point cloud rendering, I believe.

**Comment by ibgreen** [comment]
Yes the PLYLoader can be used, it requires a small amount of glue code. The necessary code can be found in `examples/website/point-cloud` in the loaders.gl repo.

I don't have any minimal gist to share unfortunately, so it would require some ability to read code and understand what needs to be done.

**Comment by Georger2323** [comment]
> Yes the PLYLoader can be used, it requires a small amount of glue code. The necessary code can be found in `examples/website/point-cloud` in the loaders.gl repo.
> 
> I don't have any minimal gist to share unfortunately, so it would require some ability to read code to understand what needs to be done.

The example you provide is the same one I mentioned on my post.
The problem with that example, as I said, is that it's in React and doesn't use Mapbox.

**Comment by ibgreen** [comment]
Yes understood. My point was just that the parts of the code from that example do not depend on React at all and can be reused in your example. And yes, I do understand that it may require a bit more work to figure out exactly what is needed than you are prepared to spend on it, and that a complete example would have been really valuable.

The goal has always been that the point cloud loaders should work seamlessly with deck.gl without the need for any glue code, but so far we didn't quite get there.
