### ISSUE TITLE
Add version to loaders global

### ISSUE THREAD

**Issue by kylebarron** [visgl/loaders.gl#908]
Deck.gl and luma.gl have `VERSION` keys set on their global object, so you can check `deck.VERSION` or `luma.VERSION` respectively. Loaders.gl doesn't appear to set this; I think it would be helpful for debugging.

**Comment by ibgreen** [comment]
It should not be hard to add, version is already injected for loader version checking.

https://github.com/visgl/loaders.gl/blob/112b16c544debdebaf17dfefad9814107e9e6283/modules/loader-utils/src/lib/validate-loader-version.js

**Comment by ibgreen** [comment]
There are a lot of submodules so maybe this should be set by `core`?

**Comment by kylebarron** [comment]
Yes I would expect it to go in `core`, similar to in deck
