### ISSUE TITLE
Terrain Loader: passing function as elevation decoder

### ISSUE THREAD

**Issue by sw1227** [visgl/loaders.gl#936]
## Suggestion

Currently only `rScaler` `gScaler`, `bScaler`, and `offset` can be specified for decoder, assuming the following encoding format:

```javascript
r * rScaler + g * gScaler + b * bScaler + offset
```

However, some elevation tiles do not conform to this format. In such cases, it would be great if we can pass a function as elevation decoder.

Related code:
https://github.com/visgl/loaders.gl/blob/master/modules/terrain/src/lib/parse-terrain.js#L18

## Background
I was trying to use [PNG elevation tile by Geospatial Information Authority of Japan (ja)](https://maps.gsi.go.jp/development/demtile.html) in deck.gl TerrainLayer, but found that it cannot be decoded by loaders.gl TerrainLoader.

For those who cannot read Japanese, I have re-written the encoding format in English, too.
https://observablehq.com/@sw1227/decoding-png-elevation-tile
It basically looks similar to other encodings (e.g. [Mapze Terrain Tiles](https://github.com/tilezen/joerd/blob/master/docs/formats.md)), but includes if-condition.

If this suggestion seems acceptable, maybe I can send Pull request.

**Comment by ibgreen** [comment]
@sw1227 This is a very reasonable feature proposal. 

However there is a significant complication in that for performance reasons, we (optionally) run this loader on a worker thread, using a pre-built worker script, and passing functions to worker threads does not work as data is serialized and deserialized during message passing.

Also the rules you have are complicated enough that they can't really be described by a matrix or a set of parameters, so they really do need a function.


@chrisgervang @kylebarron Any ideas?

**Comment by ibgreen** [comment]
I suppose an alternative is that we build in support for a number of well-known, named formats (i.e. we have a table of elevation decoder functions built-in to the loader).

**Comment by kylebarron** [comment]
I personally feel this is a bit of a special case. @ibgreen is right that because we optionally do decoding on a worker, we can't pass an arbitrary function to the parsing code. I don't have a great suggestion.
