### ISSUE TITLE
Tile3DLayer: show nothing when loading my data from Cesium Ion

### ISSUE THREAD

**Issue by HuyHoang-Ta** [visgl/loaders.gl#939]
Hello everyone, currenly I am using Tile3DLayer to display Tileset JSON data fetched from Cesium Ion. The Tile3DLayer can display sample data from Cesium Ion but when I use my data, nothing appears, just a blank black screen. My data is converted from point cloud laz file through Cesium Ion and it can be viewed from Cesium.

**Comment by ibgreen** [comment]
Do you get any errors in the console that might be helpful?

Are you able to share a code sandbox or data?

**Comment by HuyHoang-Ta** [comment]
1. Data displayed with [Cesium](https://sandcastle.cesium.com/#c=jVNdb9s4EPwrCz+0MhBQTlIfkIsTXOogqVzLPttKmgR6YaR1zJgiVZL+PPS/dyXabq64FvckUTuzmpldhiHcGq4cdNGKRdGbAM8ytBacho1eGBBaAbcWnU2Vx7BIK5bjlC+ku6rBiZ6jggtIG7jpzZ5vMzEUvehuGx0PRGQjNW5n3eiPaF4+3Hd7Z4xAX/PbOYGiD4+v2UmcDF4fRWsTJ/ezfjLaxNcvbpjcF7ForeLXx5Ph7ehk+CVuPSUj0e/2yidqFm9H63h7Z6NCzvLqnNy1h0nWjq+z9uBTi338UE7i4qE/H/XOZDl8GH8aPPSG5usN9nPxNF5148n0dLw9/fwxShvnqUrVkhtYClyhIScKV7tE2H39LUgbWX3uauW4UGjSRvPAc0IiRURE34HZDBWy0ohCOLFEy3ieB6mCt4394/Q68eTgn6oOsDDyT/iR9BgtjSFDNjW6uKoGEeXBcfv45OyseeQZYZjMhD2IyDVa9d7BjC8ROEidcUdTPAKrYYXvDcLCCvVCpULnKGPujFhX8y4lzxCEA+6gdQQtEMo65DnoKeSGr2qSAzdDIHuOgqJCdUJu3MxredPy4CKhBbNTbQrLkFs30IS+KxN9I9aY3xheYODJcIiGGtIbV6e17Wt8MYg2qEQ1PdR7/0YnP4WdeWZI7+Zv4giLFYKRPhVMFyqrMoCgCbuYd4Paal0kOtjRfS+fKVyVpdzU/nbLDtZtJAU0rTLCtbDVnah70Qrg2hluaQP2SupLw/znc48j5s9OqTUtUx54XBPevfstgJGJ/wXaX9BJJXmf2d47HER6Rxe/Wsua/cuuO1ff9pOgtDXFZVaU/ZvI0RhtDv/OtLJaIpP6ZVc593x6NI4anVrRZfXpL1GUtCrVhQgYCx0WtKC0FuHzIpuT9szaitQJ95ROLpYg8ov/uKqQSZoHVaYLKSdii2njshMS/l80qXlOSz5copF8Q5BKRmd2fNn3BcZYJ6Rj9dOfuU5r+czNm77fAQ)

2. [Code sandbox](https://codesandbox.io/s/3dtile-kfu6l?file=/src/App.js). The Cesium ION sample data can be displayed but my data shows nothing

3. My data is downloaded from [Cesium document](https://cesium.com/docs/tutorials/import-point-clouds/). Download link: https://s3.amazonaws.com/cesiumjs/downloads/House.laz

**Comment by ibgreen** [comment]
@HuyHoang-Ta Thanks for the links. 

From the code window in the Cesium sandbox in your link I read:

`// This tileset doesn't have a location, so we're using a modelMatrix to place it at 0, 0 instead of drawing at the center of the earth`

We have so far not targeted non-geospatial tilesets. I.e. loaders.gl expects the tile coordinates to be WGS84 cartesian. It might be possible to add a deck.gl `Layer` modelMatrix to deal with this, like Cesium example does, but I am honestly not 100% sure if this would work.

**Comment by ibgreen** [comment]
@HuyHoang-Ta For an API to help you create the model matrix, similar to what the Cesium example is using, take a look at [`@math.gl/geospatial`](https://math.gl/modules/geospatial/docs/api-reference/ellipsoid).

Try to update your code sandbox and I can take a look.

**Comment by FreakTheMighty** [comment]
@ibgreen I'm wondering if you can expand on how to proceed for non-geospatial use? I'm attempting load a non-geospatial set tileset into babylonjs. The tileset is at the origin, and I'm struggling to make sense of what values I can pass loader.gl to get the query to work.

If geospatial is still a requirement for loader.gl, would it be possible to pick an arbitrary reference frame?
