### ISSUE TITLE
Problem running tests under Ubuntu 20.04

### ISSUE THREAD

**Issue by jmking** [visgl/loaders.gl#949]
Hi there. I'm trying to get a dev environment for loaders.gl running on Ubuntu 20.04. Having followed the instructions [here](https://loaders.gl/docs/developer-guide/dev-env) (including installing the dependencies listed for Linux) but I'm not having much luck. 

I've run `yarn bootstrap`. `yarn test node` succeeds. Running `yarn test browser` (which seems top successfully opens Chromium on my desktop) yields:
```
Running browser tests...
browser-driver: Browser Test
browser-driver: Started webpack-dev-server at http://localhost:5000
browser-driver: Loading page in browser...
browser-driver: Browser Test failed: Page crashed!
```

Running `yarn test` looks healthier as lots of tests pass however it still fails on the lz4#defaults tests with the message:
`browser-driver: Browser Test failed: Page crashed!`

One thing to note is that instructions for starting xvfb did not work for me. `/etc/init.d/xvfb` does not exist. To start that I've used:
```
export DISPLAY=:99.0
Xvfb $DISPLAY
```
Which as far as I can tell should get me where I need to be. 

Any advice would be much appreciated. If I can get this working I'd me more than happy to write some Ubuntu specific dev environment documentation. Thanks!

**Comment by ibgreen** [comment]
@jmking Thanks for reporting. 

Unfortunately I am not easily able to reproduce on a specific version of Ubuntu, but let me make a few quick observations in case they can help you.
- `yarn test` runs `yarn test node` and `yarn test browser-headless` - the latter runs chromium puppeteer just like `yarn test browser` but this time just without a window. 
- So it is expected that you would get the same failures here.

Your indications point to the `lz4` library having problems on Ubuntu 20. You can comment it out to confirm
- Comment out compression in `test/modules.js`
- Comment out lz4 tests in  `modules/compression/test/index.js`
- If so you may want to raise an issue in the `lz4js` repo.

Also
- `xfvb` should be required for the final couple of rendering tests only, which pulls in luma.gl/deck.gl, the rest of loaders.gl is WebGL independent. 
- Perhaps you can add a note on this to https://loaders.gl/docs/developer-guide/dev-env?
