### ISSUE TITLE
Problem encoding glb

### ISSUE THREAD

**Issue by alfyorov** [visgl/loaders.gl#973]
Hello everyone.
I am trying to convert a glTF into glb, that is, to store a base64-encoded data from glTF as a binary payload in glb.

```
async function GltfToGlbTest() {
  const gltfData = await load(GLTF_URL, GLTFLoader, {
    gltf: { postProcess: false, loadBuffers: true, loadImages: false }
  });
  const gltf = new GLTFScenegraph(gltfData);

  encode(gltf, GLBWriter, {}).then(arrayBuffer => {
    const glbData = new Uint8Array(arrayBuffer)
    const file = new Blob([glbData], { type: "model/gltf.binary" });
    saveAs(file, "glfToGlb.glb");
  });
}
```

The problem is, that a `encodeGLBSync()` in [encode-glb.js](https://github.com/visgl/loaders.gl/blob/master/modules/gltf/src/lib/encode-glb.js) attaches the payload only if the given `glb `object has a property `binary`.
But the binary data from glTF is saved in `gltf.buffers` as ArrayBuffer and I can't find where and how the `binary `property can be set.

Any help will be appreciated. Thanks!

**Comment by ibgreen** [comment]
@belom88 You were just using this feature, maybe you can support?

**Comment by belom88** [comment]
`binary` should be inside there just after loading.
If you are not going to modify `gltfData`, you should pass it into "writer" as is (without GLTFScenegraph initialization).
`encode(gltfData, GLBWriter, {}).then(arrayBuffer => {`
or
` encode(gltf.gltf, GLBWriter, {}).then(arrayBuffer => {`
should work in your case.

**Comment by belom88** [comment]
@alfyorov Take a look at test https://github.com/visgl/loaders.gl/blob/a2f250c6e7d51bc500455cdcd282f7d0db722e79/modules/gltf/test/gltf-writer.spec.js#L88
New changes was merged recently. I believe they will be in next release.

**Comment by alfyorov** [comment]
Thanks a lot!
When is the next release?
