### ISSUE TITLE
3d-tiles: `gltf.json.buffers` undefined for some tilesets

### ISSUE THREAD

**Issue by ibgreen** [visgl/loaders.gl#983]
See deck.gl issue https://github.com/visgl/deck.gl/issues/4698

@belom88 @vdunaev FYI

**Comment by ibgreen** [comment]
@vdunaev Did we fix this one?

**Comment by ibgreen** [comment]
@belom88

**Comment by Pessimistress** [comment]
Can we publish a patch to include this fix?

**Comment by ibgreen** [comment]
@vdunaev is planning to publish a loaders 2.3 patch next week.
