### ISSUE TITLE
@loaders.gl/shapefile compile issue Can't resolve 'fs' 

### ISSUE THREAD

**Issue by digiiitalmb** [visgl/loaders.gl#988]
I'm trying to compile my JS using laravel-mix and I keep getting this error:

```
ERROR in ./node_modules/@loaders.gl/shapefile/dist/esm/lib/filesystems/node-filesystem.js
Module not found: Error: Can't resolve 'fs' in '/home/forge/**************/node_modules/@loaders.gl/shapefile/dist/esm/lib/filesystems'
```

I though I simply missing the fs module, so I ran `npm install fs` but that didn't help, any help would be appreciated.

**Comment by ibgreen** [comment]
@digiiitalmb Thanks for reporting

Looks like we have missed a "browser" clause excluding `fi` in the `package.json` for the Shapefile module
- https://github.com/visgl/loaders.gl/blob/master/modules/core/package.json#L34
- https://github.com/visgl/loaders.gl/blob/master/modules/shapefile/package.json#L29

That should work for most modern bundlers, though I can't be sure whether that actually would fix things in your environment, as I don't know much about how laravel builds things.
