### ISSUE TITLE
Using loaders.gl

### ISSUE THREAD

**Issue by Arsakes** [visgl/loaders.gl#998]
This may be very stupid question:
Is there a way to use this library on serverside/node.js with `require` impport statements?
I couldn't find an example of such usage, I've tried to use code below, yet error pops up:

```
const polyfills = require('@loaders.gl/polyfills');
const Core = require(@loaders.gl/core');
const OBJLoader = require(@loaders.gl/obj');

Loaders.load(<filepath>, OBJLoader);

```
This gives following error.
```
Error: No valid loader found data: "", contentType: "null" url: forest_encounter_navmesh.obj
    at _callee$ (/home/pietrko/projekty/warhammer/web-aom/node_modules/@loaders.gl/core/dist/es5/lib/api/select-loader.js:93:19)
```

Can you provide an example how to use loader to load some `.obj` file with it?

**Comment by kylebarron** [comment]
Usually with newer `import` syntax it would be
```js
import {load} from '@loaders.gl/core';
import {OBJLoader} from '@loaders.gl/obj';
```
So can you try instead with
```js
const Core = require('@loaders.gl/core');
const OBJLoader = require('@loaders.gl/obj');

Loaders.load(<filepath>, OBJLoader.OBJLoader);
```

**Comment by ibgreen** [comment]
Also, unless you are using other polyfills for fetch etc, you will likely want to add

```js
require('@loaders.gl/polyfills');
```
