### ISSUE TITLE
Offline use of Las Loader

### ISSUE THREAD

**Issue by oomcreative** [visgl/loaders.gl#999]
Is it possible to use Las Loader in offline contexts? Have integrated this package to view LIDAR data and it's great, but then when offline it stops loading data - because it has a dependency & lookup to https://unpkg.com/. 

Is there is solution to make this work without needing to reference to unpkg.com? Can we import this module in a different way, or need to recompile it? As we are working on project that needs to work with & without internet connection. 

Using standard import 

```
import { LASLoader } from "@loaders.gl/las";
import { load } from "@loaders.gl/core";
```

async function loadLaz(fileName) {

In src/las-loader.js is where the link to Unpkg is in options/las.

```
export var LASWorkerLoader = {
  id: 'las',
  name: 'LAS',
  version: VERSION,
  extensions: ['las', 'laz'],
  mimeType: 'application/octet-stream',
  text: true,
  binary: true,
  test: 'LAS',
  options: {
    las: {
      workerUrl: "https://unpkg.com/@loaders.gl/las@".concat(VERSION, "/dist/las-loader.worker.js")
    }
  }
};
```

Thanks in advance for any tips on making this work

**Comment by kylebarron** [comment]
You can set the worker url to a local script, e.g.:

https://github.com/visgl/loaders.gl/blob/f7c1b2185516b86ecc92039140f21f94bdfbe274/modules/terrain/test/terrain-loader.spec.js#L11-L15

Or just pass in 
```js
load(url, LASLoader, {las: {workerUrl: ... }})
```

**Comment by oomcreative** [comment]
thanks @kylebarron that second option has worked perfectly: having the script locally and then referencing it at load time
